/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { IndiciaError } from "./indicia-error.js";

/**
 * Bypass failed
 */
export type BypassDoubleCounterInternalServerErrorData = {
  success: boolean;
  error?: string | undefined;
};

/**
 * Bypass failed
 */
export class BypassDoubleCounterInternalServerError extends IndiciaError {
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: BypassDoubleCounterInternalServerErrorData;

  constructor(
    err: BypassDoubleCounterInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "BypassDoubleCounterInternalServerError";
  }
}

/** @internal */
export const BypassDoubleCounterInternalServerError$inboundSchema:
  z.ZodMiniType<BypassDoubleCounterInternalServerError, unknown> = z.pipe(
    z.object({
      success: types.boolean(),
      error: types.optional(types.string()),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new BypassDoubleCounterInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
