/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { IndiciaError } from "./indicia-error.js";

/**
 * A failed API response.
 */
export type FailedResponseErrorData = {
  /**
   * Always `false` for error responses.
   */
  success: boolean;
  /**
   * Human-readable error message.
   */
  error?: string | undefined;
};

/**
 * A failed API response.
 */
export class FailedResponseError extends IndiciaError {
  /**
   * Always `false` for error responses.
   */
  success: boolean;
  /**
   * Human-readable error message.
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: FailedResponseErrorData;

  constructor(
    err: FailedResponseErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "FailedResponseError";
  }
}

/** @internal */
export const FailedResponseError$inboundSchema: z.ZodMiniType<
  FailedResponseError,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    error: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new FailedResponseError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
