/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { IndiciaError } from "./indicia-error.js";

/**
 * Internal Server Error
 */
export type PostV1SearchInfrastructureCertificatesInternalServerErrorData = {
  data: Array<
    operations.PostV1SearchInfrastructureCertificatesInternalServerErrorData
  >;
  success: boolean;
  error?: string | undefined;
};

/**
 * Internal Server Error
 */
export class PostV1SearchInfrastructureCertificatesInternalServerError
  extends IndiciaError
{
  data: Array<
    operations.PostV1SearchInfrastructureCertificatesInternalServerErrorData
  >;
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostV1SearchInfrastructureCertificatesInternalServerErrorData;

  constructor(
    err: PostV1SearchInfrastructureCertificatesInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.data = err.data;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "PostV1SearchInfrastructureCertificatesInternalServerError";
  }
}

/** @internal */
export const PostV1SearchInfrastructureCertificatesInternalServerError$inboundSchema:
  z.ZodMiniType<
    PostV1SearchInfrastructureCertificatesInternalServerError,
    unknown
  > = z.pipe(
    z.object({
      data: z.array(z.lazy(() =>
        operations
          .PostV1SearchInfrastructureCertificatesInternalServerErrorData$inboundSchema
      )),
      success: types.boolean(),
      error: types.optional(types.string()),
      request$: z.custom<Request>(x =>
        x instanceof Request
      ),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new PostV1SearchInfrastructureCertificatesInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
