/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { IndiciaError } from "./indicia-error.js";

/**
 * Internal Server Error
 */
export type PostV1SearchInfrastructurePortscanInternalServerErrorData = {
  success: boolean;
  error?: string | undefined;
};

/**
 * Internal Server Error
 */
export class PostV1SearchInfrastructurePortscanInternalServerError
  extends IndiciaError
{
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostV1SearchInfrastructurePortscanInternalServerErrorData;

  constructor(
    err: PostV1SearchInfrastructurePortscanInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "PostV1SearchInfrastructurePortscanInternalServerError";
  }
}

/**
 * Payment Required - Insufficient Credits
 */
export type PostV1SearchInfrastructurePortscanPaymentRequiredErrorData = {
  success: boolean;
  error?: string | undefined;
};

/**
 * Payment Required - Insufficient Credits
 */
export class PostV1SearchInfrastructurePortscanPaymentRequiredError
  extends IndiciaError
{
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostV1SearchInfrastructurePortscanPaymentRequiredErrorData;

  constructor(
    err: PostV1SearchInfrastructurePortscanPaymentRequiredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "PostV1SearchInfrastructurePortscanPaymentRequiredError";
  }
}

/**
 * Bad Request
 */
export type PostV1SearchInfrastructurePortscanBadRequestErrorData = {
  success: boolean;
  error?: string | undefined;
};

/**
 * Bad Request
 */
export class PostV1SearchInfrastructurePortscanBadRequestError
  extends IndiciaError
{
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostV1SearchInfrastructurePortscanBadRequestErrorData;

  constructor(
    err: PostV1SearchInfrastructurePortscanBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "PostV1SearchInfrastructurePortscanBadRequestError";
  }
}

/** @internal */
export const PostV1SearchInfrastructurePortscanInternalServerError$inboundSchema:
  z.ZodMiniType<
    PostV1SearchInfrastructurePortscanInternalServerError,
    unknown
  > = z.pipe(
    z.object({
      success: types.boolean(),
      error: types.optional(types.string()),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new PostV1SearchInfrastructurePortscanInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const PostV1SearchInfrastructurePortscanPaymentRequiredError$inboundSchema:
  z.ZodMiniType<
    PostV1SearchInfrastructurePortscanPaymentRequiredError,
    unknown
  > = z.pipe(
    z.object({
      success: types.boolean(),
      error: types.optional(types.string()),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new PostV1SearchInfrastructurePortscanPaymentRequiredError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const PostV1SearchInfrastructurePortscanBadRequestError$inboundSchema:
  z.ZodMiniType<PostV1SearchInfrastructurePortscanBadRequestError, unknown> = z
    .pipe(
      z.object({
        success: types.boolean(),
        error: types.optional(types.string()),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new PostV1SearchInfrastructurePortscanBadRequestError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );
