/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { IndiciaError } from "./indicia-error.js";

/**
 * Internal Server Error
 */
export type PostV1SearchIntelligenceGeolocationInternalServerErrorData = {
  success: boolean;
  error?: string | undefined;
};

/**
 * Internal Server Error
 */
export class PostV1SearchIntelligenceGeolocationInternalServerError
  extends IndiciaError
{
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostV1SearchIntelligenceGeolocationInternalServerErrorData;

  constructor(
    err: PostV1SearchIntelligenceGeolocationInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "PostV1SearchIntelligenceGeolocationInternalServerError";
  }
}

/**
 * Payment Required - Insufficient Credits
 */
export type PostV1SearchIntelligenceGeolocationPaymentRequiredErrorData = {
  success: boolean;
  error?: string | undefined;
};

/**
 * Payment Required - Insufficient Credits
 */
export class PostV1SearchIntelligenceGeolocationPaymentRequiredError
  extends IndiciaError
{
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostV1SearchIntelligenceGeolocationPaymentRequiredErrorData;

  constructor(
    err: PostV1SearchIntelligenceGeolocationPaymentRequiredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "PostV1SearchIntelligenceGeolocationPaymentRequiredError";
  }
}

/**
 * Bad Request
 */
export type PostV1SearchIntelligenceGeolocationBadRequestErrorData = {
  success: boolean;
  error?: string | undefined;
};

/**
 * Bad Request
 */
export class PostV1SearchIntelligenceGeolocationBadRequestError
  extends IndiciaError
{
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostV1SearchIntelligenceGeolocationBadRequestErrorData;

  constructor(
    err: PostV1SearchIntelligenceGeolocationBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "PostV1SearchIntelligenceGeolocationBadRequestError";
  }
}

/** @internal */
export const PostV1SearchIntelligenceGeolocationInternalServerError$inboundSchema:
  z.ZodMiniType<
    PostV1SearchIntelligenceGeolocationInternalServerError,
    unknown
  > = z.pipe(
    z.object({
      success: types.boolean(),
      error: types.optional(types.string()),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new PostV1SearchIntelligenceGeolocationInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const PostV1SearchIntelligenceGeolocationPaymentRequiredError$inboundSchema:
  z.ZodMiniType<
    PostV1SearchIntelligenceGeolocationPaymentRequiredError,
    unknown
  > = z.pipe(
    z.object({
      success: types.boolean(),
      error: types.optional(types.string()),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new PostV1SearchIntelligenceGeolocationPaymentRequiredError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const PostV1SearchIntelligenceGeolocationBadRequestError$inboundSchema:
  z.ZodMiniType<PostV1SearchIntelligenceGeolocationBadRequestError, unknown> = z
    .pipe(
      z.object({
        success: types.boolean(),
        error: types.optional(types.string()),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new PostV1SearchIntelligenceGeolocationBadRequestError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );
