/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { IndiciaError } from "./indicia-error.js";

/**
 * Internal Server Error
 */
export type PostV1SearchIntelligencePhoneInternalServerErrorData = {
  success: boolean;
  error?: string | undefined;
};

/**
 * Internal Server Error
 */
export class PostV1SearchIntelligencePhoneInternalServerError
  extends IndiciaError
{
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostV1SearchIntelligencePhoneInternalServerErrorData;

  constructor(
    err: PostV1SearchIntelligencePhoneInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "PostV1SearchIntelligencePhoneInternalServerError";
  }
}

/** @internal */
export const PostV1SearchIntelligencePhoneInternalServerError$inboundSchema:
  z.ZodMiniType<PostV1SearchIntelligencePhoneInternalServerError, unknown> = z
    .pipe(
      z.object({
        success: types.boolean(),
        error: types.optional(types.string()),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new PostV1SearchIntelligencePhoneInternalServerError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );
