/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { IndiciaError } from "./indicia-error.js";

/**
 * Internal Server Error
 */
export type PostV1ToolsIntelxInternalServerErrorData = {
  success: boolean;
  data?: string | undefined;
};

/**
 * Internal Server Error
 */
export class PostV1ToolsIntelxInternalServerError extends IndiciaError {
  success: boolean;
  data?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostV1ToolsIntelxInternalServerErrorData;

  constructor(
    err: PostV1ToolsIntelxInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.data != null) this.data = err.data;

    this.name = "PostV1ToolsIntelxInternalServerError";
  }
}

/**
 * Bad Request
 */
export type PostV1ToolsIntelxBadRequestErrorData = {
  success: boolean;
  data?: string | undefined;
};

/**
 * Bad Request
 */
export class PostV1ToolsIntelxBadRequestError extends IndiciaError {
  success: boolean;
  data?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostV1ToolsIntelxBadRequestErrorData;

  constructor(
    err: PostV1ToolsIntelxBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.data != null) this.data = err.data;

    this.name = "PostV1ToolsIntelxBadRequestError";
  }
}

/** @internal */
export const PostV1ToolsIntelxInternalServerError$inboundSchema: z.ZodMiniType<
  PostV1ToolsIntelxInternalServerError,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    data: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new PostV1ToolsIntelxInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const PostV1ToolsIntelxBadRequestError$inboundSchema: z.ZodMiniType<
  PostV1ToolsIntelxBadRequestError,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    data: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new PostV1ToolsIntelxBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
