/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { IndiciaError } from "./indicia-error.js";

/**
 * Internal Server Error
 */
export type SearchWebDatabasesInternalServerErrorData = {
  success: boolean;
  error?: string | undefined;
};

/**
 * Internal Server Error
 */
export class SearchWebDatabasesInternalServerError extends IndiciaError {
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: SearchWebDatabasesInternalServerErrorData;

  constructor(
    err: SearchWebDatabasesInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "SearchWebDatabasesInternalServerError";
  }
}

/**
 * Payment Required
 */
export type SearchWebDatabasesPaymentRequiredErrorData = {
  success: boolean;
  error?: string | undefined;
};

/**
 * Payment Required
 */
export class SearchWebDatabasesPaymentRequiredError extends IndiciaError {
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: SearchWebDatabasesPaymentRequiredErrorData;

  constructor(
    err: SearchWebDatabasesPaymentRequiredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "SearchWebDatabasesPaymentRequiredError";
  }
}

/** @internal */
export const SearchWebDatabasesInternalServerError$inboundSchema: z.ZodMiniType<
  SearchWebDatabasesInternalServerError,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    error: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new SearchWebDatabasesInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const SearchWebDatabasesPaymentRequiredError$inboundSchema:
  z.ZodMiniType<SearchWebDatabasesPaymentRequiredError, unknown> = z.pipe(
    z.object({
      success: types.boolean(),
      error: types.optional(types.string()),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new SearchWebDatabasesPaymentRequiredError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
