/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { IndiciaError } from "./indicia-error.js";

/**
 * Internal Server Error
 */
export type SearchFaceInternalServerErrorData = {
  success: boolean;
  error?: string | undefined;
};

/**
 * Internal Server Error
 */
export class SearchFaceInternalServerError extends IndiciaError {
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: SearchFaceInternalServerErrorData;

  constructor(
    err: SearchFaceInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "SearchFaceInternalServerError";
  }
}

/**
 * Payment Required - Insufficient Credits
 */
export type SearchFacePaymentRequiredErrorData = {
  success: boolean;
  error?: string | undefined;
};

/**
 * Payment Required - Insufficient Credits
 */
export class SearchFacePaymentRequiredError extends IndiciaError {
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: SearchFacePaymentRequiredErrorData;

  constructor(
    err: SearchFacePaymentRequiredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "SearchFacePaymentRequiredError";
  }
}

/**
 * Bad Request
 */
export type SearchFaceBadRequestErrorData = {
  success: boolean;
  error?: string | undefined;
};

/**
 * Bad Request
 */
export class SearchFaceBadRequestError extends IndiciaError {
  success: boolean;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: SearchFaceBadRequestErrorData;

  constructor(
    err: SearchFaceBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    if (err.error != null) this.error = err.error;

    this.name = "SearchFaceBadRequestError";
  }
}

/** @internal */
export const SearchFaceInternalServerError$inboundSchema: z.ZodMiniType<
  SearchFaceInternalServerError,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    error: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new SearchFaceInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const SearchFacePaymentRequiredError$inboundSchema: z.ZodMiniType<
  SearchFacePaymentRequiredError,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    error: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new SearchFacePaymentRequiredError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const SearchFaceBadRequestError$inboundSchema: z.ZodMiniType<
  SearchFaceBadRequestError,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    error: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new SearchFaceBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
