/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { infrastructureScanPorts } from "../funcs/infrastructure-scan-ports.js";
import { infrastructureSearchCertificates } from "../funcs/infrastructure-search-certificates.js";
import { infrastructureSearchDns } from "../funcs/infrastructure-search-dns.js";
import { infrastructureSearchIpInfo } from "../funcs/infrastructure-search-ip-info.js";
import { infrastructureSearchShodan } from "../funcs/infrastructure-search-shodan.js";
import { infrastructureSearchWhois } from "../funcs/infrastructure-search-whois.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Infrastructure extends ClientSDK {
  /**
   * IP Info
   *
   * @remarks
   * Analyze details of an IP Address.
   */
  async searchIpInfo(
    request: operations.SearchIpInfoRequest,
    options?: RequestOptions,
  ): Promise<operations.SearchIpInfoResponse> {
    return unwrapAsync(infrastructureSearchIpInfo(
      this,
      request,
      options,
    ));
  }

  /**
   * DNS Reconnaissance
   *
   * @remarks
   * Perform deep DNS analysis and find hidden subdomains
   */
  async searchDns(
    request: operations.SearchDnsRequest,
    options?: RequestOptions,
  ): Promise<operations.SearchDnsResponse> {
    return unwrapAsync(infrastructureSearchDns(
      this,
      request,
      options,
    ));
  }

  /**
   * Shodan Search
   *
   * @remarks
   * IP service and software intelligence
   */
  async searchShodan(
    request: operations.SearchShodanRequest,
    options?: RequestOptions,
  ): Promise<operations.SearchShodanResponse> {
    return unwrapAsync(infrastructureSearchShodan(
      this,
      request,
      options,
    ));
  }

  /**
   * Whois
   *
   * @remarks
   * Return information on a domain and its registration
   */
  async searchWhois(
    request: operations.SearchWhoisRequest,
    options?: RequestOptions,
  ): Promise<operations.SearchWhoisResponse> {
    return unwrapAsync(infrastructureSearchWhois(
      this,
      request,
      options,
    ));
  }

  /**
   * Port Scan
   *
   * @remarks
   * Perform a port scan on a given IP address or domain.
   */
  async scanPorts(
    request: operations.ScanPortsRequest,
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(infrastructureScanPorts(
      this,
      request,
      options,
    ));
  }

  /**
   * Certificate Lookup
   *
   * @remarks
   * Lookup details about a TLS certificate by domain.
   */
  async searchCertificates(
    request: operations.SearchCertificatesRequest,
    options?: RequestOptions,
  ): Promise<operations.SearchCertificatesResponse> {
    return unwrapAsync(infrastructureSearchCertificates(
      this,
      request,
      options,
    ));
  }
}
