/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Activity } from "./activity.js";
import { Infrastructure } from "./infrastructure.js";
import { Intelligence } from "./intelligence.js";
import { Organizations } from "./organizations.js";
import { Pricing } from "./pricing.js";
import { Socials } from "./socials.js";
import { Tools } from "./tools.js";
import { Users } from "./users.js";

export class Indicia extends ClientSDK {
  private _users?: Users;
  get users(): Users {
    return (this._users ??= new Users(this._options));
  }

  private _pricing?: Pricing;
  get pricing(): Pricing {
    return (this._pricing ??= new Pricing(this._options));
  }

  private _activity?: Activity;
  get activity(): Activity {
    return (this._activity ??= new Activity(this._options));
  }

  private _intelligence?: Intelligence;
  get intelligence(): Intelligence {
    return (this._intelligence ??= new Intelligence(this._options));
  }

  private _socials?: Socials;
  get socials(): Socials {
    return (this._socials ??= new Socials(this._options));
  }

  private _infrastructure?: Infrastructure;
  get infrastructure(): Infrastructure {
    return (this._infrastructure ??= new Infrastructure(this._options));
  }

  private _tools?: Tools;
  get tools(): Tools {
    return (this._tools ??= new Tools(this._options));
  }

  private _organizations?: Organizations;
  get organizations(): Organizations {
    return (this._organizations ??= new Organizations(this._options));
  }
}
