/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deleteV1ActivityById } from "../funcs/delete-v1-activity-by-id.js";
import { getV1ActivityById } from "../funcs/get-v1-activity-by-id.js";
import { getV1Activity } from "../funcs/get-v1-activity.js";
import { getV1Info } from "../funcs/get-v1-info.js";
import { getV1OrganizationsByIdAuditLog } from "../funcs/get-v1-organizations-by-id-audit-log.js";
import { getV1OrganizationsByIdCases } from "../funcs/get-v1-organizations-by-id-cases.js";
import { getV1OrganizationsByIdMembers } from "../funcs/get-v1-organizations-by-id-members.js";
import { getV1OrganizationsById } from "../funcs/get-v1-organizations-by-id.js";
import { getV1Organizations } from "../funcs/get-v1-organizations.js";
import { getV1Pricing } from "../funcs/get-v1-pricing.js";
import { postV1OrganizationsByIdCredits } from "../funcs/post-v1-organizations-by-id-credits.js";
import { postV1SearchInfrastructureCertificates } from "../funcs/post-v1-search-infrastructure-certificates.js";
import { postV1SearchInfrastructureDns } from "../funcs/post-v1-search-infrastructure-dns.js";
import { postV1SearchInfrastructureIpinfo } from "../funcs/post-v1-search-infrastructure-ipinfo.js";
import { postV1SearchInfrastructurePortscan } from "../funcs/post-v1-search-infrastructure-portscan.js";
import { postV1SearchInfrastructureShodan } from "../funcs/post-v1-search-infrastructure-shodan.js";
import { postV1SearchInfrastructureWhois } from "../funcs/post-v1-search-infrastructure-whois.js";
import { postV1SearchIntelligenceAddress } from "../funcs/post-v1-search-intelligence-address.js";
import { postV1SearchIntelligenceEmail } from "../funcs/post-v1-search-intelligence-email.js";
import { postV1SearchIntelligenceFacial } from "../funcs/post-v1-search-intelligence-facial.js";
import { postV1SearchIntelligenceGeolocation } from "../funcs/post-v1-search-intelligence-geolocation.js";
import { postV1SearchIntelligenceGmail } from "../funcs/post-v1-search-intelligence-gmail.js";
import { postV1SearchIntelligenceHudsonrock } from "../funcs/post-v1-search-intelligence-hudsonrock.js";
import { postV1SearchIntelligencePerson } from "../funcs/post-v1-search-intelligence-person.js";
import { postV1SearchIntelligencePhone } from "../funcs/post-v1-search-intelligence-phone.js";
import { postV1SearchIntelligenceSeon } from "../funcs/post-v1-search-intelligence-seon.js";
import { postV1SearchIntelligenceWebDbs } from "../funcs/post-v1-search-intelligence-web-dbs.js";
import { postV1SearchSocialsDiscord } from "../funcs/post-v1-search-socials-discord.js";
import { postV1SearchSocialsGithub } from "../funcs/post-v1-search-socials-github.js";
import { postV1SearchSocialsRoblox } from "../funcs/post-v1-search-socials-roblox.js";
import { postV1SearchSocialsTiktok } from "../funcs/post-v1-search-socials-tiktok.js";
import { postV1ToolsDoogle } from "../funcs/post-v1-tools-doogle.js";
import { postV1ToolsDoublecounter } from "../funcs/post-v1-tools-doublecounter.js";
import { postV1ToolsIntelx } from "../funcs/post-v1-tools-intelx.js";
import { postV2SearchSocialsUsername } from "../funcs/post-v2-search-socials-username.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Indicia extends ClientSDK {
  /**
   * Get information about the user, also healthcheck endpoint.
   */
  async getV1Info(
    options?: RequestOptions,
  ): Promise<operations.GetV1InfoResponse> {
    return unwrapAsync(getV1Info(
      this,
      options,
    ));
  }

  /**
   * Gives credit pricing for all Indicia services
   */
  async getV1Pricing(
    options?: RequestOptions,
  ): Promise<operations.GetV1PricingResponse> {
    return unwrapAsync(getV1Pricing(
      this,
      options,
    ));
  }

  /**
   * Get a list of recent activities.
   */
  async getV1Activity(
    request?: operations.GetV1ActivityRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1ActivityResponse> {
    return unwrapAsync(getV1Activity(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a specific activity by its ID.
   */
  async getV1ActivityById(
    request: operations.GetV1ActivityByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1ActivityByIdResponse> {
    return unwrapAsync(getV1ActivityById(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a specific activity by its ID.
   */
  async deleteV1ActivityById(
    request: operations.DeleteV1ActivityByIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(deleteV1ActivityById(
      this,
      request,
      options,
    ));
  }

  /**
   * Address Search (US Only)
   */
  async postV1SearchIntelligenceAddress(
    request: operations.PostV1SearchIntelligenceAddressRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchIntelligenceAddressResponse> {
    return unwrapAsync(postV1SearchIntelligenceAddress(
      this,
      request,
      options,
    ));
  }

  /**
   * Email Search (US Only)
   *
   * @remarks
   * Search for individuals by email address.
   */
  async postV1SearchIntelligenceEmail(
    request: operations.PostV1SearchIntelligenceEmailRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchIntelligenceEmailResponse> {
    return unwrapAsync(postV1SearchIntelligenceEmail(
      this,
      request,
      options,
    ));
  }

  /**
   * Geolocate Media
   *
   * @remarks
   * Geolocate an image or video using AI-powered analysis. Streams progress updates via Server-Sent Events.
   *
   *       Response type:
   *       ```ts
   *       interface GeolocationResponse {
   *         location: string | null;
   *         coordinates: string | null;
   *         certainty: string;
   *         reasoning: string;
   *         mapsUrl?: `https://www.google.com/maps/search/?api=1&query=${string}`;
   *       }
   *     ```
   */
  async postV1SearchIntelligenceGeolocation(
    request: operations.PostV1SearchIntelligenceGeolocationRequest,
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(postV1SearchIntelligenceGeolocation(
      this,
      request,
      options,
    ));
  }

  /**
   * Gmail Search
   *
   * @remarks
   * Fetches Gmail account information based on the provided email address using the Ghunt library.
   */
  async postV1SearchIntelligenceGmail(
    request: operations.PostV1SearchIntelligenceGmailRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchIntelligenceGmailResponse> {
    return unwrapAsync(postV1SearchIntelligenceGmail(
      this,
      request,
      options,
    ));
  }

  /**
   * Person Search (US Only)
   *
   * @remarks
   * Search for individuals by name and state.
   */
  async postV1SearchIntelligencePerson(
    request: operations.PostV1SearchIntelligencePersonRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchIntelligencePersonResponse> {
    return unwrapAsync(postV1SearchIntelligencePerson(
      this,
      request,
      options,
    ));
  }

  /**
   * Phone Search (Individual data US only)
   *
   * @remarks
   * Search for individuals by phone number.
   */
  async postV1SearchIntelligencePhone(
    request: operations.PostV1SearchIntelligencePhoneRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchIntelligencePhoneResponse> {
    return unwrapAsync(postV1SearchIntelligencePhone(
      this,
      request,
      options,
    ));
  }

  /**
   * SEON Lookup
   *
   * @remarks
   * Evaluate potential threats with SEON’s counter fraud intelligence systems.
   */
  async postV1SearchIntelligenceSeon(
    request: operations.PostV1SearchIntelligenceSeonRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchIntelligenceSeonResponse> {
    return unwrapAsync(postV1SearchIntelligenceSeon(
      this,
      request,
      options,
    ));
  }

  /**
   * Web Databases
   *
   * @remarks
   * Deep web intelligence gathering and comprehensive data breach analysis
   */
  async postV1SearchIntelligenceWebDbs(
    request: operations.PostV1SearchIntelligenceWebDbsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchIntelligenceWebDbsResponse> {
    return unwrapAsync(postV1SearchIntelligenceWebDbs(
      this,
      request,
      options,
    ));
  }

  /**
   * Reverse Face Search
   *
   * @remarks
   * Search for faces across the internet using facial recognition. Streams progress updates via Server-Sent Events.
   *
   *       Response type:
   *       ```ts
   *       interface FacialSearchResult {
   *         time: number;
   *         results: {
   *           id: string;
   *           hash: string;
   *           group: number;
   *           quality: number;
   *           imageUrl: string;
   *           crawledAt: number;
   *           sourceUrl: string;
   *           thumbnailUrl: string;
   *         }[];
   *         searchHash: string;
   *         numberOfResults: number;
   *       }
   *     ```
   */
  async postV1SearchIntelligenceFacial(
    request: operations.PostV1SearchIntelligenceFacialRequest,
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(postV1SearchIntelligenceFacial(
      this,
      request,
      options,
    ));
  }

  /**
   * Hudson Rock Search
   *
   * @remarks
   * Search for compromised data on Hudson Rock
   */
  async postV1SearchIntelligenceHudsonrock(
    request: operations.PostV1SearchIntelligenceHudsonrockRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchIntelligenceHudsonrockResponse> {
    return unwrapAsync(postV1SearchIntelligenceHudsonrock(
      this,
      request,
      options,
    ));
  }

  /**
   * Discord Search
   *
   * @remarks
   * Search Discord users for profile and server info
   */
  async postV1SearchSocialsDiscord(
    request: operations.PostV1SearchSocialsDiscordRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchSocialsDiscordResponse> {
    return unwrapAsync(postV1SearchSocialsDiscord(
      this,
      request,
      options,
    ));
  }

  /**
   * GitHub Search
   *
   * @remarks
   * Search GitHub profiles, info, and commit emails
   */
  async postV1SearchSocialsGithub(
    request: operations.PostV1SearchSocialsGithubRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchSocialsGithubResponse> {
    return unwrapAsync(postV1SearchSocialsGithub(
      this,
      request,
      options,
    ));
  }

  /**
   * Roblox Search
   *
   * @remarks
   * Lookup Roblox users, game statistics, and profile information
   */
  async postV1SearchSocialsRoblox(
    request: operations.PostV1SearchSocialsRobloxRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchSocialsRobloxResponse> {
    return unwrapAsync(postV1SearchSocialsRoblox(
      this,
      request,
      options,
    ));
  }

  /**
   * TikTok Search
   *
   * @remarks
   * Aggregate intelligence and data of a TikTok account
   */
  async postV1SearchSocialsTiktok(
    request: operations.PostV1SearchSocialsTiktokRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchSocialsTiktokResponse> {
    return unwrapAsync(postV1SearchSocialsTiktok(
      this,
      request,
      options,
    ));
  }

  /**
   * IP Info
   *
   * @remarks
   * Analyze details of an IP Address.
   */
  async postV1SearchInfrastructureIpinfo(
    request: operations.PostV1SearchInfrastructureIpinfoRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchInfrastructureIpinfoResponse> {
    return unwrapAsync(postV1SearchInfrastructureIpinfo(
      this,
      request,
      options,
    ));
  }

  /**
   * DNS Reconnaissance
   *
   * @remarks
   * Perform deep DNS analysis and find hidden subdomains
   */
  async postV1SearchInfrastructureDns(
    request: operations.PostV1SearchInfrastructureDnsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchInfrastructureDnsResponse> {
    return unwrapAsync(postV1SearchInfrastructureDns(
      this,
      request,
      options,
    ));
  }

  /**
   * Shodan Search
   *
   * @remarks
   * IP service and software intelligence
   */
  async postV1SearchInfrastructureShodan(
    request: operations.PostV1SearchInfrastructureShodanRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchInfrastructureShodanResponse> {
    return unwrapAsync(postV1SearchInfrastructureShodan(
      this,
      request,
      options,
    ));
  }

  /**
   * Whois
   *
   * @remarks
   * Return information on a domain and its registration
   */
  async postV1SearchInfrastructureWhois(
    request: operations.PostV1SearchInfrastructureWhoisRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchInfrastructureWhoisResponse> {
    return unwrapAsync(postV1SearchInfrastructureWhois(
      this,
      request,
      options,
    ));
  }

  /**
   * Port Scan
   *
   * @remarks
   * Perform a port scan on a given IP address or domain.
   *
   *   Response type:
   *   ```ts
   *   interface NmapScanResult {
   *     $: {
   *       scanner: string;
   *       args: string;
   *       start: string;
   *       startstr: string;
   *       version: string;
   *       xmloutputversion: string;
   *     };
   *     scaninfo: Array<{
   *       $: {
   *         type: string;
   *         protocol: string;
   *         numservices: string;
   *         services: string;
   *       };
   *     }>;
   *     verbose: Array<{ $: { level: string } }>;
   *     debugging: Array<{ $: { level: string } }>;
   *     taskprogress?: Array<{
   *       $: {
   *         task: string;
   *         time: string;
   *         percent: string;
   *         remaining: string;
   *         etc: string;
   *       };
   *     }>;
   *     host?: Array<{
   *       $: {
   *         starttime: string;
   *         endtime: string;
   *       };
   *       status: Array<{
   *         $: {
   *           state: string;
   *           reason: string;
   *           reason_ttl: string;
   *         };
   *       }>;
   *       address: Array<{
   *         $: {
   *           addr: string;
   *           addrtype: string;
   *         };
   *       }>;
   *       hostnames?: Array<{
   *         hostname: Array<{
   *           $: {
   *             name: string;
   *             type: string;
   *           };
   *         }>;
   *       }>;
   *       ports?: Array<{
   *         extraports?: Array<{
   *           $: {
   *             state: string;
   *             count: string;
   *           };
   *           extrareasons: Array<{
   *             $: {
   *               reason: string;
   *               count: string;
   *               proto: string;
   *               ports: string;
   *             };
   *           }>;
   *         }>;
   *         port?: Array<{
   *           $: {
   *             protocol: string;
   *             portid: string;
   *           };
   *           state: Array<{
   *             $: {
   *               state: string;
   *               reason: string;
   *               reason_ttl: string;
   *             };
   *           }>;
   *           service?: Array<{
   *             $: {
   *               name: string;
   *               product?: string;
   *               version?: string;
   *               extrainfo?: string;
   *               ostype?: string;
   *               method: string;
   *               conf: string;
   *             };
   *             cpe?: string[];
   *           }>;
   *         }>;
   *       }>;
   *       times?: Array<{
   *         $: {
   *           srtt: string;
   *           rttvar: string;
   *           to: string;
   *         };
   *       }>;
   *     }>;
   *     runstats: Array<{
   *       finished: Array<{
   *         $: {
   *           time: string;
   *           timestr: string;
   *           summary: string;
   *           elapsed: string;
   *           exit: string;
   *         };
   *       }>;
   *       hosts: Array<{
   *         $: {
   *           up: string;
   *           down: string;
   *           total: string;
   *         };
   *       }>;
   *     }>;
   *   }
   * ```
   */
  async postV1SearchInfrastructurePortscan(
    request: operations.PostV1SearchInfrastructurePortscanRequest,
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(postV1SearchInfrastructurePortscan(
      this,
      request,
      options,
    ));
  }

  /**
   * Certificate Lookup
   *
   * @remarks
   * Lookup details about a TLS certificate by domain.
   */
  async postV1SearchInfrastructureCertificates(
    request: operations.PostV1SearchInfrastructureCertificatesRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1SearchInfrastructureCertificatesResponse> {
    return unwrapAsync(postV1SearchInfrastructureCertificates(
      this,
      request,
      options,
    ));
  }

  /**
   * Discord Alt Lookup
   *
   * @remarks
   * Correlate and identify alternative Discord accounts of a user.
   */
  async postV1ToolsDoogle(
    request: operations.PostV1ToolsDoogleRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ToolsDoogleResponse> {
    return unwrapAsync(postV1ToolsDoogle(
      this,
      request,
      options,
    ));
  }

  /**
   * Bypass Double Counter URL
   *
   * @remarks
   * Bypass alt detection for Discord servers.
   */
  async postV1ToolsDoublecounter(
    request: operations.PostV1ToolsDoublecounterRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ToolsDoublecounterResponse> {
    return unwrapAsync(postV1ToolsDoublecounter(
      this,
      request,
      options,
    ));
  }

  /**
   * Download IntelX file
   *
   * @remarks
   * Download a file from IntelX storage. Use storageId + bucket for a standalone file (5 credits), or systemId with bucket "leaks.logs" for a stealer log (10 credits).
   */
  async postV1ToolsIntelx(
    request: operations.PostV1ToolsIntelxRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ToolsIntelxResponse> {
    return unwrapAsync(postV1ToolsIntelx(
      this,
      request,
      options,
    ));
  }

  /**
   * List organizations the authenticated user belongs to.
   */
  async getV1Organizations(
    options?: RequestOptions,
  ): Promise<operations.GetV1OrganizationsResponse> {
    return unwrapAsync(getV1Organizations(
      this,
      options,
    ));
  }

  /**
   * Get details for a specific organization you are a member of.
   */
  async getV1OrganizationsById(
    request: operations.GetV1OrganizationsByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1OrganizationsByIdResponse> {
    return unwrapAsync(getV1OrganizationsById(
      this,
      request,
      options,
    ));
  }

  /**
   * List members of an organization you belong to.
   */
  async getV1OrganizationsByIdMembers(
    request: operations.GetV1OrganizationsByIdMembersRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1OrganizationsByIdMembersResponse> {
    return unwrapAsync(getV1OrganizationsByIdMembers(
      this,
      request,
      options,
    ));
  }

  /**
   * Get the audit log for an organization. Requires owner or admin role.
   */
  async getV1OrganizationsByIdAuditLog(
    request: operations.GetV1OrganizationsByIdAuditLogRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1OrganizationsByIdAuditLogResponse> {
    return unwrapAsync(getV1OrganizationsByIdAuditLog(
      this,
      request,
      options,
    ));
  }

  /**
   * List cases shared with an organization (filtered by your visibility settings).
   */
  async getV1OrganizationsByIdCases(
    request: operations.GetV1OrganizationsByIdCasesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1OrganizationsByIdCasesResponse> {
    return unwrapAsync(getV1OrganizationsByIdCases(
      this,
      request,
      options,
    ));
  }

  /**
   * Send credits from your balance to one or more organization members. Requires owner or admin role.
   */
  async postV1OrganizationsByIdCredits(
    request: operations.PostV1OrganizationsByIdCreditsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1OrganizationsByIdCreditsResponse> {
    return unwrapAsync(postV1OrganizationsByIdCredits(
      this,
      request,
      options,
    ));
  }

  /**
   * Username Search V2
   *
   * @remarks
   * Search various sites for a specific username
   */
  async postV2SearchSocialsUsername(
    request: operations.PostV2SearchSocialsUsernameRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV2SearchSocialsUsernameResponse> {
    return unwrapAsync(postV2SearchSocialsUsername(
      this,
      request,
      options,
    ));
  }
}
