/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { toolsBypassDoubleCounter } from "../funcs/tools-bypass-double-counter.js";
import { toolsDownloadIntelxFile } from "../funcs/tools-download-intelx-file.js";
import { toolsDownloadVirusTotalFile } from "../funcs/tools-download-virus-total-file.js";
import { toolsLookupDiscordAlt } from "../funcs/tools-lookup-discord-alt.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tools extends ClientSDK {
  /**
   * Discord Alt Lookup
   *
   * @remarks
   * Correlate and identify alternative Discord accounts of a user.
   */
  async lookupDiscordAlt(
    request: operations.LookupDiscordAltRequest,
    options?: RequestOptions,
  ): Promise<operations.LookupDiscordAltResponse> {
    return unwrapAsync(toolsLookupDiscordAlt(
      this,
      request,
      options,
    ));
  }

  /**
   * Bypass Double Counter URL
   *
   * @remarks
   * Bypass alt detection for Discord servers.
   */
  async bypassDoubleCounter(
    request: operations.BypassDoubleCounterRequest,
    options?: RequestOptions,
  ): Promise<operations.BypassDoubleCounterResponse> {
    return unwrapAsync(toolsBypassDoubleCounter(
      this,
      request,
      options,
    ));
  }

  /**
   * Download IntelX file
   *
   * @remarks
   * Download a file from IntelX storage. Use storageId + bucket for a standalone file (5 credits), or systemId with bucket "leaks.logs" for a stealer log (10 credits).
   */
  async downloadIntelxFile(
    request: operations.DownloadIntelxFileRequest,
    options?: RequestOptions,
  ): Promise<operations.DownloadIntelxFileResponse> {
    return unwrapAsync(toolsDownloadIntelxFile(
      this,
      request,
      options,
    ));
  }

  /**
   * Download VirusTotal file
   *
   * @remarks
   * Download a file from VirusTotal by its id. The file is returned base64-encoded.
   */
  async downloadVirusTotalFile(
    request: operations.DownloadVirusTotalFileRequest,
    options?: RequestOptions,
  ): Promise<operations.DownloadVirusTotalFileResponse> {
    return unwrapAsync(toolsDownloadVirusTotalFile(
      this,
      request,
      options,
    ));
  }
}
