/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { toolsAnalyzeCryptoAddress } from "../funcs/tools-analyze-crypto-address.js";
import { toolsBypassDoubleCounter } from "../funcs/tools-bypass-double-counter.js";
import { toolsDownloadIntelxFile } from "../funcs/tools-download-intelx-file.js";
import { toolsDownloadVirusTotalFile } from "../funcs/tools-download-virus-total-file.js";
import { toolsLookupDiscordAlt } from "../funcs/tools-lookup-discord-alt.js";
import { toolsSearchAppStore } from "../funcs/tools-search-app-store.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tools extends ClientSDK {
  /**
   * App Store Search
   *
   * @remarks
   * Scrape app and developer information from the Google Play Store or Apple App Store. Pass an app/package ID (e.g. com.whatsapp) for full developer contact details, or a name to search.
   */
  async searchAppStore(
    request: operations.SearchAppStoreRequest,
    options?: RequestOptions,
  ): Promise<operations.SearchAppStoreResponse> {
    return unwrapAsync(toolsSearchAppStore(
      this,
      request,
      options,
    ));
  }

  /**
   * Crypto Address Analyzer
   *
   * @remarks
   * Analyze a cryptocurrency address: native balance and USD value, token holdings, and recent transaction history with counterparties. Supports Bitcoin, Litecoin, Ethereum, Base, Optimism, Arbitrum, Polygon, Gnosis, Celo, Mode, Fuse, Tron, TON and Solana. The network is auto-detected from the address format if not supplied (pass a specific id to disambiguate base58 chains).
   */
  async analyzeCryptoAddress(
    request: operations.AnalyzeCryptoAddressRequest,
    options?: RequestOptions,
  ): Promise<operations.AnalyzeCryptoAddressResponse> {
    return unwrapAsync(toolsAnalyzeCryptoAddress(
      this,
      request,
      options,
    ));
  }

  /**
   * Discord Alt Lookup
   *
   * @remarks
   * Correlate and identify alternative Discord accounts of a user.
   */
  async lookupDiscordAlt(
    request: operations.LookupDiscordAltRequest,
    options?: RequestOptions,
  ): Promise<operations.LookupDiscordAltResponse> {
    return unwrapAsync(toolsLookupDiscordAlt(
      this,
      request,
      options,
    ));
  }

  /**
   * Bypass Double Counter URL
   *
   * @remarks
   * Bypass alt detection for Discord servers.
   */
  async bypassDoubleCounter(
    request: operations.BypassDoubleCounterRequest,
    options?: RequestOptions,
  ): Promise<operations.BypassDoubleCounterResponse> {
    return unwrapAsync(toolsBypassDoubleCounter(
      this,
      request,
      options,
    ));
  }

  /**
   * Download IntelX file
   *
   * @remarks
   * Download a file from IntelX storage. Use storageId + bucket for a standalone file (5 credits), or systemId with bucket "leaks.logs" for a stealer log (10 credits).
   */
  async downloadIntelxFile(
    request: operations.DownloadIntelxFileRequest,
    options?: RequestOptions,
  ): Promise<operations.DownloadIntelxFileResponse> {
    return unwrapAsync(toolsDownloadIntelxFile(
      this,
      request,
      options,
    ));
  }

  /**
   * Download VirusTotal file
   *
   * @remarks
   * Download a file from VirusTotal by its id. The file is returned base64-encoded.
   */
  async downloadVirusTotalFile(
    request: operations.DownloadVirusTotalFileRequest,
    options?: RequestOptions,
  ): Promise<operations.DownloadVirusTotalFileResponse> {
    return unwrapAsync(toolsDownloadVirusTotalFile(
      this,
      request,
      options,
    ));
  }
}
