/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersGetInfo } from "../funcs/users-get-info.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Users extends ClientSDK {
  /**
   * Get information about the user, also healthcheck endpoint.
   */
  async getInfo(
    options?: RequestOptions,
  ): Promise<operations.GetInfoResponse> {
    return unwrapAsync(usersGetInfo(
      this,
      options,
    ));
  }
}
