/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @indiciaosint/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx getV1Info.example.ts
 */

import { Indicia } from "@indiciaosint/sdk";

const indicia = new Indicia({
  apiKeyAuth: process.env["INDICIA_API_KEY_AUTH"] ?? "",
});

async function main() {
  const result = await indicia.getV1Info();

  console.log(result);
}

main().catch(console.error);
