/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteActivityRequest = {
  /**
   * a UUID
   */
  id: string;
};

/** @internal */
export type DeleteActivityRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteActivityRequest$outboundSchema: z.ZodMiniType<
  DeleteActivityRequest$Outbound,
  DeleteActivityRequest
> = z.object({
  id: z.string(),
});

export function deleteActivityRequestToJSON(
  deleteActivityRequest: DeleteActivityRequest,
): string {
  return JSON.stringify(
    DeleteActivityRequest$outboundSchema.parse(deleteActivityRequest),
  );
}
