/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DownloadVirusTotalFileRequest = {
  id: string;
};

export type DownloadVirusTotalFileData = {
  content: string;
  encoding: string;
  id: string;
  size: number;
};

/**
 * Successful response
 */
export type DownloadVirusTotalFileResponse = {
  success: boolean;
  data?: DownloadVirusTotalFileData | undefined;
  error?: string | undefined;
};

/** @internal */
export type DownloadVirusTotalFileRequest$Outbound = {
  id: string;
};

/** @internal */
export const DownloadVirusTotalFileRequest$outboundSchema: z.ZodMiniType<
  DownloadVirusTotalFileRequest$Outbound,
  DownloadVirusTotalFileRequest
> = z.object({
  id: z.string(),
});

export function downloadVirusTotalFileRequestToJSON(
  downloadVirusTotalFileRequest: DownloadVirusTotalFileRequest,
): string {
  return JSON.stringify(
    DownloadVirusTotalFileRequest$outboundSchema.parse(
      downloadVirusTotalFileRequest,
    ),
  );
}

/** @internal */
export const DownloadVirusTotalFileData$inboundSchema: z.ZodMiniType<
  DownloadVirusTotalFileData,
  unknown
> = z.object({
  content: types.string(),
  encoding: types.string(),
  id: types.string(),
  size: types.number(),
});

export function downloadVirusTotalFileDataFromJSON(
  jsonString: string,
): SafeParseResult<DownloadVirusTotalFileData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DownloadVirusTotalFileData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DownloadVirusTotalFileData' from JSON`,
  );
}

/** @internal */
export const DownloadVirusTotalFileResponse$inboundSchema: z.ZodMiniType<
  DownloadVirusTotalFileResponse,
  unknown
> = z.object({
  success: types.boolean(),
  data: types.optional(z.lazy(() => DownloadVirusTotalFileData$inboundSchema)),
  error: types.optional(types.string()),
});

export function downloadVirusTotalFileResponseFromJSON(
  jsonString: string,
): SafeParseResult<DownloadVirusTotalFileResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DownloadVirusTotalFileResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DownloadVirusTotalFileResponse' from JSON`,
  );
}
