/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const Model = {
  Default: "default",
  Enhanced: "enhanced",
} as const;
export type Model = ClosedEnum<typeof Model>;

export type GeolocateMediaRequest = {
  media: any;
  locationHint?: string | undefined;
  model?: Model | undefined;
};

/** @internal */
export const Model$outboundSchema: z.ZodMiniEnum<typeof Model> = z.enum(Model);

/** @internal */
export type GeolocateMediaRequest$Outbound = {
  media: any;
  locationHint?: string | undefined;
  model?: string | undefined;
};

/** @internal */
export const GeolocateMediaRequest$outboundSchema: z.ZodMiniType<
  GeolocateMediaRequest$Outbound,
  GeolocateMediaRequest
> = z.object({
  media: z.any(),
  locationHint: z.optional(z.string()),
  model: z.optional(Model$outboundSchema),
});

export function geolocateMediaRequestToJSON(
  geolocateMediaRequest: GeolocateMediaRequest,
): string {
  return JSON.stringify(
    GeolocateMediaRequest$outboundSchema.parse(geolocateMediaRequest),
  );
}
