/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetActivityRequest = {
  /**
   * a UUID
   */
  id: string;
};

export type GetActivityResult = {};

export type GetActivityResultUnion =
  | number
  | GetActivityResult
  | string
  | boolean;

export const GetActivityType = {
  Address: "address",
  Appstore: "appstore",
  Breachvip: "breachvip",
  Certificates: "certificates",
  Cloudsint: "cloudsint",
  Courtrecords: "courtrecords",
  Discord: "discord",
  Dnsdumpster: "dnsdumpster",
  Doogle: "doogle",
  Doublecounter: "doublecounter",
  Email: "email",
  Fr: "fr",
  Geolocation: "geolocation",
  GhosintSearch: "ghosint.search",
  Github: "github",
  Gmail: "gmail",
  Hudsonrock: "hudsonrock",
  IntelligencexIdentityportal: "intelligencex.identityportal",
  Intelx: "intelx",
  IntelxStealerlogs: "intelx.stealerlogs",
  Ipinfo: "ipinfo",
  Leakcheck: "leakcheck",
  Leakosint: "leakosint",
  Linkedin: "linkedin",
  Melissa: "melissa",
  Minecraft: "minecraft",
  Osintindustries: "osintindustries",
  Other: "other",
  Person: "person",
  Phone: "phone",
  Phonebook: "phonebook",
  Pimeyes: "pimeyes",
  Portscan: "portscan",
  Roblox: "roblox",
  Scraper: "scraper",
  Seon: "seon",
  Shodan: "shodan",
  Snusbase: "snusbase",
  Tiktok: "tiktok",
  Uk: "uk",
  Username: "username",
  Usernames: "usernames",
  Vehicle: "vehicle",
  VirustotalContent: "virustotal.content",
  VirustotalDownload: "virustotal.download",
  VirustotalIntelligence: "virustotal.intelligence",
  WebDbs: "web-dbs",
  Whois: "whois",
} as const;
export type GetActivityType = OpenEnum<typeof GetActivityType>;

export type GetActivityActivity = {
  agent: boolean | null;
  apiKey: string | null;
  case: string | null;
  detail: string;
  /**
   * a RFC-4122-compliant UUID
   */
  id: string;
  query: string;
  result: number | GetActivityResult | string | boolean | null;
  /**
   * an integer representing a safe Unix timestamp
   */
  time: number;
  type: GetActivityType;
  user: string | null;
};

/**
 * Successful response with the activity details.
 */
export type GetActivityResponse = {
  activity: GetActivityActivity;
  success: boolean;
};

/** @internal */
export type GetActivityRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetActivityRequest$outboundSchema: z.ZodMiniType<
  GetActivityRequest$Outbound,
  GetActivityRequest
> = z.object({
  id: z.string(),
});

export function getActivityRequestToJSON(
  getActivityRequest: GetActivityRequest,
): string {
  return JSON.stringify(
    GetActivityRequest$outboundSchema.parse(getActivityRequest),
  );
}

/** @internal */
export const GetActivityResult$inboundSchema: z.ZodMiniType<
  GetActivityResult,
  unknown
> = z.object({});

export function getActivityResultFromJSON(
  jsonString: string,
): SafeParseResult<GetActivityResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetActivityResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetActivityResult' from JSON`,
  );
}

/** @internal */
export const GetActivityResultUnion$inboundSchema: z.ZodMiniType<
  GetActivityResultUnion,
  unknown
> = smartUnion([
  types.number(),
  z.lazy(() => GetActivityResult$inboundSchema),
  types.string(),
  types.boolean(),
]);

export function getActivityResultUnionFromJSON(
  jsonString: string,
): SafeParseResult<GetActivityResultUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetActivityResultUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetActivityResultUnion' from JSON`,
  );
}

/** @internal */
export const GetActivityType$inboundSchema: z.ZodMiniType<
  GetActivityType,
  unknown
> = openEnums.inboundSchema(GetActivityType);

/** @internal */
export const GetActivityActivity$inboundSchema: z.ZodMiniType<
  GetActivityActivity,
  unknown
> = z.object({
  agent: types.nullable(types.boolean()),
  apiKey: types.nullable(types.string()),
  case: types.nullable(types.string()),
  detail: types.string(),
  id: types.string(),
  query: types.string(),
  result: types.nullable(
    smartUnion([
      types.number(),
      z.lazy(() => GetActivityResult$inboundSchema),
      types.string(),
      types.boolean(),
    ]),
  ),
  time: types.number(),
  type: GetActivityType$inboundSchema,
  user: types.nullable(types.string()),
});

export function getActivityActivityFromJSON(
  jsonString: string,
): SafeParseResult<GetActivityActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetActivityActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetActivityActivity' from JSON`,
  );
}

/** @internal */
export const GetActivityResponse$inboundSchema: z.ZodMiniType<
  GetActivityResponse,
  unknown
> = z.object({
  activity: z.lazy(() => GetActivityActivity$inboundSchema),
  success: types.boolean(),
});

export function getActivityResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetActivityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetActivityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetActivityResponse' from JSON`,
  );
}
