/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Key = {
  /**
   * an integer representing a safe Unix timestamp
   */
  createdAt: number;
  enabled: boolean;
  expiresAt: number | null;
  id: string;
  lastRefillAt: number | null;
  lastRequest: number | null;
  metadata: { [k: string]: any } | null;
  name: string | null;
  permissions: { [k: string]: Array<string> } | null;
  prefix: string | null;
  rateLimitEnabled: boolean;
  rateLimitMax: number | null;
  rateLimitTimeWindow: number | null;
  refillAmount: number | null;
  refillInterval: number | null;
  remaining: number | null;
  requestCount: number;
  start: string | null;
  /**
   * an integer representing a safe Unix timestamp
   */
  updatedAt: number;
  userId: string;
};

export const RestrictedFeatures = {
  Address: "address",
  Breachvip: "breachvip",
  Certificates: "certificates",
  Cloudsint: "cloudsint",
  Courtrecords: "courtrecords",
  Discord: "discord",
  Dnsdumpster: "dnsdumpster",
  Doogle: "doogle",
  Doublecounter: "doublecounter",
  Email: "email",
  Fr: "fr",
  Geolocation: "geolocation",
  GhosintSearch: "ghosint.search",
  Github: "github",
  Gmail: "gmail",
  Hudsonrock: "hudsonrock",
  IntelligencexIdentityportal: "intelligencex.identityportal",
  Intelx: "intelx",
  IntelxStealerlogs: "intelx.stealerlogs",
  Ipinfo: "ipinfo",
  Leakcheck: "leakcheck",
  Leakosint: "leakosint",
  Melissa: "melissa",
  Minecraft: "minecraft",
  Osintindustries: "osintindustries",
  Person: "person",
  Phone: "phone",
  Phonebook: "phonebook",
  Pimeyes: "pimeyes",
  Portscan: "portscan",
  Roblox: "roblox",
  Scraper: "scraper",
  Seon: "seon",
  Shodan: "shodan",
  Snusbase: "snusbase",
  Tiktok: "tiktok",
  Uk: "uk",
  Username: "username",
  Vehicle: "vehicle",
  WebDbs: "web-dbs",
  Whois: "whois",
} as const;
export type RestrictedFeatures = OpenEnum<typeof RestrictedFeatures>;

export type User = {
  acceptOrgInvites: boolean;
  acceptedLegalHash: string | null;
  /**
   * an integer representing a safe Unix timestamp
   */
  banExpires: number;
  banReason: string | null;
  banned: boolean | null;
  boughtCreditsAfterReferral: boolean | null;
  /**
   * an integer representing a safe Unix timestamp
   */
  createdAt: number;
  displayUsername: string | null;
  email: string;
  emailVerified: boolean;
  flagged: boolean | null;
  id: string;
  image: string | null;
  name: string;
  referralLink: string | null;
  referred: string | null;
  restrictedFeatures: Array<RestrictedFeatures> | null;
  role: string | null;
  stripeConnectedId: string | null;
  stripeId: string | null;
  taxState: string | null;
  tokens: number | null;
  twoFactorEnabled: boolean | null;
  /**
   * an integer representing a safe Unix timestamp
   */
  updatedAt: number;
  username: string | null;
};

/**
 * Successful response with user information.
 */
export type GetInfoResponse = {
  key: Key;
  success: boolean;
  user: User;
};

/** @internal */
export const Key$inboundSchema: z.ZodMiniType<Key, unknown> = z.object({
  createdAt: types.number(),
  enabled: types.boolean(),
  expiresAt: types.nullable(types.number()),
  id: types.string(),
  lastRefillAt: types.nullable(types.number()),
  lastRequest: types.nullable(types.number()),
  metadata: types.nullable(z.record(z.string(), z.any())),
  name: types.nullable(types.string()),
  permissions: types.nullable(z.record(z.string(), z.array(types.string()))),
  prefix: types.nullable(types.string()),
  rateLimitEnabled: types.boolean(),
  rateLimitMax: types.nullable(types.number()),
  rateLimitTimeWindow: types.nullable(types.number()),
  refillAmount: types.nullable(types.number()),
  refillInterval: types.nullable(types.number()),
  remaining: types.nullable(types.number()),
  requestCount: types.number(),
  start: types.nullable(types.string()),
  updatedAt: types.number(),
  userId: types.string(),
});

export function keyFromJSON(
  jsonString: string,
): SafeParseResult<Key, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Key$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Key' from JSON`,
  );
}

/** @internal */
export const RestrictedFeatures$inboundSchema: z.ZodMiniType<
  RestrictedFeatures,
  unknown
> = openEnums.inboundSchema(RestrictedFeatures);

/** @internal */
export const User$inboundSchema: z.ZodMiniType<User, unknown> = z.object({
  acceptOrgInvites: types.boolean(),
  acceptedLegalHash: types.nullable(types.string()),
  banExpires: types.number(),
  banReason: types.nullable(types.string()),
  banned: types.nullable(types.boolean()),
  boughtCreditsAfterReferral: types.nullable(types.boolean()),
  createdAt: types.number(),
  displayUsername: types.nullable(types.string()),
  email: types.string(),
  emailVerified: types.boolean(),
  flagged: types.nullable(types.boolean()),
  id: types.string(),
  image: types.nullable(types.string()),
  name: types.string(),
  referralLink: types.nullable(types.string()),
  referred: types.nullable(types.string()),
  restrictedFeatures: types.nullable(z.array(RestrictedFeatures$inboundSchema)),
  role: types.nullable(types.string()),
  stripeConnectedId: types.nullable(types.string()),
  stripeId: types.nullable(types.string()),
  taxState: types.nullable(types.string()),
  tokens: types.nullable(types.number()),
  twoFactorEnabled: types.nullable(types.boolean()),
  updatedAt: types.number(),
  username: types.nullable(types.string()),
});

export function userFromJSON(
  jsonString: string,
): SafeParseResult<User, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => User$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'User' from JSON`,
  );
}

/** @internal */
export const GetInfoResponse$inboundSchema: z.ZodMiniType<
  GetInfoResponse,
  unknown
> = z.object({
  key: z.lazy(() => Key$inboundSchema),
  success: types.boolean(),
  user: z.lazy(() => User$inboundSchema),
});

export function getInfoResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetInfoResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetInfoResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetInfoResponse' from JSON`,
  );
}
