/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1OrganizationsOrganization = {
  /**
   * an integer representing a safe Unix timestamp
   */
  createdAt: number;
  defaultCaseVisibility: string;
  description: string | null;
  id: string;
  logo: string | null;
  memberCount: number;
  myRole: string | null;
  name: string;
  slug: string;
};

/**
 * List of organizations with member counts and your role.
 */
export type GetV1OrganizationsResponse = {
  organizations: Array<GetV1OrganizationsOrganization>;
  success: boolean;
};

/** @internal */
export const GetV1OrganizationsOrganization$inboundSchema: z.ZodMiniType<
  GetV1OrganizationsOrganization,
  unknown
> = z.object({
  createdAt: types.number(),
  defaultCaseVisibility: types.string(),
  description: types.nullable(types.string()),
  id: types.string(),
  logo: types.nullable(types.string()),
  memberCount: types.number(),
  myRole: types.nullable(types.string()),
  name: types.string(),
  slug: types.string(),
});

export function getV1OrganizationsOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<GetV1OrganizationsOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1OrganizationsOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1OrganizationsOrganization' from JSON`,
  );
}

/** @internal */
export const GetV1OrganizationsResponse$inboundSchema: z.ZodMiniType<
  GetV1OrganizationsResponse,
  unknown
> = z.object({
  organizations: z.array(
    z.lazy(() => GetV1OrganizationsOrganization$inboundSchema),
  ),
  success: types.boolean(),
});

export function getV1OrganizationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1OrganizationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1OrganizationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1OrganizationsResponse' from JSON`,
  );
}
