/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Successful response
 */
export type GetPricingResponse = {
  current: number;
  prices: { [k: string]: number };
  success: boolean;
};

/** @internal */
export const GetPricingResponse$inboundSchema: z.ZodMiniType<
  GetPricingResponse,
  unknown
> = z.object({
  current: types.number(),
  prices: z.record(z.string(), types.number()),
  success: types.boolean(),
});

export function getPricingResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPricingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPricingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPricingResponse' from JSON`,
  );
}
