/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1ActivityByIdRequest = {
  /**
   * a UUID
   */
  id: string;
};

export type GetV1ActivityByIdResult = {};

export type GetV1ActivityByIdResultUnion =
  | number
  | GetV1ActivityByIdResult
  | string
  | boolean;

export const GetV1ActivityByIdType = {
  Address: "address",
  Breachvip: "breachvip",
  Certificates: "certificates",
  Cloudsint: "cloudsint",
  Courtrecords: "courtrecords",
  Discord: "discord",
  Dnsdumpster: "dnsdumpster",
  Doogle: "doogle",
  Doublecounter: "doublecounter",
  Email: "email",
  Fr: "fr",
  Geolocation: "geolocation",
  GhosintSearch: "ghosint.search",
  Github: "github",
  Gmail: "gmail",
  Hudsonrock: "hudsonrock",
  IntelligencexIdentityportal: "intelligencex.identityportal",
  Intelx: "intelx",
  IntelxStealerlogs: "intelx.stealerlogs",
  Ipinfo: "ipinfo",
  Leakcheck: "leakcheck",
  Leakosint: "leakosint",
  Melissa: "melissa",
  Minecraft: "minecraft",
  Osintindustries: "osintindustries",
  Other: "other",
  Person: "person",
  Phone: "phone",
  Phonebook: "phonebook",
  Pimeyes: "pimeyes",
  Portscan: "portscan",
  Roblox: "roblox",
  Scraper: "scraper",
  Seon: "seon",
  Shodan: "shodan",
  Snusbase: "snusbase",
  Tiktok: "tiktok",
  Uk: "uk",
  Username: "username",
  Usernames: "usernames",
  Vehicle: "vehicle",
  WebDbs: "web-dbs",
  Whois: "whois",
} as const;
export type GetV1ActivityByIdType = OpenEnum<typeof GetV1ActivityByIdType>;

export type GetV1ActivityByIdActivity = {
  agent: boolean | null;
  apiKey: string | null;
  case: string | null;
  detail: string;
  /**
   * a RFC-4122-compliant UUID
   */
  id: string;
  query: string;
  result: number | GetV1ActivityByIdResult | string | boolean | null;
  /**
   * an integer representing a safe Unix timestamp
   */
  time: number;
  type: GetV1ActivityByIdType;
  user: string | null;
};

/**
 * Successful response with the activity details.
 */
export type GetV1ActivityByIdResponse = {
  activity: GetV1ActivityByIdActivity;
  success: boolean;
};

/** @internal */
export type GetV1ActivityByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1ActivityByIdRequest$outboundSchema: z.ZodMiniType<
  GetV1ActivityByIdRequest$Outbound,
  GetV1ActivityByIdRequest
> = z.object({
  id: z.string(),
});

export function getV1ActivityByIdRequestToJSON(
  getV1ActivityByIdRequest: GetV1ActivityByIdRequest,
): string {
  return JSON.stringify(
    GetV1ActivityByIdRequest$outboundSchema.parse(getV1ActivityByIdRequest),
  );
}

/** @internal */
export const GetV1ActivityByIdResult$inboundSchema: z.ZodMiniType<
  GetV1ActivityByIdResult,
  unknown
> = z.object({});

export function getV1ActivityByIdResultFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ActivityByIdResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ActivityByIdResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ActivityByIdResult' from JSON`,
  );
}

/** @internal */
export const GetV1ActivityByIdResultUnion$inboundSchema: z.ZodMiniType<
  GetV1ActivityByIdResultUnion,
  unknown
> = smartUnion([
  types.number(),
  z.lazy(() => GetV1ActivityByIdResult$inboundSchema),
  types.string(),
  types.boolean(),
]);

export function getV1ActivityByIdResultUnionFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ActivityByIdResultUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ActivityByIdResultUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ActivityByIdResultUnion' from JSON`,
  );
}

/** @internal */
export const GetV1ActivityByIdType$inboundSchema: z.ZodMiniType<
  GetV1ActivityByIdType,
  unknown
> = openEnums.inboundSchema(GetV1ActivityByIdType);

/** @internal */
export const GetV1ActivityByIdActivity$inboundSchema: z.ZodMiniType<
  GetV1ActivityByIdActivity,
  unknown
> = z.object({
  agent: types.nullable(types.boolean()),
  apiKey: types.nullable(types.string()),
  case: types.nullable(types.string()),
  detail: types.string(),
  id: types.string(),
  query: types.string(),
  result: types.nullable(
    smartUnion([
      types.number(),
      z.lazy(() => GetV1ActivityByIdResult$inboundSchema),
      types.string(),
      types.boolean(),
    ]),
  ),
  time: types.number(),
  type: GetV1ActivityByIdType$inboundSchema,
  user: types.nullable(types.string()),
});

export function getV1ActivityByIdActivityFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ActivityByIdActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ActivityByIdActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ActivityByIdActivity' from JSON`,
  );
}

/** @internal */
export const GetV1ActivityByIdResponse$inboundSchema: z.ZodMiniType<
  GetV1ActivityByIdResponse,
  unknown
> = z.object({
  activity: z.lazy(() => GetV1ActivityByIdActivity$inboundSchema),
  success: types.boolean(),
});

export function getV1ActivityByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ActivityByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ActivityByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ActivityByIdResponse' from JSON`,
  );
}
