/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListActivitiesRequest = {
  limit?: string | undefined;
  offset?: string | undefined;
};

export type ListActivitiesResult = {};

export type ListActivitiesResultUnion =
  | number
  | ListActivitiesResult
  | string
  | boolean;

export const ListActivitiesType = {
  Address: "address",
  Breachvip: "breachvip",
  Certificates: "certificates",
  Cloudsint: "cloudsint",
  Courtrecords: "courtrecords",
  Discord: "discord",
  Dnsdumpster: "dnsdumpster",
  Doogle: "doogle",
  Doublecounter: "doublecounter",
  Email: "email",
  Fr: "fr",
  Geolocation: "geolocation",
  GhosintSearch: "ghosint.search",
  Github: "github",
  Gmail: "gmail",
  Hudsonrock: "hudsonrock",
  IntelligencexIdentityportal: "intelligencex.identityportal",
  Intelx: "intelx",
  IntelxStealerlogs: "intelx.stealerlogs",
  Ipinfo: "ipinfo",
  Leakcheck: "leakcheck",
  Leakosint: "leakosint",
  Melissa: "melissa",
  Minecraft: "minecraft",
  Osintindustries: "osintindustries",
  Other: "other",
  Person: "person",
  Phone: "phone",
  Phonebook: "phonebook",
  Pimeyes: "pimeyes",
  Portscan: "portscan",
  Roblox: "roblox",
  Scraper: "scraper",
  Seon: "seon",
  Shodan: "shodan",
  Snusbase: "snusbase",
  Tiktok: "tiktok",
  Uk: "uk",
  Username: "username",
  Usernames: "usernames",
  Vehicle: "vehicle",
  VirustotalContent: "virustotal.content",
  VirustotalDownload: "virustotal.download",
  VirustotalIntelligence: "virustotal.intelligence",
  WebDbs: "web-dbs",
  Whois: "whois",
} as const;
export type ListActivitiesType = OpenEnum<typeof ListActivitiesType>;

export type ListActivitiesActivity = {
  agent: boolean | null;
  apiKey: string | null;
  case: string | null;
  detail: string;
  /**
   * a RFC-4122-compliant UUID
   */
  id: string;
  query: string;
  result: number | ListActivitiesResult | string | boolean | null;
  /**
   * an integer representing a safe Unix timestamp
   */
  time: number;
  type: ListActivitiesType;
  user: string | null;
};

/**
 * Successful response with a list of activities.
 */
export type ListActivitiesResponse = {
  activities: Array<ListActivitiesActivity>;
  success: boolean;
};

/** @internal */
export type ListActivitiesRequest$Outbound = {
  limit?: string | undefined;
  offset?: string | undefined;
};

/** @internal */
export const ListActivitiesRequest$outboundSchema: z.ZodMiniType<
  ListActivitiesRequest$Outbound,
  ListActivitiesRequest
> = z.object({
  limit: z.optional(z.string()),
  offset: z.optional(z.string()),
});

export function listActivitiesRequestToJSON(
  listActivitiesRequest: ListActivitiesRequest,
): string {
  return JSON.stringify(
    ListActivitiesRequest$outboundSchema.parse(listActivitiesRequest),
  );
}

/** @internal */
export const ListActivitiesResult$inboundSchema: z.ZodMiniType<
  ListActivitiesResult,
  unknown
> = z.object({});

export function listActivitiesResultFromJSON(
  jsonString: string,
): SafeParseResult<ListActivitiesResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListActivitiesResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListActivitiesResult' from JSON`,
  );
}

/** @internal */
export const ListActivitiesResultUnion$inboundSchema: z.ZodMiniType<
  ListActivitiesResultUnion,
  unknown
> = smartUnion([
  types.number(),
  z.lazy(() => ListActivitiesResult$inboundSchema),
  types.string(),
  types.boolean(),
]);

export function listActivitiesResultUnionFromJSON(
  jsonString: string,
): SafeParseResult<ListActivitiesResultUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListActivitiesResultUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListActivitiesResultUnion' from JSON`,
  );
}

/** @internal */
export const ListActivitiesType$inboundSchema: z.ZodMiniType<
  ListActivitiesType,
  unknown
> = openEnums.inboundSchema(ListActivitiesType);

/** @internal */
export const ListActivitiesActivity$inboundSchema: z.ZodMiniType<
  ListActivitiesActivity,
  unknown
> = z.object({
  agent: types.nullable(types.boolean()),
  apiKey: types.nullable(types.string()),
  case: types.nullable(types.string()),
  detail: types.string(),
  id: types.string(),
  query: types.string(),
  result: types.nullable(
    smartUnion([
      types.number(),
      z.lazy(() => ListActivitiesResult$inboundSchema),
      types.string(),
      types.boolean(),
    ]),
  ),
  time: types.number(),
  type: ListActivitiesType$inboundSchema,
  user: types.nullable(types.string()),
});

export function listActivitiesActivityFromJSON(
  jsonString: string,
): SafeParseResult<ListActivitiesActivity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListActivitiesActivity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListActivitiesActivity' from JSON`,
  );
}

/** @internal */
export const ListActivitiesResponse$inboundSchema: z.ZodMiniType<
  ListActivitiesResponse,
  unknown
> = z.object({
  activities: z.array(z.lazy(() => ListActivitiesActivity$inboundSchema)),
  success: types.boolean(),
});

export function listActivitiesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListActivitiesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListActivitiesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListActivitiesResponse' from JSON`,
  );
}
