/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListOrganizationMembersRequest = {
  id: string;
};

export type Member = {
  /**
   * an integer representing a safe Unix timestamp
   */
  createdAt: number;
  displayUsername: string | null;
  id: string;
  organizationId: string;
  role: string;
  userId: string;
  username: string | null;
};

/**
 * Member list.
 */
export type ListOrganizationMembersResponse = {
  members: Array<Member>;
  success: boolean;
};

/** @internal */
export type ListOrganizationMembersRequest$Outbound = {
  id: string;
};

/** @internal */
export const ListOrganizationMembersRequest$outboundSchema: z.ZodMiniType<
  ListOrganizationMembersRequest$Outbound,
  ListOrganizationMembersRequest
> = z.object({
  id: z.string(),
});

export function listOrganizationMembersRequestToJSON(
  listOrganizationMembersRequest: ListOrganizationMembersRequest,
): string {
  return JSON.stringify(
    ListOrganizationMembersRequest$outboundSchema.parse(
      listOrganizationMembersRequest,
    ),
  );
}

/** @internal */
export const Member$inboundSchema: z.ZodMiniType<Member, unknown> = z.object({
  createdAt: types.number(),
  displayUsername: types.nullable(types.string()),
  id: types.string(),
  organizationId: types.string(),
  role: types.string(),
  userId: types.string(),
  username: types.nullable(types.string()),
});

export function memberFromJSON(
  jsonString: string,
): SafeParseResult<Member, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Member$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Member' from JSON`,
  );
}

/** @internal */
export const ListOrganizationMembersResponse$inboundSchema: z.ZodMiniType<
  ListOrganizationMembersResponse,
  unknown
> = z.object({
  members: z.array(z.lazy(() => Member$inboundSchema)),
  success: types.boolean(),
});

export function listOrganizationMembersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationMembersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOrganizationMembersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationMembersResponse' from JSON`,
  );
}
