/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListOrganizationCasesRequest = {
  id: string;
};

export type Case = {
  /**
   * an integer representing a safe Unix timestamp
   */
  createdAt: number;
  description: string | null;
  id: string;
  name: string | null;
  organizationId: string | null;
  owner: string;
};

/**
 * Shared cases.
 */
export type ListOrganizationCasesResponse = {
  cases: Array<Case>;
  success: boolean;
};

/** @internal */
export type ListOrganizationCasesRequest$Outbound = {
  id: string;
};

/** @internal */
export const ListOrganizationCasesRequest$outboundSchema: z.ZodMiniType<
  ListOrganizationCasesRequest$Outbound,
  ListOrganizationCasesRequest
> = z.object({
  id: z.string(),
});

export function listOrganizationCasesRequestToJSON(
  listOrganizationCasesRequest: ListOrganizationCasesRequest,
): string {
  return JSON.stringify(
    ListOrganizationCasesRequest$outboundSchema.parse(
      listOrganizationCasesRequest,
    ),
  );
}

/** @internal */
export const Case$inboundSchema: z.ZodMiniType<Case, unknown> = z.object({
  createdAt: types.number(),
  description: types.nullable(types.string()),
  id: types.string(),
  name: types.nullable(types.string()),
  organizationId: types.nullable(types.string()),
  owner: types.string(),
});

export function caseFromJSON(
  jsonString: string,
): SafeParseResult<Case, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Case$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Case' from JSON`,
  );
}

/** @internal */
export const ListOrganizationCasesResponse$inboundSchema: z.ZodMiniType<
  ListOrganizationCasesResponse,
  unknown
> = z.object({
  cases: z.array(z.lazy(() => Case$inboundSchema)),
  success: types.boolean(),
});

export function listOrganizationCasesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationCasesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOrganizationCasesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationCasesResponse' from JSON`,
  );
}
