/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type LookupDiscordAltRequest = {
  query: string;
};

export type First = {
  avatar: string;
  id: string;
  username: string;
};

export type Second = {
  avatar: string;
  id: string;
  username: string;
};

export type Third = {
  avatar: string;
  id: string;
  username: string;
};

export type LookupDiscordAltData = {
  first: Array<First>;
  second: Array<Second>;
  third: Array<Third>;
  tier: string;
  totalalts: number;
  verifications: number;
  vpns: number;
};

/**
 * Search successful
 */
export type LookupDiscordAltResponse = {
  success: boolean;
  data?: LookupDiscordAltData | undefined;
  error?: string | undefined;
};

/** @internal */
export type LookupDiscordAltRequest$Outbound = {
  query: string;
};

/** @internal */
export const LookupDiscordAltRequest$outboundSchema: z.ZodMiniType<
  LookupDiscordAltRequest$Outbound,
  LookupDiscordAltRequest
> = z.object({
  query: z.string(),
});

export function lookupDiscordAltRequestToJSON(
  lookupDiscordAltRequest: LookupDiscordAltRequest,
): string {
  return JSON.stringify(
    LookupDiscordAltRequest$outboundSchema.parse(lookupDiscordAltRequest),
  );
}

/** @internal */
export const First$inboundSchema: z.ZodMiniType<First, unknown> = z.object({
  avatar: types.string(),
  id: types.string(),
  username: types.string(),
});

export function firstFromJSON(
  jsonString: string,
): SafeParseResult<First, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => First$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'First' from JSON`,
  );
}

/** @internal */
export const Second$inboundSchema: z.ZodMiniType<Second, unknown> = z.object({
  avatar: types.string(),
  id: types.string(),
  username: types.string(),
});

export function secondFromJSON(
  jsonString: string,
): SafeParseResult<Second, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Second$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Second' from JSON`,
  );
}

/** @internal */
export const Third$inboundSchema: z.ZodMiniType<Third, unknown> = z.object({
  avatar: types.string(),
  id: types.string(),
  username: types.string(),
});

export function thirdFromJSON(
  jsonString: string,
): SafeParseResult<Third, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Third$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Third' from JSON`,
  );
}

/** @internal */
export const LookupDiscordAltData$inboundSchema: z.ZodMiniType<
  LookupDiscordAltData,
  unknown
> = z.object({
  first: z.array(z.lazy(() => First$inboundSchema)),
  second: z.array(z.lazy(() => Second$inboundSchema)),
  third: z.array(z.lazy(() => Third$inboundSchema)),
  tier: types.string(),
  totalalts: types.number(),
  verifications: types.number(),
  vpns: types.number(),
});

export function lookupDiscordAltDataFromJSON(
  jsonString: string,
): SafeParseResult<LookupDiscordAltData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupDiscordAltData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupDiscordAltData' from JSON`,
  );
}

/** @internal */
export const LookupDiscordAltResponse$inboundSchema: z.ZodMiniType<
  LookupDiscordAltResponse,
  unknown
> = z.object({
  success: types.boolean(),
  data: types.optional(z.lazy(() => LookupDiscordAltData$inboundSchema)),
  error: types.optional(types.string()),
});

export function lookupDiscordAltResponseFromJSON(
  jsonString: string,
): SafeParseResult<LookupDiscordAltResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LookupDiscordAltResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LookupDiscordAltResponse' from JSON`,
  );
}
