/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostV1SearchIntelligenceGmailRequest = {
  email: string;
};

export type Position = {
  latitude: number;
  longitude: number;
};

export type PostV1SearchIntelligenceGmailLocation = {
  address: string;
  costLevel: number;
  id: string;
  name: string;
  position: Position;
  tags: Array<string>;
  types: Array<string>;
};

export type Photo = {
  date: string;
  id: string;
  location: PostV1SearchIntelligenceGmailLocation;
  url: string;
};

export type Maps = {
  photos: Array<Photo>;
  reviews: Array<{ [k: string]: any }>;
  stats: { [k: string]: number };
};

export type CoverPhotos = {
  flathash: string | null;
  isDefault: boolean;
  url: string;
};

export type Emails = {
  value: string;
};

export type DynamiteData = {
  customerId: string | null;
  dndState: string;
  entityType: string;
  presence: string;
};

export type GplusData = {
  contentRestriction: string;
  isEntrepriseUser: boolean;
};

export type ExtendedData = {
  dynamiteData: DynamiteData;
  gplusData: GplusData;
};

export type InAppReachability = {
  apps: Array<string>;
};

export type Names = {
  fullname: string;
};

export type ProfileInfos = {
  userTypes: Array<string>;
};

export type ProfilePhotos = {
  flathash: string | null;
  isDefault: boolean;
  url: string;
};

export type SourceIds = {
  lastUpdated: string | null;
};

export type PostV1SearchIntelligenceGmailProfile = {
  coverPhotos: { [k: string]: CoverPhotos };
  emails: { [k: string]: Emails };
  extendedData: ExtendedData;
  inAppReachability: { [k: string]: InAppReachability };
  names: { [k: string]: Names };
  personId: string;
  profileInfos: { [k: string]: ProfileInfos };
  profilePhotos: { [k: string]: ProfilePhotos };
  sourceIds: { [k: string]: SourceIds };
};

export type Calendar = {
  details: { [k: string]: any };
  events: { [k: string]: any };
};

export type PlayGames = {
  avatarUrl: string;
  id: string;
  name: string;
};

export type ProfileContainer = {
  maps: Maps;
  profile: PostV1SearchIntelligenceGmailProfile;
  calendar?: Calendar | undefined;
  playGames?: PlayGames | undefined;
};

export type PostV1SearchIntelligenceGmailData = {
  profileContainer?: ProfileContainer | undefined;
};

/**
 * Successful Response
 */
export type PostV1SearchIntelligenceGmailResponse = {
  success: boolean;
  data?: PostV1SearchIntelligenceGmailData | undefined;
  error?: string | undefined;
};

/** @internal */
export type PostV1SearchIntelligenceGmailRequest$Outbound = {
  email: string;
};

/** @internal */
export const PostV1SearchIntelligenceGmailRequest$outboundSchema: z.ZodMiniType<
  PostV1SearchIntelligenceGmailRequest$Outbound,
  PostV1SearchIntelligenceGmailRequest
> = z.object({
  email: z.string(),
});

export function postV1SearchIntelligenceGmailRequestToJSON(
  postV1SearchIntelligenceGmailRequest: PostV1SearchIntelligenceGmailRequest,
): string {
  return JSON.stringify(
    PostV1SearchIntelligenceGmailRequest$outboundSchema.parse(
      postV1SearchIntelligenceGmailRequest,
    ),
  );
}

/** @internal */
export const Position$inboundSchema: z.ZodMiniType<Position, unknown> = z
  .object({
    latitude: types.number(),
    longitude: types.number(),
  });

export function positionFromJSON(
  jsonString: string,
): SafeParseResult<Position, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Position$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Position' from JSON`,
  );
}

/** @internal */
export const PostV1SearchIntelligenceGmailLocation$inboundSchema: z.ZodMiniType<
  PostV1SearchIntelligenceGmailLocation,
  unknown
> = z.pipe(
  z.object({
    address: types.string(),
    cost_level: types.number(),
    id: types.string(),
    name: types.string(),
    position: z.lazy(() => Position$inboundSchema),
    tags: z.array(types.string()),
    types: z.array(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "cost_level": "costLevel",
    });
  }),
);

export function postV1SearchIntelligenceGmailLocationFromJSON(
  jsonString: string,
): SafeParseResult<PostV1SearchIntelligenceGmailLocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1SearchIntelligenceGmailLocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1SearchIntelligenceGmailLocation' from JSON`,
  );
}

/** @internal */
export const Photo$inboundSchema: z.ZodMiniType<Photo, unknown> = z.object({
  date: types.string(),
  id: types.string(),
  location: z.lazy(() => PostV1SearchIntelligenceGmailLocation$inboundSchema),
  url: types.string(),
});

export function photoFromJSON(
  jsonString: string,
): SafeParseResult<Photo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Photo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Photo' from JSON`,
  );
}

/** @internal */
export const Maps$inboundSchema: z.ZodMiniType<Maps, unknown> = z.object({
  photos: z.array(z.lazy(() => Photo$inboundSchema)),
  reviews: z.array(z.record(z.string(), z.any())),
  stats: z.record(z.string(), types.number()),
});

export function mapsFromJSON(
  jsonString: string,
): SafeParseResult<Maps, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Maps$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Maps' from JSON`,
  );
}

/** @internal */
export const CoverPhotos$inboundSchema: z.ZodMiniType<CoverPhotos, unknown> = z
  .object({
    flathash: types.nullable(types.string()),
    isDefault: types.boolean(),
    url: types.string(),
  });

export function coverPhotosFromJSON(
  jsonString: string,
): SafeParseResult<CoverPhotos, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CoverPhotos$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CoverPhotos' from JSON`,
  );
}

/** @internal */
export const Emails$inboundSchema: z.ZodMiniType<Emails, unknown> = z.object({
  value: types.string(),
});

export function emailsFromJSON(
  jsonString: string,
): SafeParseResult<Emails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Emails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Emails' from JSON`,
  );
}

/** @internal */
export const DynamiteData$inboundSchema: z.ZodMiniType<DynamiteData, unknown> =
  z.object({
    customerId: types.nullable(types.string()),
    dndState: types.string(),
    entityType: types.string(),
    presence: types.string(),
  });

export function dynamiteDataFromJSON(
  jsonString: string,
): SafeParseResult<DynamiteData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DynamiteData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DynamiteData' from JSON`,
  );
}

/** @internal */
export const GplusData$inboundSchema: z.ZodMiniType<GplusData, unknown> = z
  .object({
    contentRestriction: types.string(),
    isEntrepriseUser: types.boolean(),
  });

export function gplusDataFromJSON(
  jsonString: string,
): SafeParseResult<GplusData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GplusData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GplusData' from JSON`,
  );
}

/** @internal */
export const ExtendedData$inboundSchema: z.ZodMiniType<ExtendedData, unknown> =
  z.object({
    dynamiteData: z.lazy(() => DynamiteData$inboundSchema),
    gplusData: z.lazy(() => GplusData$inboundSchema),
  });

export function extendedDataFromJSON(
  jsonString: string,
): SafeParseResult<ExtendedData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExtendedData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtendedData' from JSON`,
  );
}

/** @internal */
export const InAppReachability$inboundSchema: z.ZodMiniType<
  InAppReachability,
  unknown
> = z.object({
  apps: z.array(types.string()),
});

export function inAppReachabilityFromJSON(
  jsonString: string,
): SafeParseResult<InAppReachability, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InAppReachability$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InAppReachability' from JSON`,
  );
}

/** @internal */
export const Names$inboundSchema: z.ZodMiniType<Names, unknown> = z.object({
  fullname: types.string(),
});

export function namesFromJSON(
  jsonString: string,
): SafeParseResult<Names, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Names$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Names' from JSON`,
  );
}

/** @internal */
export const ProfileInfos$inboundSchema: z.ZodMiniType<ProfileInfos, unknown> =
  z.object({
    userTypes: z.array(types.string()),
  });

export function profileInfosFromJSON(
  jsonString: string,
): SafeParseResult<ProfileInfos, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProfileInfos$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProfileInfos' from JSON`,
  );
}

/** @internal */
export const ProfilePhotos$inboundSchema: z.ZodMiniType<
  ProfilePhotos,
  unknown
> = z.object({
  flathash: types.nullable(types.string()),
  isDefault: types.boolean(),
  url: types.string(),
});

export function profilePhotosFromJSON(
  jsonString: string,
): SafeParseResult<ProfilePhotos, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProfilePhotos$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProfilePhotos' from JSON`,
  );
}

/** @internal */
export const SourceIds$inboundSchema: z.ZodMiniType<SourceIds, unknown> = z
  .object({
    lastUpdated: types.nullable(types.string()),
  });

export function sourceIdsFromJSON(
  jsonString: string,
): SafeParseResult<SourceIds, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SourceIds$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SourceIds' from JSON`,
  );
}

/** @internal */
export const PostV1SearchIntelligenceGmailProfile$inboundSchema: z.ZodMiniType<
  PostV1SearchIntelligenceGmailProfile,
  unknown
> = z.object({
  coverPhotos: z.record(z.string(), z.lazy(() => CoverPhotos$inboundSchema)),
  emails: z.record(z.string(), z.lazy(() => Emails$inboundSchema)),
  extendedData: z.lazy(() => ExtendedData$inboundSchema),
  inAppReachability: z.record(
    z.string(),
    z.lazy(() => InAppReachability$inboundSchema),
  ),
  names: z.record(z.string(), z.lazy(() => Names$inboundSchema)),
  personId: types.string(),
  profileInfos: z.record(z.string(), z.lazy(() => ProfileInfos$inboundSchema)),
  profilePhotos: z.record(
    z.string(),
    z.lazy(() => ProfilePhotos$inboundSchema),
  ),
  sourceIds: z.record(z.string(), z.lazy(() => SourceIds$inboundSchema)),
});

export function postV1SearchIntelligenceGmailProfileFromJSON(
  jsonString: string,
): SafeParseResult<PostV1SearchIntelligenceGmailProfile, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1SearchIntelligenceGmailProfile$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1SearchIntelligenceGmailProfile' from JSON`,
  );
}

/** @internal */
export const Calendar$inboundSchema: z.ZodMiniType<Calendar, unknown> = z
  .object({
    details: z.record(z.string(), z.any()),
    events: z.record(z.string(), z.any()),
  });

export function calendarFromJSON(
  jsonString: string,
): SafeParseResult<Calendar, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Calendar$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Calendar' from JSON`,
  );
}

/** @internal */
export const PlayGames$inboundSchema: z.ZodMiniType<PlayGames, unknown> = z
  .pipe(
    z.object({
      avatar_url: types.string(),
      id: types.string(),
      name: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "avatar_url": "avatarUrl",
      });
    }),
  );

export function playGamesFromJSON(
  jsonString: string,
): SafeParseResult<PlayGames, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlayGames$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlayGames' from JSON`,
  );
}

/** @internal */
export const ProfileContainer$inboundSchema: z.ZodMiniType<
  ProfileContainer,
  unknown
> = z.pipe(
  z.object({
    maps: z.lazy(() => Maps$inboundSchema),
    profile: z.lazy(() => PostV1SearchIntelligenceGmailProfile$inboundSchema),
    calendar: types.optional(z.lazy(() => Calendar$inboundSchema)),
    play_games: types.optional(z.lazy(() => PlayGames$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "play_games": "playGames",
    });
  }),
);

export function profileContainerFromJSON(
  jsonString: string,
): SafeParseResult<ProfileContainer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProfileContainer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProfileContainer' from JSON`,
  );
}

/** @internal */
export const PostV1SearchIntelligenceGmailData$inboundSchema: z.ZodMiniType<
  PostV1SearchIntelligenceGmailData,
  unknown
> = z.pipe(
  z.object({
    PROFILE_CONTAINER: types.optional(
      z.lazy(() => ProfileContainer$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "PROFILE_CONTAINER": "profileContainer",
    });
  }),
);

export function postV1SearchIntelligenceGmailDataFromJSON(
  jsonString: string,
): SafeParseResult<PostV1SearchIntelligenceGmailData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1SearchIntelligenceGmailData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1SearchIntelligenceGmailData' from JSON`,
  );
}

/** @internal */
export const PostV1SearchIntelligenceGmailResponse$inboundSchema: z.ZodMiniType<
  PostV1SearchIntelligenceGmailResponse,
  unknown
> = z.object({
  success: types.boolean(),
  data: types.optional(
    z.lazy(() => PostV1SearchIntelligenceGmailData$inboundSchema),
  ),
  error: types.optional(types.string()),
});

export function postV1SearchIntelligenceGmailResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1SearchIntelligenceGmailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1SearchIntelligenceGmailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1SearchIntelligenceGmailResponse' from JSON`,
  );
}
