/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const PostV1SearchIntelligenceHudsonrockTypeRequest = {
  Domain: "domain",
  Email: "email",
  Ip: "ip",
  Password: "password",
  Username: "username",
} as const;
export type PostV1SearchIntelligenceHudsonrockTypeRequest = ClosedEnum<
  typeof PostV1SearchIntelligenceHudsonrockTypeRequest
>;

export type PostV1SearchIntelligenceHudsonrockRequest = {
  query: string;
  type: PostV1SearchIntelligenceHudsonrockTypeRequest;
};

export type Stealer = {
  computerName: string;
  dateCompromised: string;
  ip: string;
  malwarePath: string;
  operatingSystem: string;
  topLogins: Array<string>;
  topPasswords: Array<string>;
  totalCorporateServices: number;
  totalUserServices: number;
  stealerFamily?: string | undefined;
};

export const PostV1SearchIntelligenceHudsonrockDataType2 = {
  Domain: "domain",
  Email: "email",
  Ip: "ip",
  Password: "password",
  Username: "username",
} as const;
export type PostV1SearchIntelligenceHudsonrockDataType2 = OpenEnum<
  typeof PostV1SearchIntelligenceHudsonrockDataType2
>;

export type PostV1SearchIntelligenceHudsonrockData2 = {
  message: string;
  stealers: Array<Stealer>;
  type: PostV1SearchIntelligenceHudsonrockDataType2;
};

export type Application = {
  keyword: string;
};

export type EmployeesUrl = {
  occurrence: number;
  type: string;
  url: string;
};

export type PostV1SearchIntelligenceHudsonrockDataData = {
  employeesUrls: Array<EmployeesUrl>;
};

export type PostV1SearchIntelligenceHudsonrockStats = {
  clientsCount: Array<number>;
  clientsUrls: Array<string>;
  employeesCount: Array<number>;
  employeesUrls: Array<string>;
  totalEmployees: number;
  totalUsers: number;
};

export type ThirdPartyDomain = {
  domain: string;
  occurrence: number;
};

export const PostV1SearchIntelligenceHudsonrockDataType1 = {
  Domain: "domain",
  Email: "email",
  Ip: "ip",
  Password: "password",
  Username: "username",
} as const;
export type PostV1SearchIntelligenceHudsonrockDataType1 = OpenEnum<
  typeof PostV1SearchIntelligenceHudsonrockDataType1
>;

export type PostV1SearchIntelligenceHudsonrockList = {
  count: number;
  name: string;
};

export type Antiviruses = {
  found: number;
  free: string;
  list: Array<PostV1SearchIntelligenceHudsonrockList>;
  notFound: string;
  total: number;
};

export type EmployeePasswordsMedium = {
  perc: number;
  qty: number;
};

export type EmployeePasswordsStrong = {
  perc: number;
  qty: number;
};

export type EmployeePasswordsTooWeak = {
  perc: number;
  qty: number;
};

export type EmployeePasswordsWeak = {
  perc: number;
  qty: number;
};

export type EmployeePasswords = {
  hasStats: boolean;
  medium: EmployeePasswordsMedium;
  strong: EmployeePasswordsStrong;
  tooWeak: EmployeePasswordsTooWeak;
  totalPass: number;
  weak: EmployeePasswordsWeak;
};

export type StealerFamilies = {
  acreed: number;
  atomic: number;
  azorult: number;
  cryptbot: number;
  darkCrystal: number;
  ficker: number;
  genericStealer: number;
  lumma: number;
  mystic: number;
  predator: number;
  raccoon: number;
  redLine: number;
  stealC: number;
  taurus: number;
  unknown: number;
  vidar: number;
  lastCounted: string;
  total: number;
};

export type UserPasswordsMedium = {
  perc: number;
  qty: number;
};

export type UserPasswordsStrong = {
  perc: number;
  qty: number;
};

export type UserPasswordsTooWeak = {
  perc: number;
  qty: number;
};

export type UserPasswordsWeak = {
  perc: number;
  qty: number;
};

export type UserPasswords = {
  hasStats: boolean;
  medium: UserPasswordsMedium;
  strong: UserPasswordsStrong;
  tooWeak: UserPasswordsTooWeak;
  totalPass: number;
  weak: UserPasswordsWeak;
};

export type PostV1SearchIntelligenceHudsonrockData1 = {
  applications: Array<Application>;
  data: PostV1SearchIntelligenceHudsonrockDataData;
  employees: number;
  isShopify: boolean;
  lastEmployeeCompromised: string;
  lastUserCompromised: string;
  logo: string;
  stats: PostV1SearchIntelligenceHudsonrockStats;
  thirdPartyDomains: Array<ThirdPartyDomain>;
  thirdParties: number;
  total: number;
  totalStealers: number;
  totalUrls: number;
  type: PostV1SearchIntelligenceHudsonrockDataType1;
  users: number;
  antiviruses?: Antiviruses | undefined;
  employeePasswords?: EmployeePasswords | undefined;
  stealerFamilies?: StealerFamilies | undefined;
  userPasswords?: UserPasswords | undefined;
};

export type PostV1SearchIntelligenceHudsonrockDataUnion =
  | PostV1SearchIntelligenceHudsonrockData1
  | PostV1SearchIntelligenceHudsonrockData2;

/**
 * Search successful
 */
export type PostV1SearchIntelligenceHudsonrockResponse = {
  data:
    | PostV1SearchIntelligenceHudsonrockData1
    | PostV1SearchIntelligenceHudsonrockData2;
  success: boolean;
  error?: string | undefined;
};

/** @internal */
export const PostV1SearchIntelligenceHudsonrockTypeRequest$outboundSchema:
  z.ZodMiniEnum<typeof PostV1SearchIntelligenceHudsonrockTypeRequest> = z.enum(
    PostV1SearchIntelligenceHudsonrockTypeRequest,
  );

/** @internal */
export type PostV1SearchIntelligenceHudsonrockRequest$Outbound = {
  query: string;
  type: string;
};

/** @internal */
export const PostV1SearchIntelligenceHudsonrockRequest$outboundSchema:
  z.ZodMiniType<
    PostV1SearchIntelligenceHudsonrockRequest$Outbound,
    PostV1SearchIntelligenceHudsonrockRequest
  > = z.object({
    query: z.string(),
    type: PostV1SearchIntelligenceHudsonrockTypeRequest$outboundSchema,
  });

export function postV1SearchIntelligenceHudsonrockRequestToJSON(
  postV1SearchIntelligenceHudsonrockRequest:
    PostV1SearchIntelligenceHudsonrockRequest,
): string {
  return JSON.stringify(
    PostV1SearchIntelligenceHudsonrockRequest$outboundSchema.parse(
      postV1SearchIntelligenceHudsonrockRequest,
    ),
  );
}

/** @internal */
export const Stealer$inboundSchema: z.ZodMiniType<Stealer, unknown> = z.pipe(
  z.object({
    computer_name: types.string(),
    date_compromised: types.string(),
    ip: types.string(),
    malware_path: types.string(),
    operating_system: types.string(),
    top_logins: z.array(types.string()),
    top_passwords: z.array(types.string()),
    total_corporate_services: types.number(),
    total_user_services: types.number(),
    stealer_family: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "computer_name": "computerName",
      "date_compromised": "dateCompromised",
      "malware_path": "malwarePath",
      "operating_system": "operatingSystem",
      "top_logins": "topLogins",
      "top_passwords": "topPasswords",
      "total_corporate_services": "totalCorporateServices",
      "total_user_services": "totalUserServices",
      "stealer_family": "stealerFamily",
    });
  }),
);

export function stealerFromJSON(
  jsonString: string,
): SafeParseResult<Stealer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Stealer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Stealer' from JSON`,
  );
}

/** @internal */
export const PostV1SearchIntelligenceHudsonrockDataType2$inboundSchema:
  z.ZodMiniType<PostV1SearchIntelligenceHudsonrockDataType2, unknown> =
    openEnums.inboundSchema(PostV1SearchIntelligenceHudsonrockDataType2);

/** @internal */
export const PostV1SearchIntelligenceHudsonrockData2$inboundSchema:
  z.ZodMiniType<PostV1SearchIntelligenceHudsonrockData2, unknown> = z.object({
    message: types.string(),
    stealers: z.array(z.lazy(() => Stealer$inboundSchema)),
    type: PostV1SearchIntelligenceHudsonrockDataType2$inboundSchema,
  });

export function postV1SearchIntelligenceHudsonrockData2FromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1SearchIntelligenceHudsonrockData2,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1SearchIntelligenceHudsonrockData2$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV1SearchIntelligenceHudsonrockData2' from JSON`,
  );
}

/** @internal */
export const Application$inboundSchema: z.ZodMiniType<Application, unknown> = z
  .object({
    keyword: types.string(),
  });

export function applicationFromJSON(
  jsonString: string,
): SafeParseResult<Application, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Application$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Application' from JSON`,
  );
}

/** @internal */
export const EmployeesUrl$inboundSchema: z.ZodMiniType<EmployeesUrl, unknown> =
  z.object({
    occurrence: types.number(),
    type: types.string(),
    url: types.string(),
  });

export function employeesUrlFromJSON(
  jsonString: string,
): SafeParseResult<EmployeesUrl, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmployeesUrl$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmployeesUrl' from JSON`,
  );
}

/** @internal */
export const PostV1SearchIntelligenceHudsonrockDataData$inboundSchema:
  z.ZodMiniType<PostV1SearchIntelligenceHudsonrockDataData, unknown> = z.pipe(
    z.object({
      employees_urls: z.array(z.lazy(() => EmployeesUrl$inboundSchema)),
    }),
    z.transform((v) => {
      return remap$(v, {
        "employees_urls": "employeesUrls",
      });
    }),
  );

export function postV1SearchIntelligenceHudsonrockDataDataFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1SearchIntelligenceHudsonrockDataData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1SearchIntelligenceHudsonrockDataData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV1SearchIntelligenceHudsonrockDataData' from JSON`,
  );
}

/** @internal */
export const PostV1SearchIntelligenceHudsonrockStats$inboundSchema:
  z.ZodMiniType<PostV1SearchIntelligenceHudsonrockStats, unknown> = z.pipe(
    z.object({
      clients_count: z.array(types.number()),
      clients_urls: z.array(types.string()),
      employees_count: z.array(types.number()),
      employees_urls: z.array(types.string()),
      totalEmployees: types.number(),
      totalUsers: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "clients_count": "clientsCount",
        "clients_urls": "clientsUrls",
        "employees_count": "employeesCount",
        "employees_urls": "employeesUrls",
      });
    }),
  );

export function postV1SearchIntelligenceHudsonrockStatsFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1SearchIntelligenceHudsonrockStats,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1SearchIntelligenceHudsonrockStats$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV1SearchIntelligenceHudsonrockStats' from JSON`,
  );
}

/** @internal */
export const ThirdPartyDomain$inboundSchema: z.ZodMiniType<
  ThirdPartyDomain,
  unknown
> = z.object({
  domain: types.string(),
  occurrence: types.number(),
});

export function thirdPartyDomainFromJSON(
  jsonString: string,
): SafeParseResult<ThirdPartyDomain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThirdPartyDomain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThirdPartyDomain' from JSON`,
  );
}

/** @internal */
export const PostV1SearchIntelligenceHudsonrockDataType1$inboundSchema:
  z.ZodMiniType<PostV1SearchIntelligenceHudsonrockDataType1, unknown> =
    openEnums.inboundSchema(PostV1SearchIntelligenceHudsonrockDataType1);

/** @internal */
export const PostV1SearchIntelligenceHudsonrockList$inboundSchema:
  z.ZodMiniType<PostV1SearchIntelligenceHudsonrockList, unknown> = z.object({
    count: types.number(),
    name: types.string(),
  });

export function postV1SearchIntelligenceHudsonrockListFromJSON(
  jsonString: string,
): SafeParseResult<PostV1SearchIntelligenceHudsonrockList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1SearchIntelligenceHudsonrockList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1SearchIntelligenceHudsonrockList' from JSON`,
  );
}

/** @internal */
export const Antiviruses$inboundSchema: z.ZodMiniType<Antiviruses, unknown> = z
  .pipe(
    z.object({
      found: types.number(),
      free: types.string(),
      list: z.array(
        z.lazy(() => PostV1SearchIntelligenceHudsonrockList$inboundSchema),
      ),
      not_found: types.string(),
      total: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "not_found": "notFound",
      });
    }),
  );

export function antivirusesFromJSON(
  jsonString: string,
): SafeParseResult<Antiviruses, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Antiviruses$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Antiviruses' from JSON`,
  );
}

/** @internal */
export const EmployeePasswordsMedium$inboundSchema: z.ZodMiniType<
  EmployeePasswordsMedium,
  unknown
> = z.object({
  perc: types.number(),
  qty: types.number(),
});

export function employeePasswordsMediumFromJSON(
  jsonString: string,
): SafeParseResult<EmployeePasswordsMedium, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmployeePasswordsMedium$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmployeePasswordsMedium' from JSON`,
  );
}

/** @internal */
export const EmployeePasswordsStrong$inboundSchema: z.ZodMiniType<
  EmployeePasswordsStrong,
  unknown
> = z.object({
  perc: types.number(),
  qty: types.number(),
});

export function employeePasswordsStrongFromJSON(
  jsonString: string,
): SafeParseResult<EmployeePasswordsStrong, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmployeePasswordsStrong$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmployeePasswordsStrong' from JSON`,
  );
}

/** @internal */
export const EmployeePasswordsTooWeak$inboundSchema: z.ZodMiniType<
  EmployeePasswordsTooWeak,
  unknown
> = z.object({
  perc: types.number(),
  qty: types.number(),
});

export function employeePasswordsTooWeakFromJSON(
  jsonString: string,
): SafeParseResult<EmployeePasswordsTooWeak, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmployeePasswordsTooWeak$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmployeePasswordsTooWeak' from JSON`,
  );
}

/** @internal */
export const EmployeePasswordsWeak$inboundSchema: z.ZodMiniType<
  EmployeePasswordsWeak,
  unknown
> = z.object({
  perc: types.number(),
  qty: types.number(),
});

export function employeePasswordsWeakFromJSON(
  jsonString: string,
): SafeParseResult<EmployeePasswordsWeak, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmployeePasswordsWeak$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmployeePasswordsWeak' from JSON`,
  );
}

/** @internal */
export const EmployeePasswords$inboundSchema: z.ZodMiniType<
  EmployeePasswords,
  unknown
> = z.pipe(
  z.object({
    has_stats: types.boolean(),
    medium: z.lazy(() => EmployeePasswordsMedium$inboundSchema),
    strong: z.lazy(() => EmployeePasswordsStrong$inboundSchema),
    too_weak: z.lazy(() => EmployeePasswordsTooWeak$inboundSchema),
    totalPass: types.number(),
    weak: z.lazy(() => EmployeePasswordsWeak$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_stats": "hasStats",
      "too_weak": "tooWeak",
    });
  }),
);

export function employeePasswordsFromJSON(
  jsonString: string,
): SafeParseResult<EmployeePasswords, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmployeePasswords$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmployeePasswords' from JSON`,
  );
}

/** @internal */
export const StealerFamilies$inboundSchema: z.ZodMiniType<
  StealerFamilies,
  unknown
> = z.pipe(
  z.object({
    Acreed: types.number(),
    Atomic: types.number(),
    Azorult: types.number(),
    CRYPTBOT: types.number(),
    DarkCrystal: types.number(),
    Ficker: types.number(),
    "Generic Stealer": types.number(),
    Lumma: types.number(),
    Mystic: types.number(),
    Predator: types.number(),
    Raccoon: types.number(),
    RedLine: types.number(),
    StealC: types.number(),
    Taurus: types.number(),
    UNKNOWN: types.number(),
    Vidar: types.number(),
    last_counted: types.string(),
    total: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Acreed": "acreed",
      "Atomic": "atomic",
      "Azorult": "azorult",
      "CRYPTBOT": "cryptbot",
      "DarkCrystal": "darkCrystal",
      "Ficker": "ficker",
      "Generic Stealer": "genericStealer",
      "Lumma": "lumma",
      "Mystic": "mystic",
      "Predator": "predator",
      "Raccoon": "raccoon",
      "RedLine": "redLine",
      "StealC": "stealC",
      "Taurus": "taurus",
      "UNKNOWN": "unknown",
      "Vidar": "vidar",
      "last_counted": "lastCounted",
    });
  }),
);

export function stealerFamiliesFromJSON(
  jsonString: string,
): SafeParseResult<StealerFamilies, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StealerFamilies$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StealerFamilies' from JSON`,
  );
}

/** @internal */
export const UserPasswordsMedium$inboundSchema: z.ZodMiniType<
  UserPasswordsMedium,
  unknown
> = z.object({
  perc: types.number(),
  qty: types.number(),
});

export function userPasswordsMediumFromJSON(
  jsonString: string,
): SafeParseResult<UserPasswordsMedium, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserPasswordsMedium$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserPasswordsMedium' from JSON`,
  );
}

/** @internal */
export const UserPasswordsStrong$inboundSchema: z.ZodMiniType<
  UserPasswordsStrong,
  unknown
> = z.object({
  perc: types.number(),
  qty: types.number(),
});

export function userPasswordsStrongFromJSON(
  jsonString: string,
): SafeParseResult<UserPasswordsStrong, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserPasswordsStrong$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserPasswordsStrong' from JSON`,
  );
}

/** @internal */
export const UserPasswordsTooWeak$inboundSchema: z.ZodMiniType<
  UserPasswordsTooWeak,
  unknown
> = z.object({
  perc: types.number(),
  qty: types.number(),
});

export function userPasswordsTooWeakFromJSON(
  jsonString: string,
): SafeParseResult<UserPasswordsTooWeak, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserPasswordsTooWeak$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserPasswordsTooWeak' from JSON`,
  );
}

/** @internal */
export const UserPasswordsWeak$inboundSchema: z.ZodMiniType<
  UserPasswordsWeak,
  unknown
> = z.object({
  perc: types.number(),
  qty: types.number(),
});

export function userPasswordsWeakFromJSON(
  jsonString: string,
): SafeParseResult<UserPasswordsWeak, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserPasswordsWeak$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserPasswordsWeak' from JSON`,
  );
}

/** @internal */
export const UserPasswords$inboundSchema: z.ZodMiniType<
  UserPasswords,
  unknown
> = z.pipe(
  z.object({
    has_stats: types.boolean(),
    medium: z.lazy(() => UserPasswordsMedium$inboundSchema),
    strong: z.lazy(() => UserPasswordsStrong$inboundSchema),
    too_weak: z.lazy(() => UserPasswordsTooWeak$inboundSchema),
    totalPass: types.number(),
    weak: z.lazy(() => UserPasswordsWeak$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_stats": "hasStats",
      "too_weak": "tooWeak",
    });
  }),
);

export function userPasswordsFromJSON(
  jsonString: string,
): SafeParseResult<UserPasswords, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserPasswords$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserPasswords' from JSON`,
  );
}

/** @internal */
export const PostV1SearchIntelligenceHudsonrockData1$inboundSchema:
  z.ZodMiniType<PostV1SearchIntelligenceHudsonrockData1, unknown> = z.pipe(
    z.object({
      applications: z.array(z.lazy(() => Application$inboundSchema)),
      data: z.lazy(() =>
        PostV1SearchIntelligenceHudsonrockDataData$inboundSchema
      ),
      employees: types.number(),
      is_shopify: types.boolean(),
      last_employee_compromised: types.string(),
      last_user_compromised: types.string(),
      logo: types.string(),
      stats: z.lazy(() =>
        PostV1SearchIntelligenceHudsonrockStats$inboundSchema
      ),
      thirdPartyDomains: z.array(z.lazy(() => ThirdPartyDomain$inboundSchema)),
      third_parties: types.number(),
      total: types.number(),
      totalStealers: types.number(),
      totalUrls: types.number(),
      type: PostV1SearchIntelligenceHudsonrockDataType1$inboundSchema,
      users: types.number(),
      antiviruses: types.optional(z.lazy(() => Antiviruses$inboundSchema)),
      employeePasswords: types.optional(
        z.lazy(() => EmployeePasswords$inboundSchema),
      ),
      stealerFamilies: types.optional(
        z.lazy(() => StealerFamilies$inboundSchema),
      ),
      userPasswords: types.optional(z.lazy(() => UserPasswords$inboundSchema)),
    }),
    z.transform((v) => {
      return remap$(v, {
        "is_shopify": "isShopify",
        "last_employee_compromised": "lastEmployeeCompromised",
        "last_user_compromised": "lastUserCompromised",
        "third_parties": "thirdParties",
      });
    }),
  );

export function postV1SearchIntelligenceHudsonrockData1FromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1SearchIntelligenceHudsonrockData1,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1SearchIntelligenceHudsonrockData1$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV1SearchIntelligenceHudsonrockData1' from JSON`,
  );
}

/** @internal */
export const PostV1SearchIntelligenceHudsonrockDataUnion$inboundSchema:
  z.ZodMiniType<PostV1SearchIntelligenceHudsonrockDataUnion, unknown> =
    smartUnion([
      z.lazy(() => PostV1SearchIntelligenceHudsonrockData1$inboundSchema),
      z.lazy(() => PostV1SearchIntelligenceHudsonrockData2$inboundSchema),
    ]);

export function postV1SearchIntelligenceHudsonrockDataUnionFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1SearchIntelligenceHudsonrockDataUnion,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1SearchIntelligenceHudsonrockDataUnion$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV1SearchIntelligenceHudsonrockDataUnion' from JSON`,
  );
}

/** @internal */
export const PostV1SearchIntelligenceHudsonrockResponse$inboundSchema:
  z.ZodMiniType<PostV1SearchIntelligenceHudsonrockResponse, unknown> = z.object(
    {
      data: smartUnion([
        z.lazy(() => PostV1SearchIntelligenceHudsonrockData1$inboundSchema),
        z.lazy(() => PostV1SearchIntelligenceHudsonrockData2$inboundSchema),
      ]),
      success: types.boolean(),
      error: types.optional(types.string()),
    },
  );

export function postV1SearchIntelligenceHudsonrockResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1SearchIntelligenceHudsonrockResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1SearchIntelligenceHudsonrockResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV1SearchIntelligenceHudsonrockResponse' from JSON`,
  );
}
