/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostV1SearchIntelligenceEmailRequest = {
  query: string;
};

export type PostV1SearchIntelligenceEmailData = {
  aka: Array<string>;
  associates: Array<string>;
  children: number;
  currentAddress: string;
  emails: Array<string>;
  maritalStatus: string;
  name: string | null;
  pastAddresses: Array<string>;
  phones: Array<string>;
};

/**
 * Search successful
 */
export type PostV1SearchIntelligenceEmailResponse = {
  data: Array<PostV1SearchIntelligenceEmailData>;
  success: boolean;
  error?: string | undefined;
};

/** @internal */
export type PostV1SearchIntelligenceEmailRequest$Outbound = {
  query: string;
};

/** @internal */
export const PostV1SearchIntelligenceEmailRequest$outboundSchema: z.ZodMiniType<
  PostV1SearchIntelligenceEmailRequest$Outbound,
  PostV1SearchIntelligenceEmailRequest
> = z.object({
  query: z.string(),
});

export function postV1SearchIntelligenceEmailRequestToJSON(
  postV1SearchIntelligenceEmailRequest: PostV1SearchIntelligenceEmailRequest,
): string {
  return JSON.stringify(
    PostV1SearchIntelligenceEmailRequest$outboundSchema.parse(
      postV1SearchIntelligenceEmailRequest,
    ),
  );
}

/** @internal */
export const PostV1SearchIntelligenceEmailData$inboundSchema: z.ZodMiniType<
  PostV1SearchIntelligenceEmailData,
  unknown
> = z.object({
  aka: z.array(types.string()),
  associates: z.array(types.string()),
  children: types.number(),
  currentAddress: types.string(),
  emails: z.array(types.string()),
  maritalStatus: types.string(),
  name: types.nullable(types.string()),
  pastAddresses: z.array(types.string()),
  phones: z.array(types.string()),
});

export function postV1SearchIntelligenceEmailDataFromJSON(
  jsonString: string,
): SafeParseResult<PostV1SearchIntelligenceEmailData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1SearchIntelligenceEmailData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1SearchIntelligenceEmailData' from JSON`,
  );
}

/** @internal */
export const PostV1SearchIntelligenceEmailResponse$inboundSchema: z.ZodMiniType<
  PostV1SearchIntelligenceEmailResponse,
  unknown
> = z.object({
  data: z.array(z.lazy(() => PostV1SearchIntelligenceEmailData$inboundSchema)),
  success: types.boolean(),
  error: types.optional(types.string()),
});

export function postV1SearchIntelligenceEmailResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1SearchIntelligenceEmailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1SearchIntelligenceEmailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1SearchIntelligenceEmailResponse' from JSON`,
  );
}
