/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostV1OrganizationsByIdCreditsRequestBody = {
  creditsEach: number;
  recipientMemberIds: Array<string>;
};

export type PostV1OrganizationsByIdCreditsRequest = {
  id: string;
  body: PostV1OrganizationsByIdCreditsRequestBody;
};

/**
 * Credits sent.
 */
export type PostV1OrganizationsByIdCreditsResponse = {
  sent: number;
  success: boolean;
  totalCost: number;
};

/** @internal */
export type PostV1OrganizationsByIdCreditsRequestBody$Outbound = {
  creditsEach: number;
  recipientMemberIds: Array<string>;
};

/** @internal */
export const PostV1OrganizationsByIdCreditsRequestBody$outboundSchema:
  z.ZodMiniType<
    PostV1OrganizationsByIdCreditsRequestBody$Outbound,
    PostV1OrganizationsByIdCreditsRequestBody
  > = z.object({
    creditsEach: z.number(),
    recipientMemberIds: z.array(z.string()),
  });

export function postV1OrganizationsByIdCreditsRequestBodyToJSON(
  postV1OrganizationsByIdCreditsRequestBody:
    PostV1OrganizationsByIdCreditsRequestBody,
): string {
  return JSON.stringify(
    PostV1OrganizationsByIdCreditsRequestBody$outboundSchema.parse(
      postV1OrganizationsByIdCreditsRequestBody,
    ),
  );
}

/** @internal */
export type PostV1OrganizationsByIdCreditsRequest$Outbound = {
  id: string;
  body: PostV1OrganizationsByIdCreditsRequestBody$Outbound;
};

/** @internal */
export const PostV1OrganizationsByIdCreditsRequest$outboundSchema:
  z.ZodMiniType<
    PostV1OrganizationsByIdCreditsRequest$Outbound,
    PostV1OrganizationsByIdCreditsRequest
  > = z.object({
    id: z.string(),
    body: z.lazy(() =>
      PostV1OrganizationsByIdCreditsRequestBody$outboundSchema
    ),
  });

export function postV1OrganizationsByIdCreditsRequestToJSON(
  postV1OrganizationsByIdCreditsRequest: PostV1OrganizationsByIdCreditsRequest,
): string {
  return JSON.stringify(
    PostV1OrganizationsByIdCreditsRequest$outboundSchema.parse(
      postV1OrganizationsByIdCreditsRequest,
    ),
  );
}

/** @internal */
export const PostV1OrganizationsByIdCreditsResponse$inboundSchema:
  z.ZodMiniType<PostV1OrganizationsByIdCreditsResponse, unknown> = z.object({
    sent: types.number(),
    success: types.boolean(),
    totalCost: types.number(),
  });

export function postV1OrganizationsByIdCreditsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1OrganizationsByIdCreditsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1OrganizationsByIdCreditsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1OrganizationsByIdCreditsResponse' from JSON`,
  );
}
