/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const Model = {
  Default: "default",
  Enhanced: "enhanced",
} as const;
export type Model = ClosedEnum<typeof Model>;

export type PostV1SearchIntelligenceGeolocationRequest = {
  media: any;
  locationHint?: string | undefined;
  model?: Model | undefined;
};

/** @internal */
export const Model$outboundSchema: z.ZodMiniEnum<typeof Model> = z.enum(Model);

/** @internal */
export type PostV1SearchIntelligenceGeolocationRequest$Outbound = {
  media: any;
  locationHint?: string | undefined;
  model?: string | undefined;
};

/** @internal */
export const PostV1SearchIntelligenceGeolocationRequest$outboundSchema:
  z.ZodMiniType<
    PostV1SearchIntelligenceGeolocationRequest$Outbound,
    PostV1SearchIntelligenceGeolocationRequest
  > = z.object({
    media: z.any(),
    locationHint: z.optional(z.string()),
    model: z.optional(Model$outboundSchema),
  });

export function postV1SearchIntelligenceGeolocationRequestToJSON(
  postV1SearchIntelligenceGeolocationRequest:
    PostV1SearchIntelligenceGeolocationRequest,
): string {
  return JSON.stringify(
    PostV1SearchIntelligenceGeolocationRequest$outboundSchema.parse(
      postV1SearchIntelligenceGeolocationRequest,
    ),
  );
}
