/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type RequestBody2 = {
  bucket: "leaks.logs";
  systemId: string;
};

export const Bucket = {
  DarknetI2p: "darknet.i2p",
  DarknetTor: "darknet.tor",
  DocumentsPublicScihub: "documents.public.scihub",
  Dumpster: "dumpster",
  DumpsterWeb1: "dumpster.web.1",
  DumpsterWebSsn: "dumpster.web.ssn",
  LeaksLogs: "leaks.logs",
  LeaksPrivateGeneral: "leaks.private.general",
  LeaksPublicGeneral: "leaks.public.general",
  LeaksPublicWikileaks: "leaks.public.wikileaks",
  Pastes: "pastes",
  PatentUs: "patent.us",
  Usenet: "usenet",
  WebGovRu: "web.gov.ru",
  WebPublicAf: "web.public.af",
  WebPublicAms: "web.public.ams",
  WebPublicAq: "web.public.aq",
  WebPublicBusiness: "web.public.business",
  WebPublicCee: "web.public.cee",
  WebPublicCn: "web.public.cn",
  WebPublicCom: "web.public.com",
  WebPublicDe: "web.public.de",
  WebPublicEu: "web.public.eu",
  WebPublicGov: "web.public.gov",
  WebPublicInfo: "web.public.info",
  WebPublicKp: "web.public.kp",
  WebPublicMea: "web.public.mea",
  WebPublicMisc: "web.public.misc",
  WebPublicNet: "web.public.net",
  WebPublicNord: "web.public.nord",
  WebPublicOc: "web.public.oc",
  WebPublicOrg: "web.public.org",
  WebPublicPeer: "web.public.peer",
  WebPublicRu: "web.public.ru",
  WebPublicSocial: "web.public.social",
  WebPublicTech: "web.public.tech",
  WebPublicWe: "web.public.we",
  Whois: "whois",
} as const;
export type Bucket = ClosedEnum<typeof Bucket>;

export type RequestBody1 = {
  bucket: Bucket;
  storageId: string;
};

export type PostV1ToolsIntelxRequest = RequestBody1 | RequestBody2;

/**
 * Successful response
 */
export type PostV1ToolsIntelxResponse = {
  success: boolean;
  data?: string | undefined;
};

/** @internal */
export type RequestBody2$Outbound = {
  bucket: "leaks.logs";
  systemId: string;
};

/** @internal */
export const RequestBody2$outboundSchema: z.ZodMiniType<
  RequestBody2$Outbound,
  RequestBody2
> = z.object({
  bucket: z.literal("leaks.logs"),
  systemId: z.string(),
});

export function requestBody2ToJSON(requestBody2: RequestBody2): string {
  return JSON.stringify(RequestBody2$outboundSchema.parse(requestBody2));
}

/** @internal */
export const Bucket$outboundSchema: z.ZodMiniEnum<typeof Bucket> = z.enum(
  Bucket,
);

/** @internal */
export type RequestBody1$Outbound = {
  bucket: string;
  storageId: string;
};

/** @internal */
export const RequestBody1$outboundSchema: z.ZodMiniType<
  RequestBody1$Outbound,
  RequestBody1
> = z.object({
  bucket: Bucket$outboundSchema,
  storageId: z.string(),
});

export function requestBody1ToJSON(requestBody1: RequestBody1): string {
  return JSON.stringify(RequestBody1$outboundSchema.parse(requestBody1));
}

/** @internal */
export type PostV1ToolsIntelxRequest$Outbound =
  | RequestBody1$Outbound
  | RequestBody2$Outbound;

/** @internal */
export const PostV1ToolsIntelxRequest$outboundSchema: z.ZodMiniType<
  PostV1ToolsIntelxRequest$Outbound,
  PostV1ToolsIntelxRequest
> = smartUnion([
  z.lazy(() => RequestBody1$outboundSchema),
  z.lazy(() => RequestBody2$outboundSchema),
]);

export function postV1ToolsIntelxRequestToJSON(
  postV1ToolsIntelxRequest: PostV1ToolsIntelxRequest,
): string {
  return JSON.stringify(
    PostV1ToolsIntelxRequest$outboundSchema.parse(postV1ToolsIntelxRequest),
  );
}

/** @internal */
export const PostV1ToolsIntelxResponse$inboundSchema: z.ZodMiniType<
  PostV1ToolsIntelxResponse,
  unknown
> = z.object({
  success: types.boolean(),
  data: types.optional(types.string()),
});

export function postV1ToolsIntelxResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ToolsIntelxResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ToolsIntelxResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ToolsIntelxResponse' from JSON`,
  );
}
