/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type Options = {
  scanAll?: boolean | undefined;
  skipPing?: boolean | undefined;
  udp?: boolean | undefined;
};

export type ScanPortsRequest = {
  host: string;
  options: Options;
};

/** @internal */
export type Options$Outbound = {
  scanAll?: boolean | undefined;
  skipPing?: boolean | undefined;
  udp?: boolean | undefined;
};

/** @internal */
export const Options$outboundSchema: z.ZodMiniType<Options$Outbound, Options> =
  z.object({
    scanAll: z.optional(z.boolean()),
    skipPing: z.optional(z.boolean()),
    udp: z.optional(z.boolean()),
  });

export function optionsToJSON(options: Options): string {
  return JSON.stringify(Options$outboundSchema.parse(options));
}

/** @internal */
export type ScanPortsRequest$Outbound = {
  host: string;
  options: Options$Outbound;
};

/** @internal */
export const ScanPortsRequest$outboundSchema: z.ZodMiniType<
  ScanPortsRequest$Outbound,
  ScanPortsRequest
> = z.object({
  host: z.string(),
  options: z.lazy(() => Options$outboundSchema),
});

export function scanPortsRequestToJSON(
  scanPortsRequest: ScanPortsRequest,
): string {
  return JSON.stringify(
    ScanPortsRequest$outboundSchema.parse(scanPortsRequest),
  );
}
