/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SearchPersonRequest = {
  name: string;
  city?: string | undefined;
  state?: string | undefined;
};

export type SearchPersonLocal = {
  id: number;
  startDat: number | null;
  address: string | null;
  aka1fullname: string | null;
  aka2fullname: string | null;
  aka3fullname: string | null;
  alt1dob: string | null;
  alt2dob: string | null;
  alt3dob: string | null;
  city: string | null;
  countyName: string | null;
  dob: string | null;
  firstname: string;
  lastname: string;
  middlename: string | null;
  nameSuff: string | null;
  phone1: number | null;
  st: string | null;
  zip: number | null;
};

export type SearchPersonWeb = {
  aka: Array<string>;
  associates: Array<string>;
  children: number;
  currentAddress: string;
  emails: Array<string>;
  maritalStatus: string;
  name: string | null;
  pastAddresses: Array<string>;
  phones: Array<string>;
};

export type SearchPersonData = {
  local: Array<SearchPersonLocal>;
  web: Array<SearchPersonWeb>;
};

/**
 * Search successful
 */
export type SearchPersonResponse = {
  data: SearchPersonData;
  success: boolean;
  error?: string | undefined;
};

/** @internal */
export type SearchPersonRequest$Outbound = {
  name: string;
  city?: string | undefined;
  state?: string | undefined;
};

/** @internal */
export const SearchPersonRequest$outboundSchema: z.ZodMiniType<
  SearchPersonRequest$Outbound,
  SearchPersonRequest
> = z.object({
  name: z.string(),
  city: z.optional(z.string()),
  state: z.optional(z.string()),
});

export function searchPersonRequestToJSON(
  searchPersonRequest: SearchPersonRequest,
): string {
  return JSON.stringify(
    SearchPersonRequest$outboundSchema.parse(searchPersonRequest),
  );
}

/** @internal */
export const SearchPersonLocal$inboundSchema: z.ZodMiniType<
  SearchPersonLocal,
  unknown
> = z.pipe(
  z.object({
    ID: types.number(),
    StartDat: types.nullable(types.number()),
    address: types.nullable(types.string()),
    aka1fullname: types.nullable(types.string()),
    aka2fullname: types.nullable(types.string()),
    aka3fullname: types.nullable(types.string()),
    alt1dob: types.nullable(types.string()),
    alt2dob: types.nullable(types.string()),
    alt3dob: types.nullable(types.string()),
    city: types.nullable(types.string()),
    county_name: types.nullable(types.string()),
    dob: types.nullable(types.string()),
    firstname: types.string(),
    lastname: types.string(),
    middlename: types.nullable(types.string()),
    name_suff: types.nullable(types.string()),
    phone1: types.nullable(types.number()),
    st: types.nullable(types.string()),
    zip: types.nullable(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "ID": "id",
      "StartDat": "startDat",
      "county_name": "countyName",
      "name_suff": "nameSuff",
    });
  }),
);

export function searchPersonLocalFromJSON(
  jsonString: string,
): SafeParseResult<SearchPersonLocal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPersonLocal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPersonLocal' from JSON`,
  );
}

/** @internal */
export const SearchPersonWeb$inboundSchema: z.ZodMiniType<
  SearchPersonWeb,
  unknown
> = z.object({
  aka: z.array(types.string()),
  associates: z.array(types.string()),
  children: types.number(),
  currentAddress: types.string(),
  emails: z.array(types.string()),
  maritalStatus: types.string(),
  name: types.nullable(types.string()),
  pastAddresses: z.array(types.string()),
  phones: z.array(types.string()),
});

export function searchPersonWebFromJSON(
  jsonString: string,
): SafeParseResult<SearchPersonWeb, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPersonWeb$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPersonWeb' from JSON`,
  );
}

/** @internal */
export const SearchPersonData$inboundSchema: z.ZodMiniType<
  SearchPersonData,
  unknown
> = z.object({
  local: z.array(z.lazy(() => SearchPersonLocal$inboundSchema)),
  web: z.array(z.lazy(() => SearchPersonWeb$inboundSchema)),
});

export function searchPersonDataFromJSON(
  jsonString: string,
): SafeParseResult<SearchPersonData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPersonData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPersonData' from JSON`,
  );
}

/** @internal */
export const SearchPersonResponse$inboundSchema: z.ZodMiniType<
  SearchPersonResponse,
  unknown
> = z.object({
  data: z.lazy(() => SearchPersonData$inboundSchema),
  success: types.boolean(),
  error: types.optional(types.string()),
});

export function searchPersonResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchPersonResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPersonResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPersonResponse' from JSON`,
  );
}
