/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const SearchSeonType = {
  Bin: "bin",
  Email: "email",
  Ip: "ip",
  Phone: "phone",
} as const;
export type SearchSeonType = ClosedEnum<typeof SearchSeonType>;

export type SearchSeonRequest = {
  query: string;
  type: SearchSeonType;
};

export type JobsAndEmployment = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type MoneyTransferRemittance = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type ScienceAndEducation = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type BusinessTechnology = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type Business = {
  jobsAndEmployment?: JobsAndEmployment | undefined;
  moneyTransferRemittance?: MoneyTransferRemittance | undefined;
  scienceAndEducation?: ScienceAndEducation | undefined;
  technology?: BusinessTechnology | undefined;
  totalRegistration?: number | undefined;
};

export type AdultSites = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type BettingAndGaming = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type Dating = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type Delivery = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type Ecommerce = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type EmailService = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type Entertainment = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type HealthAndFitness = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type Messenger = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type RealEstate = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type SocialMedia = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type PersonalTechnology = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type Travel = {
  checked?: number | undefined;
  registered?: number | undefined;
};

export type Personal = {
  adultSites?: AdultSites | undefined;
  bettingAndGaming?: BettingAndGaming | undefined;
  dating?: Dating | undefined;
  delivery?: Delivery | undefined;
  ecommerce?: Ecommerce | undefined;
  emailService?: EmailService | undefined;
  entertainment?: Entertainment | undefined;
  healthAndFitness?: HealthAndFitness | undefined;
  messenger?: Messenger | undefined;
  realEstate?: RealEstate | undefined;
  socialMedia?: SocialMedia | undefined;
  technology?: PersonalTechnology | undefined;
  totalRegistration?: number | undefined;
  travel?: Travel | undefined;
};

export type AccountAggregates = {
  business?: Business | undefined;
  personal?: Personal | undefined;
  totalRegistration?: number | undefined;
};

export type AppliedRule = {
  id?: string | undefined;
  name?: string | undefined;
  operation?: string | undefined;
  score?: number | undefined;
};

export type Domain = {
  cityName?: string | undefined;
  companyName?: string | undefined;
  countryCode?: string | undefined;
  createDate?: string | undefined;
  domainName?: string | undefined;
  expiryDate?: string | undefined;
  fullName?: string | undefined;
  mailingAddress?: string | undefined;
  phoneNumber?: string | undefined;
  registrarName?: string | undefined;
  stateName?: string | undefined;
  updateDate?: string | undefined;
  zipCode?: string | undefined;
};

export type AssociatedDomainRegistrations = {
  domains?: Array<Domain> | undefined;
  exists?: boolean | undefined;
  firstRegistrationDate?: string | null | undefined;
  numberOfDomains?: number | undefined;
};

export type SearchSeonBreach = {
  date?: string | undefined;
  domain?: string | undefined;
  name?: string | undefined;
};

export type BreachDetails = {
  breaches?: Array<SearchSeonBreach> | undefined;
  firstBreach?: string | undefined;
  haveibeenpwnedListed?: boolean | undefined;
  lastBreach?: string | undefined;
  numberOfBreaches?: number | undefined;
};

export type CnamDetails = {
  name?: string | undefined;
};

export type EmailDetails = {
  deliverable?: boolean | undefined;
  earliestProfileDate?: string | undefined;
  emailRandomnessScore?: number | undefined;
  fullInbox?: boolean | undefined;
  minimumAgeMonths?: number | undefined;
  validFormat?: boolean | undefined;
};

export type EmailDomainDetails = {
  acceptAll?: boolean | undefined;
  created?: string | undefined;
  custom?: boolean | undefined;
  disposable?: boolean | undefined;
  dmarcEnforced?: boolean | undefined;
  domain?: string | undefined;
  expires?: string | undefined;
  free?: boolean | undefined;
  registered?: boolean | undefined;
  registeredTo?: string | undefined;
  registrarName?: string | undefined;
  spfStrict?: boolean | undefined;
  suspiciousTld?: boolean | undefined;
  tld?: string | undefined;
  updated?: string | undefined;
  validMx?: boolean | undefined;
  websiteExists?: boolean | undefined;
};

export type OriginalCarrier = {
  carrier?: string | undefined;
  carrierPrefix?: string | undefined;
};

export type PortedCarrier = {
  carrier?: string | undefined;
  carrierPrefix?: string | undefined;
};

export type RoamingCarrier = {
  carrier?: string | null | undefined;
  carrierCountry?: string | null | undefined;
  carrierPrefix?: string | null | undefined;
};

export type HlrDetails = {
  imsi?: string | undefined;
  originalCarrier?: OriginalCarrier | undefined;
  portedCarrier?: PortedCarrier | undefined;
  roamingCarrier?: RoamingCarrier | undefined;
  servingMsc?: string | null | undefined;
  status?: string | undefined;
};

export type SearchSeonPhone = number | string;

export type ProviderCarrierDetails = {
  carrier?: string | undefined;
  country?: string | undefined;
  disposable?: boolean | undefined;
  phoneIsValid?: boolean | undefined;
  type?: string | undefined;
};

export type RiskScores = {
  globalNetworkScore?: number | undefined;
};

export type SeonFraudHistory = {
  customerHits?: number | undefined;
  firstSeen?: number | null | undefined;
  flags?: Array<string> | undefined;
  fraudulentDeclineCustomerHits?: number | undefined;
  fraudulentDeclineFirstSeen?: number | null | undefined;
  fraudulentDeclineHits?: number | undefined;
  fraudulentDeclineLastSeen?: number | null | undefined;
  hits?: number | undefined;
  lastSeen?: number | null | undefined;
};

export type SearchSeonData = {
  accountAggregates?: AccountAggregates | undefined;
  appliedRules?: Array<AppliedRule> | undefined;
  associatedDomainRegistrations?: AssociatedDomainRegistrations | undefined;
  binBank?: string | undefined;
  binCard?: string | undefined;
  binCountry?: string | undefined;
  binCountryCode?: string | undefined;
  binLevel?: string | undefined;
  binPhone?: string | undefined;
  binType?: string | undefined;
  binValid?: boolean | undefined;
  binWebsite?: string | undefined;
  breachDetails?: BreachDetails | undefined;
  cardBin?: string | undefined;
  cardIssuer?: string | undefined;
  city?: string | undefined;
  cnamDetails?: CnamDetails | undefined;
  consumerPrivacyNetwork?: boolean | undefined;
  country?: string | undefined;
  dataCenterProxy?: boolean | undefined;
  email?: string | undefined;
  emailDetails?: EmailDetails | undefined;
  emailDomainDetails?: EmailDomainDetails | undefined;
  enterprisePrivateNetwork?: boolean | undefined;
  flags?: Array<{ [k: string]: any }> | undefined;
  harmful?: boolean | undefined;
  history?: { [k: string]: any } | undefined;
  hlrDetails?: HlrDetails | undefined;
  id?: string | undefined;
  ip?: string | undefined;
  ispName?: string | undefined;
  latitude?: number | undefined;
  longitude?: number | undefined;
  openPorts?: Array<number> | undefined;
  phone?: number | string | undefined;
  providerCarrierDetails?: ProviderCarrierDetails | undefined;
  providerName?: string | null | undefined;
  publicProxy?: boolean | undefined;
  residentialProxy?: boolean | undefined;
  riskScores?: RiskScores | undefined;
  score?: number | undefined;
  searchEngineSpider?: boolean | undefined;
  seonFraudHistory?: SeonFraudHistory | undefined;
  spamNumber?: number | undefined;
  spamUrls?: Array<string> | undefined;
  stateProv?: string | undefined;
  timezoneOffset?: string | undefined;
  tor?: boolean | undefined;
  type?: string | undefined;
  vpn?: boolean | undefined;
  webProxy?: boolean | undefined;
};

/**
 * Search successful
 */
export type SearchSeonResponse = {
  data: SearchSeonData;
  success: boolean;
  error?: string | undefined;
};

/** @internal */
export const SearchSeonType$outboundSchema: z.ZodMiniEnum<
  typeof SearchSeonType
> = z.enum(SearchSeonType);

/** @internal */
export type SearchSeonRequest$Outbound = {
  query: string;
  type: string;
};

/** @internal */
export const SearchSeonRequest$outboundSchema: z.ZodMiniType<
  SearchSeonRequest$Outbound,
  SearchSeonRequest
> = z.object({
  query: z.string(),
  type: SearchSeonType$outboundSchema,
});

export function searchSeonRequestToJSON(
  searchSeonRequest: SearchSeonRequest,
): string {
  return JSON.stringify(
    SearchSeonRequest$outboundSchema.parse(searchSeonRequest),
  );
}

/** @internal */
export const JobsAndEmployment$inboundSchema: z.ZodMiniType<
  JobsAndEmployment,
  unknown
> = z.object({
  checked: types.optional(types.number()),
  registered: types.optional(types.number()),
});

export function jobsAndEmploymentFromJSON(
  jsonString: string,
): SafeParseResult<JobsAndEmployment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JobsAndEmployment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JobsAndEmployment' from JSON`,
  );
}

/** @internal */
export const MoneyTransferRemittance$inboundSchema: z.ZodMiniType<
  MoneyTransferRemittance,
  unknown
> = z.object({
  checked: types.optional(types.number()),
  registered: types.optional(types.number()),
});

export function moneyTransferRemittanceFromJSON(
  jsonString: string,
): SafeParseResult<MoneyTransferRemittance, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MoneyTransferRemittance$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MoneyTransferRemittance' from JSON`,
  );
}

/** @internal */
export const ScienceAndEducation$inboundSchema: z.ZodMiniType<
  ScienceAndEducation,
  unknown
> = z.object({
  checked: types.optional(types.number()),
  registered: types.optional(types.number()),
});

export function scienceAndEducationFromJSON(
  jsonString: string,
): SafeParseResult<ScienceAndEducation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScienceAndEducation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScienceAndEducation' from JSON`,
  );
}

/** @internal */
export const BusinessTechnology$inboundSchema: z.ZodMiniType<
  BusinessTechnology,
  unknown
> = z.object({
  checked: types.optional(types.number()),
  registered: types.optional(types.number()),
});

export function businessTechnologyFromJSON(
  jsonString: string,
): SafeParseResult<BusinessTechnology, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BusinessTechnology$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BusinessTechnology' from JSON`,
  );
}

/** @internal */
export const Business$inboundSchema: z.ZodMiniType<Business, unknown> = z.pipe(
  z.object({
    jobs_and_employment: types.optional(z.lazy(() =>
      JobsAndEmployment$inboundSchema
    )),
    money_transfer_remittance: types.optional(z.lazy(() =>
      MoneyTransferRemittance$inboundSchema
    )),
    science_and_education: types.optional(z.lazy(() =>
      ScienceAndEducation$inboundSchema
    )),
    technology: types.optional(z.lazy(() => BusinessTechnology$inboundSchema)),
    total_registration: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "jobs_and_employment": "jobsAndEmployment",
      "money_transfer_remittance": "moneyTransferRemittance",
      "science_and_education": "scienceAndEducation",
      "total_registration": "totalRegistration",
    });
  }),
);

export function businessFromJSON(
  jsonString: string,
): SafeParseResult<Business, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Business$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Business' from JSON`,
  );
}

/** @internal */
export const AdultSites$inboundSchema: z.ZodMiniType<AdultSites, unknown> = z
  .object({
    checked: types.optional(types.number()),
    registered: types.optional(types.number()),
  });

export function adultSitesFromJSON(
  jsonString: string,
): SafeParseResult<AdultSites, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdultSites$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdultSites' from JSON`,
  );
}

/** @internal */
export const BettingAndGaming$inboundSchema: z.ZodMiniType<
  BettingAndGaming,
  unknown
> = z.object({
  checked: types.optional(types.number()),
  registered: types.optional(types.number()),
});

export function bettingAndGamingFromJSON(
  jsonString: string,
): SafeParseResult<BettingAndGaming, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BettingAndGaming$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BettingAndGaming' from JSON`,
  );
}

/** @internal */
export const Dating$inboundSchema: z.ZodMiniType<Dating, unknown> = z.object({
  checked: types.optional(types.number()),
  registered: types.optional(types.number()),
});

export function datingFromJSON(
  jsonString: string,
): SafeParseResult<Dating, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Dating$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Dating' from JSON`,
  );
}

/** @internal */
export const Delivery$inboundSchema: z.ZodMiniType<Delivery, unknown> = z
  .object({
    checked: types.optional(types.number()),
    registered: types.optional(types.number()),
  });

export function deliveryFromJSON(
  jsonString: string,
): SafeParseResult<Delivery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Delivery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Delivery' from JSON`,
  );
}

/** @internal */
export const Ecommerce$inboundSchema: z.ZodMiniType<Ecommerce, unknown> = z
  .object({
    checked: types.optional(types.number()),
    registered: types.optional(types.number()),
  });

export function ecommerceFromJSON(
  jsonString: string,
): SafeParseResult<Ecommerce, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ecommerce$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ecommerce' from JSON`,
  );
}

/** @internal */
export const EmailService$inboundSchema: z.ZodMiniType<EmailService, unknown> =
  z.object({
    checked: types.optional(types.number()),
    registered: types.optional(types.number()),
  });

export function emailServiceFromJSON(
  jsonString: string,
): SafeParseResult<EmailService, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailService$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailService' from JSON`,
  );
}

/** @internal */
export const Entertainment$inboundSchema: z.ZodMiniType<
  Entertainment,
  unknown
> = z.object({
  checked: types.optional(types.number()),
  registered: types.optional(types.number()),
});

export function entertainmentFromJSON(
  jsonString: string,
): SafeParseResult<Entertainment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Entertainment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Entertainment' from JSON`,
  );
}

/** @internal */
export const HealthAndFitness$inboundSchema: z.ZodMiniType<
  HealthAndFitness,
  unknown
> = z.object({
  checked: types.optional(types.number()),
  registered: types.optional(types.number()),
});

export function healthAndFitnessFromJSON(
  jsonString: string,
): SafeParseResult<HealthAndFitness, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HealthAndFitness$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HealthAndFitness' from JSON`,
  );
}

/** @internal */
export const Messenger$inboundSchema: z.ZodMiniType<Messenger, unknown> = z
  .object({
    checked: types.optional(types.number()),
    registered: types.optional(types.number()),
  });

export function messengerFromJSON(
  jsonString: string,
): SafeParseResult<Messenger, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Messenger$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Messenger' from JSON`,
  );
}

/** @internal */
export const RealEstate$inboundSchema: z.ZodMiniType<RealEstate, unknown> = z
  .object({
    checked: types.optional(types.number()),
    registered: types.optional(types.number()),
  });

export function realEstateFromJSON(
  jsonString: string,
): SafeParseResult<RealEstate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RealEstate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RealEstate' from JSON`,
  );
}

/** @internal */
export const SocialMedia$inboundSchema: z.ZodMiniType<SocialMedia, unknown> = z
  .object({
    checked: types.optional(types.number()),
    registered: types.optional(types.number()),
  });

export function socialMediaFromJSON(
  jsonString: string,
): SafeParseResult<SocialMedia, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SocialMedia$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SocialMedia' from JSON`,
  );
}

/** @internal */
export const PersonalTechnology$inboundSchema: z.ZodMiniType<
  PersonalTechnology,
  unknown
> = z.object({
  checked: types.optional(types.number()),
  registered: types.optional(types.number()),
});

export function personalTechnologyFromJSON(
  jsonString: string,
): SafeParseResult<PersonalTechnology, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PersonalTechnology$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PersonalTechnology' from JSON`,
  );
}

/** @internal */
export const Travel$inboundSchema: z.ZodMiniType<Travel, unknown> = z.object({
  checked: types.optional(types.number()),
  registered: types.optional(types.number()),
});

export function travelFromJSON(
  jsonString: string,
): SafeParseResult<Travel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Travel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Travel' from JSON`,
  );
}

/** @internal */
export const Personal$inboundSchema: z.ZodMiniType<Personal, unknown> = z.pipe(
  z.object({
    adult_sites: types.optional(z.lazy(() => AdultSites$inboundSchema)),
    betting_and_gaming: types.optional(z.lazy(() =>
      BettingAndGaming$inboundSchema
    )),
    dating: types.optional(z.lazy(() => Dating$inboundSchema)),
    delivery: types.optional(z.lazy(() => Delivery$inboundSchema)),
    ecommerce: types.optional(z.lazy(() => Ecommerce$inboundSchema)),
    email_service: types.optional(z.lazy(() => EmailService$inboundSchema)),
    entertainment: types.optional(z.lazy(() => Entertainment$inboundSchema)),
    health_and_fitness: types.optional(z.lazy(() =>
      HealthAndFitness$inboundSchema
    )),
    messenger: types.optional(z.lazy(() => Messenger$inboundSchema)),
    real_estate: types.optional(z.lazy(() => RealEstate$inboundSchema)),
    social_media: types.optional(z.lazy(() => SocialMedia$inboundSchema)),
    technology: types.optional(z.lazy(() => PersonalTechnology$inboundSchema)),
    total_registration: types.optional(types.number()),
    travel: types.optional(z.lazy(() => Travel$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "adult_sites": "adultSites",
      "betting_and_gaming": "bettingAndGaming",
      "email_service": "emailService",
      "health_and_fitness": "healthAndFitness",
      "real_estate": "realEstate",
      "social_media": "socialMedia",
      "total_registration": "totalRegistration",
    });
  }),
);

export function personalFromJSON(
  jsonString: string,
): SafeParseResult<Personal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Personal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Personal' from JSON`,
  );
}

/** @internal */
export const AccountAggregates$inboundSchema: z.ZodMiniType<
  AccountAggregates,
  unknown
> = z.pipe(
  z.object({
    business: types.optional(z.lazy(() => Business$inboundSchema)),
    personal: types.optional(z.lazy(() => Personal$inboundSchema)),
    total_registration: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_registration": "totalRegistration",
    });
  }),
);

export function accountAggregatesFromJSON(
  jsonString: string,
): SafeParseResult<AccountAggregates, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountAggregates$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountAggregates' from JSON`,
  );
}

/** @internal */
export const AppliedRule$inboundSchema: z.ZodMiniType<AppliedRule, unknown> = z
  .object({
    id: types.optional(types.string()),
    name: types.optional(types.string()),
    operation: types.optional(types.string()),
    score: types.optional(types.number()),
  });

export function appliedRuleFromJSON(
  jsonString: string,
): SafeParseResult<AppliedRule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppliedRule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppliedRule' from JSON`,
  );
}

/** @internal */
export const Domain$inboundSchema: z.ZodMiniType<Domain, unknown> = z.pipe(
  z.object({
    city_name: types.optional(types.string()),
    company_name: types.optional(types.string()),
    country_code: types.optional(types.string()),
    create_date: types.optional(types.string()),
    domain_name: types.optional(types.string()),
    expiry_date: types.optional(types.string()),
    full_name: types.optional(types.string()),
    mailing_address: types.optional(types.string()),
    phone_number: types.optional(types.string()),
    registrar_name: types.optional(types.string()),
    state_name: types.optional(types.string()),
    update_date: types.optional(types.string()),
    zip_code: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "city_name": "cityName",
      "company_name": "companyName",
      "country_code": "countryCode",
      "create_date": "createDate",
      "domain_name": "domainName",
      "expiry_date": "expiryDate",
      "full_name": "fullName",
      "mailing_address": "mailingAddress",
      "phone_number": "phoneNumber",
      "registrar_name": "registrarName",
      "state_name": "stateName",
      "update_date": "updateDate",
      "zip_code": "zipCode",
    });
  }),
);

export function domainFromJSON(
  jsonString: string,
): SafeParseResult<Domain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Domain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Domain' from JSON`,
  );
}

/** @internal */
export const AssociatedDomainRegistrations$inboundSchema: z.ZodMiniType<
  AssociatedDomainRegistrations,
  unknown
> = z.pipe(
  z.object({
    domains: types.optional(z.array(z.lazy(() => Domain$inboundSchema))),
    exists: types.optional(types.boolean()),
    first_registration_date: z.optional(z.nullable(types.string())),
    number_of_domains: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "first_registration_date": "firstRegistrationDate",
      "number_of_domains": "numberOfDomains",
    });
  }),
);

export function associatedDomainRegistrationsFromJSON(
  jsonString: string,
): SafeParseResult<AssociatedDomainRegistrations, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssociatedDomainRegistrations$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssociatedDomainRegistrations' from JSON`,
  );
}

/** @internal */
export const SearchSeonBreach$inboundSchema: z.ZodMiniType<
  SearchSeonBreach,
  unknown
> = z.object({
  date: types.optional(types.string()),
  domain: types.optional(types.string()),
  name: types.optional(types.string()),
});

export function searchSeonBreachFromJSON(
  jsonString: string,
): SafeParseResult<SearchSeonBreach, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchSeonBreach$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchSeonBreach' from JSON`,
  );
}

/** @internal */
export const BreachDetails$inboundSchema: z.ZodMiniType<
  BreachDetails,
  unknown
> = z.pipe(
  z.object({
    breaches: types.optional(
      z.array(z.lazy(() => SearchSeonBreach$inboundSchema)),
    ),
    first_breach: types.optional(types.string()),
    haveibeenpwned_listed: types.optional(types.boolean()),
    last_breach: types.optional(types.string()),
    number_of_breaches: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "first_breach": "firstBreach",
      "haveibeenpwned_listed": "haveibeenpwnedListed",
      "last_breach": "lastBreach",
      "number_of_breaches": "numberOfBreaches",
    });
  }),
);

export function breachDetailsFromJSON(
  jsonString: string,
): SafeParseResult<BreachDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BreachDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BreachDetails' from JSON`,
  );
}

/** @internal */
export const CnamDetails$inboundSchema: z.ZodMiniType<CnamDetails, unknown> = z
  .object({
    name: types.optional(types.string()),
  });

export function cnamDetailsFromJSON(
  jsonString: string,
): SafeParseResult<CnamDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CnamDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CnamDetails' from JSON`,
  );
}

/** @internal */
export const EmailDetails$inboundSchema: z.ZodMiniType<EmailDetails, unknown> =
  z.pipe(
    z.object({
      deliverable: types.optional(types.boolean()),
      earliest_profile_date: types.optional(types.string()),
      email_randomness_score: types.optional(types.number()),
      full_inbox: types.optional(types.boolean()),
      minimum_age_months: types.optional(types.number()),
      valid_format: types.optional(types.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "earliest_profile_date": "earliestProfileDate",
        "email_randomness_score": "emailRandomnessScore",
        "full_inbox": "fullInbox",
        "minimum_age_months": "minimumAgeMonths",
        "valid_format": "validFormat",
      });
    }),
  );

export function emailDetailsFromJSON(
  jsonString: string,
): SafeParseResult<EmailDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailDetails' from JSON`,
  );
}

/** @internal */
export const EmailDomainDetails$inboundSchema: z.ZodMiniType<
  EmailDomainDetails,
  unknown
> = z.pipe(
  z.object({
    accept_all: types.optional(types.boolean()),
    created: types.optional(types.string()),
    custom: types.optional(types.boolean()),
    disposable: types.optional(types.boolean()),
    dmarc_enforced: types.optional(types.boolean()),
    domain: types.optional(types.string()),
    expires: types.optional(types.string()),
    free: types.optional(types.boolean()),
    registered: types.optional(types.boolean()),
    registered_to: types.optional(types.string()),
    registrar_name: types.optional(types.string()),
    spf_strict: types.optional(types.boolean()),
    suspicious_tld: types.optional(types.boolean()),
    tld: types.optional(types.string()),
    updated: types.optional(types.string()),
    valid_mx: types.optional(types.boolean()),
    website_exists: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "accept_all": "acceptAll",
      "dmarc_enforced": "dmarcEnforced",
      "registered_to": "registeredTo",
      "registrar_name": "registrarName",
      "spf_strict": "spfStrict",
      "suspicious_tld": "suspiciousTld",
      "valid_mx": "validMx",
      "website_exists": "websiteExists",
    });
  }),
);

export function emailDomainDetailsFromJSON(
  jsonString: string,
): SafeParseResult<EmailDomainDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailDomainDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailDomainDetails' from JSON`,
  );
}

/** @internal */
export const OriginalCarrier$inboundSchema: z.ZodMiniType<
  OriginalCarrier,
  unknown
> = z.pipe(
  z.object({
    carrier: types.optional(types.string()),
    carrier_prefix: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "carrier_prefix": "carrierPrefix",
    });
  }),
);

export function originalCarrierFromJSON(
  jsonString: string,
): SafeParseResult<OriginalCarrier, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OriginalCarrier$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OriginalCarrier' from JSON`,
  );
}

/** @internal */
export const PortedCarrier$inboundSchema: z.ZodMiniType<
  PortedCarrier,
  unknown
> = z.pipe(
  z.object({
    carrier: types.optional(types.string()),
    carrier_prefix: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "carrier_prefix": "carrierPrefix",
    });
  }),
);

export function portedCarrierFromJSON(
  jsonString: string,
): SafeParseResult<PortedCarrier, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PortedCarrier$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PortedCarrier' from JSON`,
  );
}

/** @internal */
export const RoamingCarrier$inboundSchema: z.ZodMiniType<
  RoamingCarrier,
  unknown
> = z.pipe(
  z.object({
    carrier: z.optional(z.nullable(types.string())),
    carrier_country: z.optional(z.nullable(types.string())),
    carrier_prefix: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "carrier_country": "carrierCountry",
      "carrier_prefix": "carrierPrefix",
    });
  }),
);

export function roamingCarrierFromJSON(
  jsonString: string,
): SafeParseResult<RoamingCarrier, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RoamingCarrier$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RoamingCarrier' from JSON`,
  );
}

/** @internal */
export const HlrDetails$inboundSchema: z.ZodMiniType<HlrDetails, unknown> = z
  .pipe(
    z.object({
      imsi: types.optional(types.string()),
      original_carrier: types.optional(
        z.lazy(() => OriginalCarrier$inboundSchema),
      ),
      ported_carrier: types.optional(z.lazy(() => PortedCarrier$inboundSchema)),
      roaming_carrier: types.optional(
        z.lazy(() => RoamingCarrier$inboundSchema),
      ),
      serving_msc: z.optional(z.nullable(types.string())),
      status: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "original_carrier": "originalCarrier",
        "ported_carrier": "portedCarrier",
        "roaming_carrier": "roamingCarrier",
        "serving_msc": "servingMsc",
      });
    }),
  );

export function hlrDetailsFromJSON(
  jsonString: string,
): SafeParseResult<HlrDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HlrDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HlrDetails' from JSON`,
  );
}

/** @internal */
export const SearchSeonPhone$inboundSchema: z.ZodMiniType<
  SearchSeonPhone,
  unknown
> = smartUnion([types.number(), types.string()]);

export function searchSeonPhoneFromJSON(
  jsonString: string,
): SafeParseResult<SearchSeonPhone, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchSeonPhone$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchSeonPhone' from JSON`,
  );
}

/** @internal */
export const ProviderCarrierDetails$inboundSchema: z.ZodMiniType<
  ProviderCarrierDetails,
  unknown
> = z.pipe(
  z.object({
    carrier: types.optional(types.string()),
    country: types.optional(types.string()),
    disposable: types.optional(types.boolean()),
    phone_is_valid: types.optional(types.boolean()),
    type: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "phone_is_valid": "phoneIsValid",
    });
  }),
);

export function providerCarrierDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ProviderCarrierDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProviderCarrierDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProviderCarrierDetails' from JSON`,
  );
}

/** @internal */
export const RiskScores$inboundSchema: z.ZodMiniType<RiskScores, unknown> = z
  .pipe(
    z.object({
      global_network_score: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "global_network_score": "globalNetworkScore",
      });
    }),
  );

export function riskScoresFromJSON(
  jsonString: string,
): SafeParseResult<RiskScores, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RiskScores$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RiskScores' from JSON`,
  );
}

/** @internal */
export const SeonFraudHistory$inboundSchema: z.ZodMiniType<
  SeonFraudHistory,
  unknown
> = z.pipe(
  z.object({
    customer_hits: types.optional(types.number()),
    first_seen: z.optional(z.nullable(types.number())),
    flags: types.optional(z.array(types.string())),
    fraudulent_decline_customer_hits: types.optional(types.number()),
    fraudulent_decline_first_seen: z.optional(z.nullable(types.number())),
    fraudulent_decline_hits: types.optional(types.number()),
    fraudulent_decline_last_seen: z.optional(z.nullable(types.number())),
    hits: types.optional(types.number()),
    last_seen: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "customer_hits": "customerHits",
      "first_seen": "firstSeen",
      "fraudulent_decline_customer_hits": "fraudulentDeclineCustomerHits",
      "fraudulent_decline_first_seen": "fraudulentDeclineFirstSeen",
      "fraudulent_decline_hits": "fraudulentDeclineHits",
      "fraudulent_decline_last_seen": "fraudulentDeclineLastSeen",
      "last_seen": "lastSeen",
    });
  }),
);

export function seonFraudHistoryFromJSON(
  jsonString: string,
): SafeParseResult<SeonFraudHistory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SeonFraudHistory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SeonFraudHistory' from JSON`,
  );
}

/** @internal */
export const SearchSeonData$inboundSchema: z.ZodMiniType<
  SearchSeonData,
  unknown
> = z.pipe(
  z.object({
    account_aggregates: types.optional(
      z.lazy(() => AccountAggregates$inboundSchema),
    ),
    applied_rules: types.optional(
      z.array(z.lazy(() => AppliedRule$inboundSchema)),
    ),
    associated_domain_registrations: types.optional(
      z.lazy(() => AssociatedDomainRegistrations$inboundSchema),
    ),
    bin_bank: types.optional(types.string()),
    bin_card: types.optional(types.string()),
    bin_country: types.optional(types.string()),
    bin_country_code: types.optional(types.string()),
    bin_level: types.optional(types.string()),
    bin_phone: types.optional(types.string()),
    bin_type: types.optional(types.string()),
    bin_valid: types.optional(types.boolean()),
    bin_website: types.optional(types.string()),
    breach_details: types.optional(z.lazy(() => BreachDetails$inboundSchema)),
    card_bin: types.optional(types.string()),
    card_issuer: types.optional(types.string()),
    city: types.optional(types.string()),
    cnam_details: types.optional(z.lazy(() => CnamDetails$inboundSchema)),
    consumer_privacy_network: types.optional(types.boolean()),
    country: types.optional(types.string()),
    data_center_proxy: types.optional(types.boolean()),
    email: types.optional(types.string()),
    email_details: types.optional(z.lazy(() => EmailDetails$inboundSchema)),
    email_domain_details: types.optional(
      z.lazy(() => EmailDomainDetails$inboundSchema),
    ),
    enterprise_private_network: types.optional(types.boolean()),
    flags: types.optional(z.array(z.record(z.string(), z.any()))),
    harmful: types.optional(types.boolean()),
    history: types.optional(z.record(z.string(), z.any())),
    hlr_details: types.optional(z.lazy(() => HlrDetails$inboundSchema)),
    id: types.optional(types.string()),
    ip: types.optional(types.string()),
    isp_name: types.optional(types.string()),
    latitude: types.optional(types.number()),
    longitude: types.optional(types.number()),
    open_ports: types.optional(z.array(types.number())),
    phone: types.optional(smartUnion([types.number(), types.string()])),
    provider_carrier_details: types.optional(
      z.lazy(() => ProviderCarrierDetails$inboundSchema),
    ),
    provider_name: z.optional(z.nullable(types.string())),
    public_proxy: types.optional(types.boolean()),
    residential_proxy: types.optional(types.boolean()),
    risk_scores: types.optional(z.lazy(() => RiskScores$inboundSchema)),
    score: types.optional(types.number()),
    search_engine_spider: types.optional(types.boolean()),
    seon_fraud_history: types.optional(
      z.lazy(() => SeonFraudHistory$inboundSchema),
    ),
    spam_number: types.optional(types.number()),
    spam_urls: types.optional(z.array(types.string())),
    state_prov: types.optional(types.string()),
    timezone_offset: types.optional(types.string()),
    tor: types.optional(types.boolean()),
    type: types.optional(types.string()),
    vpn: types.optional(types.boolean()),
    web_proxy: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "account_aggregates": "accountAggregates",
      "applied_rules": "appliedRules",
      "associated_domain_registrations": "associatedDomainRegistrations",
      "bin_bank": "binBank",
      "bin_card": "binCard",
      "bin_country": "binCountry",
      "bin_country_code": "binCountryCode",
      "bin_level": "binLevel",
      "bin_phone": "binPhone",
      "bin_type": "binType",
      "bin_valid": "binValid",
      "bin_website": "binWebsite",
      "breach_details": "breachDetails",
      "card_bin": "cardBin",
      "card_issuer": "cardIssuer",
      "cnam_details": "cnamDetails",
      "consumer_privacy_network": "consumerPrivacyNetwork",
      "data_center_proxy": "dataCenterProxy",
      "email_details": "emailDetails",
      "email_domain_details": "emailDomainDetails",
      "enterprise_private_network": "enterprisePrivateNetwork",
      "hlr_details": "hlrDetails",
      "isp_name": "ispName",
      "open_ports": "openPorts",
      "provider_carrier_details": "providerCarrierDetails",
      "provider_name": "providerName",
      "public_proxy": "publicProxy",
      "residential_proxy": "residentialProxy",
      "risk_scores": "riskScores",
      "search_engine_spider": "searchEngineSpider",
      "seon_fraud_history": "seonFraudHistory",
      "spam_number": "spamNumber",
      "spam_urls": "spamUrls",
      "state_prov": "stateProv",
      "timezone_offset": "timezoneOffset",
      "web_proxy": "webProxy",
    });
  }),
);

export function searchSeonDataFromJSON(
  jsonString: string,
): SafeParseResult<SearchSeonData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchSeonData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchSeonData' from JSON`,
  );
}

/** @internal */
export const SearchSeonResponse$inboundSchema: z.ZodMiniType<
  SearchSeonResponse,
  unknown
> = z.object({
  data: z.lazy(() => SearchSeonData$inboundSchema),
  success: types.boolean(),
  error: types.optional(types.string()),
});

export function searchSeonResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchSeonResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchSeonResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchSeonResponse' from JSON`,
  );
}
