/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SearchGithubRequest = {
  query: string;
};

export type SearchGithubData = {
  avatarUrl: string | null;
  bio: string | null;
  commitEmails: { [k: string]: Array<string> };
  commitRepoCount: number;
  commits: number;
  company: string | null;
  createdAt: string | null;
  followers: number;
  following: number;
  id: number;
  lastSeen: string | null;
  location: string | null;
  name: string | null;
  publicGists: number;
  publicRepos: number;
  username: string;
};

/**
 * Search successful
 */
export type SearchGithubResponse = {
  data: SearchGithubData;
  success: boolean;
  error?: string | undefined;
};

/** @internal */
export type SearchGithubRequest$Outbound = {
  query: string;
};

/** @internal */
export const SearchGithubRequest$outboundSchema: z.ZodMiniType<
  SearchGithubRequest$Outbound,
  SearchGithubRequest
> = z.object({
  query: z.string(),
});

export function searchGithubRequestToJSON(
  searchGithubRequest: SearchGithubRequest,
): string {
  return JSON.stringify(
    SearchGithubRequest$outboundSchema.parse(searchGithubRequest),
  );
}

/** @internal */
export const SearchGithubData$inboundSchema: z.ZodMiniType<
  SearchGithubData,
  unknown
> = z.pipe(
  z.object({
    avatar_url: types.nullable(types.string()),
    bio: types.nullable(types.string()),
    commitEmails: z.record(z.string(), z.array(types.string())),
    commitRepoCount: types.number(),
    commits: types.number(),
    company: types.nullable(types.string()),
    createdAt: types.nullable(types.string()),
    followers: types.number(),
    following: types.number(),
    id: types.number(),
    lastSeen: types.nullable(types.string()),
    location: types.nullable(types.string()),
    name: types.nullable(types.string()),
    public_gists: types.number(),
    public_repos: types.number(),
    username: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "avatar_url": "avatarUrl",
      "public_gists": "publicGists",
      "public_repos": "publicRepos",
    });
  }),
);

export function searchGithubDataFromJSON(
  jsonString: string,
): SafeParseResult<SearchGithubData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchGithubData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchGithubData' from JSON`,
  );
}

/** @internal */
export const SearchGithubResponse$inboundSchema: z.ZodMiniType<
  SearchGithubResponse,
  unknown
> = z.object({
  data: z.lazy(() => SearchGithubData$inboundSchema),
  success: types.boolean(),
  error: types.optional(types.string()),
});

export function searchGithubResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchGithubResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchGithubResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchGithubResponse' from JSON`,
  );
}
