/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SearchEmailRequest = {
  query: string;
};

export type SearchEmailData = {
  aka: Array<string>;
  associates: Array<string>;
  children: number;
  currentAddress: string;
  emails: Array<string>;
  maritalStatus: string;
  name: string | null;
  pastAddresses: Array<string>;
  phones: Array<string>;
};

/**
 * Search successful
 */
export type SearchEmailResponse = {
  data: Array<SearchEmailData>;
  success: boolean;
  error?: string | undefined;
};

/** @internal */
export type SearchEmailRequest$Outbound = {
  query: string;
};

/** @internal */
export const SearchEmailRequest$outboundSchema: z.ZodMiniType<
  SearchEmailRequest$Outbound,
  SearchEmailRequest
> = z.object({
  query: z.string(),
});

export function searchEmailRequestToJSON(
  searchEmailRequest: SearchEmailRequest,
): string {
  return JSON.stringify(
    SearchEmailRequest$outboundSchema.parse(searchEmailRequest),
  );
}

/** @internal */
export const SearchEmailData$inboundSchema: z.ZodMiniType<
  SearchEmailData,
  unknown
> = z.object({
  aka: z.array(types.string()),
  associates: z.array(types.string()),
  children: types.number(),
  currentAddress: types.string(),
  emails: z.array(types.string()),
  maritalStatus: types.string(),
  name: types.nullable(types.string()),
  pastAddresses: z.array(types.string()),
  phones: z.array(types.string()),
});

export function searchEmailDataFromJSON(
  jsonString: string,
): SafeParseResult<SearchEmailData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchEmailData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchEmailData' from JSON`,
  );
}

/** @internal */
export const SearchEmailResponse$inboundSchema: z.ZodMiniType<
  SearchEmailResponse,
  unknown
> = z.object({
  data: z.array(z.lazy(() => SearchEmailData$inboundSchema)),
  success: types.boolean(),
  error: types.optional(types.string()),
});

export function searchEmailResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchEmailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchEmailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchEmailResponse' from JSON`,
  );
}
