/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SearchPhoneRequest = {
  query: string;
};

export type SearchPhoneLocal = {
  id: number;
  startDat: number | null;
  address: string | null;
  aka1fullname: string | null;
  aka2fullname: string | null;
  aka3fullname: string | null;
  alt1dob: string | null;
  alt2dob: string | null;
  alt3dob: string | null;
  city: string | null;
  countyName: string | null;
  dob: string | null;
  firstname: string;
  lastname: string;
  middlename: string | null;
  nameSuff: string | null;
  phone1: number | null;
  st: string | null;
  zip: number | null;
};

export type LineTypeIntelligence = {
  carrierName: string;
  mobileCountryCode: string;
  mobileNetworkCode: string;
  type: string;
};

export type SimSwap = {
  carrierName: string | null;
  errorCode: number;
  lastSimSwap: number | null;
  mobileCountryCode: string | null;
  mobileNetworkCode: string | null;
};

export type SmsPumpingRisk = {
  carrierRiskCategories: string;
  numberBlocked: boolean;
  numberBlockedDate: number;
  numberBlockedLast3Months: boolean;
};

export type SearchPhonePhone = {
  countryCode: string;
  nationalFormat: string;
  phoneNumber: string;
  valid: boolean;
  lineTypeIntelligence?: LineTypeIntelligence | undefined;
  simSwap?: SimSwap | undefined;
  smsPumpingRisk?: SmsPumpingRisk | undefined;
};

export type SearchPhoneWeb = {
  aka: Array<string>;
  associates: Array<string>;
  children: number;
  currentAddress: string;
  emails: Array<string>;
  maritalStatus: string;
  name: string | null;
  pastAddresses: Array<string>;
  phones: Array<string>;
};

export type SearchPhoneData = {
  local: Array<SearchPhoneLocal>;
  phone: SearchPhonePhone;
  web: Array<SearchPhoneWeb>;
};

/**
 * Search successful
 */
export type SearchPhoneResponse = {
  data: SearchPhoneData;
  success: boolean;
  error?: string | undefined;
};

/** @internal */
export type SearchPhoneRequest$Outbound = {
  query: string;
};

/** @internal */
export const SearchPhoneRequest$outboundSchema: z.ZodMiniType<
  SearchPhoneRequest$Outbound,
  SearchPhoneRequest
> = z.object({
  query: z.string(),
});

export function searchPhoneRequestToJSON(
  searchPhoneRequest: SearchPhoneRequest,
): string {
  return JSON.stringify(
    SearchPhoneRequest$outboundSchema.parse(searchPhoneRequest),
  );
}

/** @internal */
export const SearchPhoneLocal$inboundSchema: z.ZodMiniType<
  SearchPhoneLocal,
  unknown
> = z.pipe(
  z.object({
    ID: types.number(),
    StartDat: types.nullable(types.number()),
    address: types.nullable(types.string()),
    aka1fullname: types.nullable(types.string()),
    aka2fullname: types.nullable(types.string()),
    aka3fullname: types.nullable(types.string()),
    alt1dob: types.nullable(types.string()),
    alt2dob: types.nullable(types.string()),
    alt3dob: types.nullable(types.string()),
    city: types.nullable(types.string()),
    county_name: types.nullable(types.string()),
    dob: types.nullable(types.string()),
    firstname: types.string(),
    lastname: types.string(),
    middlename: types.nullable(types.string()),
    name_suff: types.nullable(types.string()),
    phone1: types.nullable(types.number()),
    st: types.nullable(types.string()),
    zip: types.nullable(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "ID": "id",
      "StartDat": "startDat",
      "county_name": "countyName",
      "name_suff": "nameSuff",
    });
  }),
);

export function searchPhoneLocalFromJSON(
  jsonString: string,
): SafeParseResult<SearchPhoneLocal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPhoneLocal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPhoneLocal' from JSON`,
  );
}

/** @internal */
export const LineTypeIntelligence$inboundSchema: z.ZodMiniType<
  LineTypeIntelligence,
  unknown
> = z.pipe(
  z.object({
    carrier_name: types.string(),
    mobile_country_code: types.string(),
    mobile_network_code: types.string(),
    type: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "carrier_name": "carrierName",
      "mobile_country_code": "mobileCountryCode",
      "mobile_network_code": "mobileNetworkCode",
    });
  }),
);

export function lineTypeIntelligenceFromJSON(
  jsonString: string,
): SafeParseResult<LineTypeIntelligence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LineTypeIntelligence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LineTypeIntelligence' from JSON`,
  );
}

/** @internal */
export const SimSwap$inboundSchema: z.ZodMiniType<SimSwap, unknown> = z.pipe(
  z.object({
    carrier_name: types.nullable(types.string()),
    error_code: types.number(),
    last_sim_swap: types.nullable(types.number()),
    mobile_country_code: types.nullable(types.string()),
    mobile_network_code: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "carrier_name": "carrierName",
      "error_code": "errorCode",
      "last_sim_swap": "lastSimSwap",
      "mobile_country_code": "mobileCountryCode",
      "mobile_network_code": "mobileNetworkCode",
    });
  }),
);

export function simSwapFromJSON(
  jsonString: string,
): SafeParseResult<SimSwap, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimSwap$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimSwap' from JSON`,
  );
}

/** @internal */
export const SmsPumpingRisk$inboundSchema: z.ZodMiniType<
  SmsPumpingRisk,
  unknown
> = z.pipe(
  z.object({
    carrier_risk_categories: types.string(),
    number_blocked: types.boolean(),
    number_blocked_date: types.number(),
    number_blocked_last_3_months: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "carrier_risk_categories": "carrierRiskCategories",
      "number_blocked": "numberBlocked",
      "number_blocked_date": "numberBlockedDate",
      "number_blocked_last_3_months": "numberBlockedLast3Months",
    });
  }),
);

export function smsPumpingRiskFromJSON(
  jsonString: string,
): SafeParseResult<SmsPumpingRisk, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SmsPumpingRisk$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SmsPumpingRisk' from JSON`,
  );
}

/** @internal */
export const SearchPhonePhone$inboundSchema: z.ZodMiniType<
  SearchPhonePhone,
  unknown
> = z.pipe(
  z.object({
    country_code: types.string(),
    national_format: types.string(),
    phone_number: types.string(),
    valid: types.boolean(),
    line_type_intelligence: types.optional(
      z.lazy(() => LineTypeIntelligence$inboundSchema),
    ),
    sim_swap: types.optional(z.lazy(() => SimSwap$inboundSchema)),
    sms_pumping_risk: types.optional(
      z.lazy(() => SmsPumpingRisk$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "country_code": "countryCode",
      "national_format": "nationalFormat",
      "phone_number": "phoneNumber",
      "line_type_intelligence": "lineTypeIntelligence",
      "sim_swap": "simSwap",
      "sms_pumping_risk": "smsPumpingRisk",
    });
  }),
);

export function searchPhonePhoneFromJSON(
  jsonString: string,
): SafeParseResult<SearchPhonePhone, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPhonePhone$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPhonePhone' from JSON`,
  );
}

/** @internal */
export const SearchPhoneWeb$inboundSchema: z.ZodMiniType<
  SearchPhoneWeb,
  unknown
> = z.object({
  aka: z.array(types.string()),
  associates: z.array(types.string()),
  children: types.number(),
  currentAddress: types.string(),
  emails: z.array(types.string()),
  maritalStatus: types.string(),
  name: types.nullable(types.string()),
  pastAddresses: z.array(types.string()),
  phones: z.array(types.string()),
});

export function searchPhoneWebFromJSON(
  jsonString: string,
): SafeParseResult<SearchPhoneWeb, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPhoneWeb$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPhoneWeb' from JSON`,
  );
}

/** @internal */
export const SearchPhoneData$inboundSchema: z.ZodMiniType<
  SearchPhoneData,
  unknown
> = z.object({
  local: z.array(z.lazy(() => SearchPhoneLocal$inboundSchema)),
  phone: z.lazy(() => SearchPhonePhone$inboundSchema),
  web: z.array(z.lazy(() => SearchPhoneWeb$inboundSchema)),
});

export function searchPhoneDataFromJSON(
  jsonString: string,
): SafeParseResult<SearchPhoneData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPhoneData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPhoneData' from JSON`,
  );
}

/** @internal */
export const SearchPhoneResponse$inboundSchema: z.ZodMiniType<
  SearchPhoneResponse,
  unknown
> = z.object({
  data: z.lazy(() => SearchPhoneData$inboundSchema),
  success: types.boolean(),
  error: types.optional(types.string()),
});

export function searchPhoneResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchPhoneResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPhoneResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPhoneResponse' from JSON`,
  );
}
