/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SearchUsernameRequest = {
  query: string;
};

export const SearchUsernameType = {
  Email: "email",
  Username: "username",
} as const;
export type SearchUsernameType = OpenEnum<typeof SearchUsernameType>;

export type Id = number | string;

export type Account = {
  domain?: string | undefined;
  shortname?: string | undefined;
  url?: string | undefined;
  verified?: boolean | undefined;
};

export type Award = {};

export type AwardUnion = number | Award | string | boolean;

export type SearchUsernameBadge = {};

export type Badge = number | SearchUsernameBadge | string | boolean;

export type Bands = number | string;

export type BioLink = {};

export type BioLinkUnion = number | BioLink | string | boolean;

export type Club = {};

export type ClubUnion = number | Club | string | boolean;

export type Collections = number | string;

export type Connection = {
  name?: string | undefined;
  provider?: string | undefined;
};

export type Course = {
  crowns?: number | undefined;
  title?: string | undefined;
  xp?: number | undefined;
};

export type CryptoAddress = {};

export type CryptoAddressUnion = number | CryptoAddress | string | boolean;

export type Followers = number | string;

export type Following = number | string;

export type LatestPaste = {};

export type LatestPasteUnion = number | LatestPaste | string | boolean;

export type Link = {};

export type LinkUnion = number | Link | string | boolean;

export type SearchUsernameOrganization = {
  name?: string | undefined;
  url?: string | undefined;
};

export type Platform = {};

export type PlatformUnion = number | Platform | string | boolean;

export type Plays = number | string;

export type Proof = {};

export type ProofUnion = number | Proof | string | boolean;

export type SearchUsernameRole = {};

export type Role = number | SearchUsernameRole | string | boolean;

export type SocialLink = {};

export type SocialLinkUnion = number | SocialLink | string | boolean;

export type Socials = {
  facebook?: string | undefined;
  instagram?: string | undefined;
  twitter?: string | undefined;
  website?: string | undefined;
};

export type SocialsUnion = Socials | Array<string>;

export type SearchUsernameStatus = {
  isCoach?: boolean | undefined;
  isModerator?: boolean | undefined;
  isStaff?: boolean | undefined;
  isStreamer?: boolean | undefined;
  isTopBlogger?: boolean | undefined;
};

export type Status = string | SearchUsernameStatus;

export type UrlEntity = {};

export type UrlEntityUnion = number | UrlEntity | string | boolean;

export type Url = {
  title?: string | undefined;
  value?: string | undefined;
};

export type Metadata = {
  accentColor?: string | undefined;
  accountType?: string | undefined;
  accounts?: Array<Account> | undefined;
  address?: string | undefined;
  awardeeKarma?: number | undefined;
  awarderKarma?: number | undefined;
  awards?: Array<number | Award | string | boolean | null> | undefined;
  backgroundPicture?: string | undefined;
  badges?:
    | Array<number | SearchUsernameBadge | string | boolean | null>
    | undefined;
  bands?: number | string | undefined;
  bioLinks?: Array<number | BioLink | string | boolean | null> | undefined;
  blog?: string | undefined;
  boardCount?: number | undefined;
  broadcasterType?: string | undefined;
  capeUrl?: string | undefined;
  cashtagUrl?: string | undefined;
  channelId?: string | undefined;
  clubs?: Array<number | Club | string | boolean | null> | undefined;
  collections?: number | string | undefined;
  company?: string | undefined;
  connections?: Array<Connection> | undefined;
  courses?: Array<Course> | undefined;
  coverImage?: string | undefined;
  createdAt?: string | undefined;
  createdDate?: string | undefined;
  createdOn?: string | undefined;
  createdUtc?: number | undefined;
  cryptoAddresses?:
    | Array<number | CryptoAddress | string | boolean | null>
    | undefined;
  currency?: string | undefined;
  currentStreak?: number | undefined;
  devices?: Array<string> | undefined;
  emails?: Array<string> | undefined;
  externalUrl?: string | undefined;
  familyName?: string | undefined;
  followers?: number | string | undefined;
  following?: number | string | undefined;
  friendCount?: number | undefined;
  genres?: Array<string> | undefined;
  givenName?: string | undefined;
  hasPlus?: boolean | undefined;
  hasVerifiedEmail?: boolean | undefined;
  inspiredBy?: Array<string> | undefined;
  isAffiliate?: boolean | undefined;
  isBanned?: boolean | undefined;
  isBusiness?: boolean | undefined;
  isChannel?: boolean | undefined;
  isConfirmed?: boolean | undefined;
  isGold?: boolean | undefined;
  isGroup?: boolean | undefined;
  isHacker?: boolean | undefined;
  isJunior?: boolean | undefined;
  isLegacy?: boolean | undefined;
  isMetaBlocked?: boolean | undefined;
  isMod?: boolean | undefined;
  isPartner?: boolean | undefined;
  isPremium?: boolean | undefined;
  isProfessional?: boolean | undefined;
  isSuspended?: boolean | undefined;
  isVerified?: boolean | null | undefined;
  joinedAt?: string | undefined;
  keywords?: Array<string> | undefined;
  lastModified?: string | undefined;
  lastSeen?: string | undefined;
  latestPastes?:
    | Array<number | LatestPaste | string | boolean | null>
    | undefined;
  learningLanguage?: string | undefined;
  likes?: number | undefined;
  likesReceived?: number | undefined;
  links?: Array<number | Link | string | boolean | null> | undefined;
  listedCount?: number | undefined;
  mediaCount?: number | undefined;
  memberType?: string | undefined;
  organizations?: Array<SearchUsernameOrganization> | undefined;
  pageViews?: number | undefined;
  pastUsernames?: Array<string> | undefined;
  pasteViews?: number | undefined;
  pins?: number | undefined;
  platformId?: string | undefined;
  platforms?: Array<number | Platform | string | boolean | null> | undefined;
  playlistCount?: number | undefined;
  plays?: number | string | undefined;
  posts?: number | undefined;
  postsCount?: number | undefined;
  primaryTeam?: string | undefined;
  profileViews?: number | undefined;
  proofs?: Array<number | Proof | string | boolean | null> | undefined;
  provider?: string | undefined;
  providerId?: string | undefined;
  publicGists?: number | undefined;
  publicRepos?: number | undefined;
  ratePlan?: string | undefined;
  realName?: string | undefined;
  recentActivity?: any | undefined;
  recoveryEmail?: string | undefined;
  region?: string | undefined;
  registeredSince?: string | undefined;
  reputation?: number | undefined;
  reputationLabel?: string | undefined;
  roles?:
    | Array<number | SearchUsernameRole | string | boolean | null>
    | undefined;
  scratchTeam?: boolean | undefined;
  skills?: Array<string> | undefined;
  skinUrl?: string | undefined;
  socialLinks?:
    | Array<number | SocialLink | string | boolean | null>
    | undefined;
  socials?: Socials | Array<string> | undefined;
  status?: string | SearchUsernameStatus | undefined;
  steamId64?: string | undefined;
  streak?: number | undefined;
  subscriberCount?: number | undefined;
  subscribers?: number | undefined;
  themeTitle?: string | undefined;
  thumbnail?: string | undefined;
  title?: string | undefined;
  totalKarma?: number | undefined;
  totalScrobbles?: number | undefined;
  totalXp?: number | undefined;
  trackCount?: number | undefined;
  trnRank?: string | undefined;
  trnRating?: string | undefined;
  trophies?: Array<string> | undefined;
  tweets?: number | undefined;
  twitterUsername?: string | undefined;
  updatedAt?: string | undefined;
  upvotes?: number | undefined;
  urlEntities?: Array<number | UrlEntity | string | boolean | null> | undefined;
  urls?: Array<Url> | undefined;
  uuid?: string | undefined;
  videoCount?: number | undefined;
  visibleCollectionCount?: number | undefined;
  visibleWishlistCount?: number | undefined;
  website?: string | undefined;
};

export type SearchUsernameDataData = {
  avatar?: string | undefined;
  bio?: string | undefined;
  country?: string | undefined;
  displayName?: string | undefined;
  id?: number | string | undefined;
  isPrivate?: boolean | undefined;
  isVerified?: boolean | undefined;
  metadata?: Metadata | undefined;
  url?: string | undefined;
  username?: string | undefined;
};

export type SearchUsernameData = {
  durationMs: number;
  exists: boolean;
  service: string;
  type: SearchUsernameType;
  data?: SearchUsernameDataData | undefined;
  error?: string | undefined;
};

/**
 * Search successful
 */
export type SearchUsernameResponse = {
  data: Array<SearchUsernameData>;
  success: boolean;
  error?: string | undefined;
};

/** @internal */
export type SearchUsernameRequest$Outbound = {
  query: string;
};

/** @internal */
export const SearchUsernameRequest$outboundSchema: z.ZodMiniType<
  SearchUsernameRequest$Outbound,
  SearchUsernameRequest
> = z.object({
  query: z.string(),
});

export function searchUsernameRequestToJSON(
  searchUsernameRequest: SearchUsernameRequest,
): string {
  return JSON.stringify(
    SearchUsernameRequest$outboundSchema.parse(searchUsernameRequest),
  );
}

/** @internal */
export const SearchUsernameType$inboundSchema: z.ZodMiniType<
  SearchUsernameType,
  unknown
> = openEnums.inboundSchema(SearchUsernameType);

/** @internal */
export const Id$inboundSchema: z.ZodMiniType<Id, unknown> = smartUnion([
  types.number(),
  types.string(),
]);

export function idFromJSON(
  jsonString: string,
): SafeParseResult<Id, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Id$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Id' from JSON`,
  );
}

/** @internal */
export const Account$inboundSchema: z.ZodMiniType<Account, unknown> = z.object({
  domain: types.optional(types.string()),
  shortname: types.optional(types.string()),
  url: types.optional(types.string()),
  verified: types.optional(types.boolean()),
});

export function accountFromJSON(
  jsonString: string,
): SafeParseResult<Account, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Account$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Account' from JSON`,
  );
}

/** @internal */
export const Award$inboundSchema: z.ZodMiniType<Award, unknown> = z.object({});

export function awardFromJSON(
  jsonString: string,
): SafeParseResult<Award, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Award$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Award' from JSON`,
  );
}

/** @internal */
export const AwardUnion$inboundSchema: z.ZodMiniType<AwardUnion, unknown> =
  smartUnion([
    types.number(),
    z.lazy(() => Award$inboundSchema),
    types.string(),
    types.boolean(),
  ]);

export function awardUnionFromJSON(
  jsonString: string,
): SafeParseResult<AwardUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AwardUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AwardUnion' from JSON`,
  );
}

/** @internal */
export const SearchUsernameBadge$inboundSchema: z.ZodMiniType<
  SearchUsernameBadge,
  unknown
> = z.object({});

export function searchUsernameBadgeFromJSON(
  jsonString: string,
): SafeParseResult<SearchUsernameBadge, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchUsernameBadge$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchUsernameBadge' from JSON`,
  );
}

/** @internal */
export const Badge$inboundSchema: z.ZodMiniType<Badge, unknown> = smartUnion([
  types.number(),
  z.lazy(() => SearchUsernameBadge$inboundSchema),
  types.string(),
  types.boolean(),
]);

export function badgeFromJSON(
  jsonString: string,
): SafeParseResult<Badge, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Badge$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Badge' from JSON`,
  );
}

/** @internal */
export const Bands$inboundSchema: z.ZodMiniType<Bands, unknown> = smartUnion([
  types.number(),
  types.string(),
]);

export function bandsFromJSON(
  jsonString: string,
): SafeParseResult<Bands, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Bands$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Bands' from JSON`,
  );
}

/** @internal */
export const BioLink$inboundSchema: z.ZodMiniType<BioLink, unknown> = z.object(
  {},
);

export function bioLinkFromJSON(
  jsonString: string,
): SafeParseResult<BioLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BioLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BioLink' from JSON`,
  );
}

/** @internal */
export const BioLinkUnion$inboundSchema: z.ZodMiniType<BioLinkUnion, unknown> =
  smartUnion([
    types.number(),
    z.lazy(() => BioLink$inboundSchema),
    types.string(),
    types.boolean(),
  ]);

export function bioLinkUnionFromJSON(
  jsonString: string,
): SafeParseResult<BioLinkUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BioLinkUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BioLinkUnion' from JSON`,
  );
}

/** @internal */
export const Club$inboundSchema: z.ZodMiniType<Club, unknown> = z.object({});

export function clubFromJSON(
  jsonString: string,
): SafeParseResult<Club, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Club$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Club' from JSON`,
  );
}

/** @internal */
export const ClubUnion$inboundSchema: z.ZodMiniType<ClubUnion, unknown> =
  smartUnion([
    types.number(),
    z.lazy(() => Club$inboundSchema),
    types.string(),
    types.boolean(),
  ]);

export function clubUnionFromJSON(
  jsonString: string,
): SafeParseResult<ClubUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClubUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClubUnion' from JSON`,
  );
}

/** @internal */
export const Collections$inboundSchema: z.ZodMiniType<Collections, unknown> =
  smartUnion([types.number(), types.string()]);

export function collectionsFromJSON(
  jsonString: string,
): SafeParseResult<Collections, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Collections$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Collections' from JSON`,
  );
}

/** @internal */
export const Connection$inboundSchema: z.ZodMiniType<Connection, unknown> = z
  .object({
    name: types.optional(types.string()),
    provider: types.optional(types.string()),
  });

export function connectionFromJSON(
  jsonString: string,
): SafeParseResult<Connection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Connection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Connection' from JSON`,
  );
}

/** @internal */
export const Course$inboundSchema: z.ZodMiniType<Course, unknown> = z.object({
  crowns: types.optional(types.number()),
  title: types.optional(types.string()),
  xp: types.optional(types.number()),
});

export function courseFromJSON(
  jsonString: string,
): SafeParseResult<Course, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Course$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Course' from JSON`,
  );
}

/** @internal */
export const CryptoAddress$inboundSchema: z.ZodMiniType<
  CryptoAddress,
  unknown
> = z.object({});

export function cryptoAddressFromJSON(
  jsonString: string,
): SafeParseResult<CryptoAddress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CryptoAddress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CryptoAddress' from JSON`,
  );
}

/** @internal */
export const CryptoAddressUnion$inboundSchema: z.ZodMiniType<
  CryptoAddressUnion,
  unknown
> = smartUnion([
  types.number(),
  z.lazy(() => CryptoAddress$inboundSchema),
  types.string(),
  types.boolean(),
]);

export function cryptoAddressUnionFromJSON(
  jsonString: string,
): SafeParseResult<CryptoAddressUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CryptoAddressUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CryptoAddressUnion' from JSON`,
  );
}

/** @internal */
export const Followers$inboundSchema: z.ZodMiniType<Followers, unknown> =
  smartUnion([types.number(), types.string()]);

export function followersFromJSON(
  jsonString: string,
): SafeParseResult<Followers, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Followers$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Followers' from JSON`,
  );
}

/** @internal */
export const Following$inboundSchema: z.ZodMiniType<Following, unknown> =
  smartUnion([types.number(), types.string()]);

export function followingFromJSON(
  jsonString: string,
): SafeParseResult<Following, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Following$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Following' from JSON`,
  );
}

/** @internal */
export const LatestPaste$inboundSchema: z.ZodMiniType<LatestPaste, unknown> = z
  .object({});

export function latestPasteFromJSON(
  jsonString: string,
): SafeParseResult<LatestPaste, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LatestPaste$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LatestPaste' from JSON`,
  );
}

/** @internal */
export const LatestPasteUnion$inboundSchema: z.ZodMiniType<
  LatestPasteUnion,
  unknown
> = smartUnion([
  types.number(),
  z.lazy(() => LatestPaste$inboundSchema),
  types.string(),
  types.boolean(),
]);

export function latestPasteUnionFromJSON(
  jsonString: string,
): SafeParseResult<LatestPasteUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LatestPasteUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LatestPasteUnion' from JSON`,
  );
}

/** @internal */
export const Link$inboundSchema: z.ZodMiniType<Link, unknown> = z.object({});

export function linkFromJSON(
  jsonString: string,
): SafeParseResult<Link, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Link$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Link' from JSON`,
  );
}

/** @internal */
export const LinkUnion$inboundSchema: z.ZodMiniType<LinkUnion, unknown> =
  smartUnion([
    types.number(),
    z.lazy(() => Link$inboundSchema),
    types.string(),
    types.boolean(),
  ]);

export function linkUnionFromJSON(
  jsonString: string,
): SafeParseResult<LinkUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkUnion' from JSON`,
  );
}

/** @internal */
export const SearchUsernameOrganization$inboundSchema: z.ZodMiniType<
  SearchUsernameOrganization,
  unknown
> = z.object({
  name: types.optional(types.string()),
  url: types.optional(types.string()),
});

export function searchUsernameOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<SearchUsernameOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchUsernameOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchUsernameOrganization' from JSON`,
  );
}

/** @internal */
export const Platform$inboundSchema: z.ZodMiniType<Platform, unknown> = z
  .object({});

export function platformFromJSON(
  jsonString: string,
): SafeParseResult<Platform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Platform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Platform' from JSON`,
  );
}

/** @internal */
export const PlatformUnion$inboundSchema: z.ZodMiniType<
  PlatformUnion,
  unknown
> = smartUnion([
  types.number(),
  z.lazy(() => Platform$inboundSchema),
  types.string(),
  types.boolean(),
]);

export function platformUnionFromJSON(
  jsonString: string,
): SafeParseResult<PlatformUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformUnion' from JSON`,
  );
}

/** @internal */
export const Plays$inboundSchema: z.ZodMiniType<Plays, unknown> = smartUnion([
  types.number(),
  types.string(),
]);

export function playsFromJSON(
  jsonString: string,
): SafeParseResult<Plays, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Plays$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Plays' from JSON`,
  );
}

/** @internal */
export const Proof$inboundSchema: z.ZodMiniType<Proof, unknown> = z.object({});

export function proofFromJSON(
  jsonString: string,
): SafeParseResult<Proof, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Proof$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Proof' from JSON`,
  );
}

/** @internal */
export const ProofUnion$inboundSchema: z.ZodMiniType<ProofUnion, unknown> =
  smartUnion([
    types.number(),
    z.lazy(() => Proof$inboundSchema),
    types.string(),
    types.boolean(),
  ]);

export function proofUnionFromJSON(
  jsonString: string,
): SafeParseResult<ProofUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProofUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProofUnion' from JSON`,
  );
}

/** @internal */
export const SearchUsernameRole$inboundSchema: z.ZodMiniType<
  SearchUsernameRole,
  unknown
> = z.object({});

export function searchUsernameRoleFromJSON(
  jsonString: string,
): SafeParseResult<SearchUsernameRole, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchUsernameRole$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchUsernameRole' from JSON`,
  );
}

/** @internal */
export const Role$inboundSchema: z.ZodMiniType<Role, unknown> = smartUnion([
  types.number(),
  z.lazy(() => SearchUsernameRole$inboundSchema),
  types.string(),
  types.boolean(),
]);

export function roleFromJSON(
  jsonString: string,
): SafeParseResult<Role, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Role$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Role' from JSON`,
  );
}

/** @internal */
export const SocialLink$inboundSchema: z.ZodMiniType<SocialLink, unknown> = z
  .object({});

export function socialLinkFromJSON(
  jsonString: string,
): SafeParseResult<SocialLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SocialLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SocialLink' from JSON`,
  );
}

/** @internal */
export const SocialLinkUnion$inboundSchema: z.ZodMiniType<
  SocialLinkUnion,
  unknown
> = smartUnion([
  types.number(),
  z.lazy(() => SocialLink$inboundSchema),
  types.string(),
  types.boolean(),
]);

export function socialLinkUnionFromJSON(
  jsonString: string,
): SafeParseResult<SocialLinkUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SocialLinkUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SocialLinkUnion' from JSON`,
  );
}

/** @internal */
export const Socials$inboundSchema: z.ZodMiniType<Socials, unknown> = z.object({
  facebook: types.optional(types.string()),
  instagram: types.optional(types.string()),
  twitter: types.optional(types.string()),
  website: types.optional(types.string()),
});

export function socialsFromJSON(
  jsonString: string,
): SafeParseResult<Socials, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Socials$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Socials' from JSON`,
  );
}

/** @internal */
export const SocialsUnion$inboundSchema: z.ZodMiniType<SocialsUnion, unknown> =
  smartUnion([z.lazy(() => Socials$inboundSchema), z.array(types.string())]);

export function socialsUnionFromJSON(
  jsonString: string,
): SafeParseResult<SocialsUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SocialsUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SocialsUnion' from JSON`,
  );
}

/** @internal */
export const SearchUsernameStatus$inboundSchema: z.ZodMiniType<
  SearchUsernameStatus,
  unknown
> = z.pipe(
  z.object({
    is_coach: types.optional(types.boolean()),
    is_moderator: types.optional(types.boolean()),
    is_staff: types.optional(types.boolean()),
    is_streamer: types.optional(types.boolean()),
    is_top_blogger: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "is_coach": "isCoach",
      "is_moderator": "isModerator",
      "is_staff": "isStaff",
      "is_streamer": "isStreamer",
      "is_top_blogger": "isTopBlogger",
    });
  }),
);

export function searchUsernameStatusFromJSON(
  jsonString: string,
): SafeParseResult<SearchUsernameStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchUsernameStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchUsernameStatus' from JSON`,
  );
}

/** @internal */
export const Status$inboundSchema: z.ZodMiniType<Status, unknown> = smartUnion([
  types.string(),
  z.lazy(() => SearchUsernameStatus$inboundSchema),
]);

export function statusFromJSON(
  jsonString: string,
): SafeParseResult<Status, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Status$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Status' from JSON`,
  );
}

/** @internal */
export const UrlEntity$inboundSchema: z.ZodMiniType<UrlEntity, unknown> = z
  .object({});

export function urlEntityFromJSON(
  jsonString: string,
): SafeParseResult<UrlEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UrlEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UrlEntity' from JSON`,
  );
}

/** @internal */
export const UrlEntityUnion$inboundSchema: z.ZodMiniType<
  UrlEntityUnion,
  unknown
> = smartUnion([
  types.number(),
  z.lazy(() => UrlEntity$inboundSchema),
  types.string(),
  types.boolean(),
]);

export function urlEntityUnionFromJSON(
  jsonString: string,
): SafeParseResult<UrlEntityUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UrlEntityUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UrlEntityUnion' from JSON`,
  );
}

/** @internal */
export const Url$inboundSchema: z.ZodMiniType<Url, unknown> = z.object({
  title: types.optional(types.string()),
  value: types.optional(types.string()),
});

export function urlFromJSON(
  jsonString: string,
): SafeParseResult<Url, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Url$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Url' from JSON`,
  );
}

/** @internal */
export const Metadata$inboundSchema: z.ZodMiniType<Metadata, unknown> = z.pipe(
  z.object({
    accent_color: types.optional(types.string()),
    account_type: types.optional(types.string()),
    accounts: types.optional(z.array(z.lazy(() => Account$inboundSchema))),
    address: types.optional(types.string()),
    awardee_karma: types.optional(types.number()),
    awarder_karma: types.optional(types.number()),
    awards: types.optional(
      z.array(types.nullable(smartUnion([
        types.number(),
        z.lazy(() => Award$inboundSchema),
        types.string(),
        types.boolean(),
      ]))),
    ),
    background_picture: types.optional(types.string()),
    badges: types.optional(
      z.array(types.nullable(smartUnion([
        types.number(),
        z.lazy(() => SearchUsernameBadge$inboundSchema),
        types.string(),
        types.boolean(),
      ]))),
    ),
    bands: types.optional(smartUnion([types.number(), types.string()])),
    bio_links: types.optional(
      z.array(types.nullable(smartUnion([
        types.number(),
        z.lazy(() => BioLink$inboundSchema),
        types.string(),
        types.boolean(),
      ]))),
    ),
    blog: types.optional(types.string()),
    board_count: types.optional(types.number()),
    broadcaster_type: types.optional(types.string()),
    cape_url: types.optional(types.string()),
    cashtag_url: types.optional(types.string()),
    channel_id: types.optional(types.string()),
    clubs: types.optional(
      z.array(types.nullable(smartUnion([
        types.number(),
        z.lazy(() => Club$inboundSchema),
        types.string(),
        types.boolean(),
      ]))),
    ),
    collections: types.optional(smartUnion([types.number(), types.string()])),
    company: types.optional(types.string()),
    connections: types.optional(
      z.array(z.lazy(() => Connection$inboundSchema)),
    ),
    courses: types.optional(z.array(z.lazy(() => Course$inboundSchema))),
    cover_image: types.optional(types.string()),
    created_at: types.optional(types.string()),
    created_date: types.optional(types.string()),
    created_on: types.optional(types.string()),
    created_utc: types.optional(types.number()),
    crypto_addresses: types.optional(
      z.array(types.nullable(smartUnion([
        types.number(),
        z.lazy(() => CryptoAddress$inboundSchema),
        types.string(),
        types.boolean(),
      ]))),
    ),
    currency: types.optional(types.string()),
    current_streak: types.optional(types.number()),
    devices: types.optional(z.array(types.string())),
    emails: types.optional(z.array(types.string())),
    external_url: types.optional(types.string()),
    family_name: types.optional(types.string()),
    followers: types.optional(smartUnion([types.number(), types.string()])),
    following: types.optional(smartUnion([types.number(), types.string()])),
    friend_count: types.optional(types.number()),
    genres: types.optional(z.array(types.string())),
    given_name: types.optional(types.string()),
    has_plus: types.optional(types.boolean()),
    has_verified_email: types.optional(types.boolean()),
    inspired_by: types.optional(z.array(types.string())),
    is_affiliate: types.optional(types.boolean()),
    is_banned: types.optional(types.boolean()),
    is_business: types.optional(types.boolean()),
    is_channel: types.optional(types.boolean()),
    is_confirmed: types.optional(types.boolean()),
    is_gold: types.optional(types.boolean()),
    is_group: types.optional(types.boolean()),
    is_hacker: types.optional(types.boolean()),
    is_junior: types.optional(types.boolean()),
    is_legacy: types.optional(types.boolean()),
    is_meta_blocked: types.optional(types.boolean()),
    is_mod: types.optional(types.boolean()),
    is_partner: types.optional(types.boolean()),
    is_premium: types.optional(types.boolean()),
    is_professional: types.optional(types.boolean()),
    is_suspended: types.optional(types.boolean()),
    is_verified: z.optional(z.nullable(types.boolean())),
    joined_at: types.optional(types.string()),
    keywords: types.optional(z.array(types.string())),
    last_modified: types.optional(types.string()),
    last_seen: types.optional(types.string()),
    latest_pastes: types.optional(
      z.array(types.nullable(smartUnion([
        types.number(),
        z.lazy(() => LatestPaste$inboundSchema),
        types.string(),
        types.boolean(),
      ]))),
    ),
    learning_language: types.optional(types.string()),
    likes: types.optional(types.number()),
    likes_received: types.optional(types.number()),
    links: types.optional(
      z.array(types.nullable(smartUnion([
        types.number(),
        z.lazy(() => Link$inboundSchema),
        types.string(),
        types.boolean(),
      ]))),
    ),
    listed_count: types.optional(types.number()),
    media_count: types.optional(types.number()),
    member_type: types.optional(types.string()),
    organizations: types.optional(
      z.array(z.lazy(() => SearchUsernameOrganization$inboundSchema)),
    ),
    page_views: types.optional(types.number()),
    past_usernames: types.optional(z.array(types.string())),
    paste_views: types.optional(types.number()),
    pins: types.optional(types.number()),
    platform_id: types.optional(types.string()),
    platforms: types.optional(
      z.array(types.nullable(smartUnion([
        types.number(),
        z.lazy(() => Platform$inboundSchema),
        types.string(),
        types.boolean(),
      ]))),
    ),
    playlist_count: types.optional(types.number()),
    plays: types.optional(smartUnion([types.number(), types.string()])),
    posts: types.optional(types.number()),
    posts_count: types.optional(types.number()),
    primary_team: types.optional(types.string()),
    profile_views: types.optional(types.number()),
    proofs: types.optional(
      z.array(types.nullable(smartUnion([
        types.number(),
        z.lazy(() => Proof$inboundSchema),
        types.string(),
        types.boolean(),
      ]))),
    ),
    provider: types.optional(types.string()),
    provider_id: types.optional(types.string()),
    public_gists: types.optional(types.number()),
    public_repos: types.optional(types.number()),
    rate_plan: types.optional(types.string()),
    real_name: types.optional(types.string()),
    recent_activity: types.optional(z.any()),
    recovery_email: types.optional(types.string()),
    region: types.optional(types.string()),
    registered_since: types.optional(types.string()),
    reputation: types.optional(types.number()),
    reputation_label: types.optional(types.string()),
    roles: types.optional(
      z.array(types.nullable(smartUnion([
        types.number(),
        z.lazy(() => SearchUsernameRole$inboundSchema),
        types.string(),
        types.boolean(),
      ]))),
    ),
    scratch_team: types.optional(types.boolean()),
    skills: types.optional(z.array(types.string())),
    skin_url: types.optional(types.string()),
    social_links: types.optional(
      z.array(types.nullable(smartUnion([
        types.number(),
        z.lazy(() => SocialLink$inboundSchema),
        types.string(),
        types.boolean(),
      ]))),
    ),
    socials: types.optional(
      smartUnion([
        z.lazy(() => Socials$inboundSchema),
        z.array(types.string()),
      ]),
    ),
    status: types.optional(
      smartUnion([
        types.string(),
        z.lazy(() => SearchUsernameStatus$inboundSchema),
      ]),
    ),
    steam_id_64: types.optional(types.string()),
    streak: types.optional(types.number()),
    subscriber_count: types.optional(types.number()),
    subscribers: types.optional(types.number()),
    theme_title: types.optional(types.string()),
    thumbnail: types.optional(types.string()),
    title: types.optional(types.string()),
    total_karma: types.optional(types.number()),
    total_scrobbles: types.optional(types.number()),
    total_xp: types.optional(types.number()),
    track_count: types.optional(types.number()),
    trn_rank: types.optional(types.string()),
    trn_rating: types.optional(types.string()),
    trophies: types.optional(z.array(types.string())),
    tweets: types.optional(types.number()),
    twitter_username: types.optional(types.string()),
    updated_at: types.optional(types.string()),
    upvotes: types.optional(types.number()),
    url_entities: types.optional(
      z.array(types.nullable(smartUnion([
        types.number(),
        z.lazy(() => UrlEntity$inboundSchema),
        types.string(),
        types.boolean(),
      ]))),
    ),
    urls: types.optional(z.array(z.lazy(() => Url$inboundSchema))),
    uuid: types.optional(types.string()),
    video_count: types.optional(types.number()),
    visible_collection_count: types.optional(types.number()),
    visible_wishlist_count: types.optional(types.number()),
    website: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "accent_color": "accentColor",
      "account_type": "accountType",
      "awardee_karma": "awardeeKarma",
      "awarder_karma": "awarderKarma",
      "background_picture": "backgroundPicture",
      "bio_links": "bioLinks",
      "board_count": "boardCount",
      "broadcaster_type": "broadcasterType",
      "cape_url": "capeUrl",
      "cashtag_url": "cashtagUrl",
      "channel_id": "channelId",
      "cover_image": "coverImage",
      "created_at": "createdAt",
      "created_date": "createdDate",
      "created_on": "createdOn",
      "created_utc": "createdUtc",
      "crypto_addresses": "cryptoAddresses",
      "current_streak": "currentStreak",
      "external_url": "externalUrl",
      "family_name": "familyName",
      "friend_count": "friendCount",
      "given_name": "givenName",
      "has_plus": "hasPlus",
      "has_verified_email": "hasVerifiedEmail",
      "inspired_by": "inspiredBy",
      "is_affiliate": "isAffiliate",
      "is_banned": "isBanned",
      "is_business": "isBusiness",
      "is_channel": "isChannel",
      "is_confirmed": "isConfirmed",
      "is_gold": "isGold",
      "is_group": "isGroup",
      "is_hacker": "isHacker",
      "is_junior": "isJunior",
      "is_legacy": "isLegacy",
      "is_meta_blocked": "isMetaBlocked",
      "is_mod": "isMod",
      "is_partner": "isPartner",
      "is_premium": "isPremium",
      "is_professional": "isProfessional",
      "is_suspended": "isSuspended",
      "is_verified": "isVerified",
      "joined_at": "joinedAt",
      "last_modified": "lastModified",
      "last_seen": "lastSeen",
      "latest_pastes": "latestPastes",
      "learning_language": "learningLanguage",
      "likes_received": "likesReceived",
      "listed_count": "listedCount",
      "media_count": "mediaCount",
      "member_type": "memberType",
      "page_views": "pageViews",
      "past_usernames": "pastUsernames",
      "paste_views": "pasteViews",
      "platform_id": "platformId",
      "playlist_count": "playlistCount",
      "posts_count": "postsCount",
      "primary_team": "primaryTeam",
      "profile_views": "profileViews",
      "provider_id": "providerId",
      "public_gists": "publicGists",
      "public_repos": "publicRepos",
      "rate_plan": "ratePlan",
      "real_name": "realName",
      "recent_activity": "recentActivity",
      "recovery_email": "recoveryEmail",
      "registered_since": "registeredSince",
      "reputation_label": "reputationLabel",
      "scratch_team": "scratchTeam",
      "skin_url": "skinUrl",
      "social_links": "socialLinks",
      "steam_id_64": "steamId64",
      "subscriber_count": "subscriberCount",
      "theme_title": "themeTitle",
      "total_karma": "totalKarma",
      "total_scrobbles": "totalScrobbles",
      "total_xp": "totalXp",
      "track_count": "trackCount",
      "trn_rank": "trnRank",
      "trn_rating": "trnRating",
      "twitter_username": "twitterUsername",
      "updated_at": "updatedAt",
      "url_entities": "urlEntities",
      "video_count": "videoCount",
      "visible_collection_count": "visibleCollectionCount",
      "visible_wishlist_count": "visibleWishlistCount",
    });
  }),
);

export function metadataFromJSON(
  jsonString: string,
): SafeParseResult<Metadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Metadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Metadata' from JSON`,
  );
}

/** @internal */
export const SearchUsernameDataData$inboundSchema: z.ZodMiniType<
  SearchUsernameDataData,
  unknown
> = z.object({
  avatar: types.optional(types.string()),
  bio: types.optional(types.string()),
  country: types.optional(types.string()),
  displayName: types.optional(types.string()),
  id: types.optional(smartUnion([types.number(), types.string()])),
  isPrivate: types.optional(types.boolean()),
  isVerified: types.optional(types.boolean()),
  metadata: types.optional(z.lazy(() => Metadata$inboundSchema)),
  url: types.optional(types.string()),
  username: types.optional(types.string()),
});

export function searchUsernameDataDataFromJSON(
  jsonString: string,
): SafeParseResult<SearchUsernameDataData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchUsernameDataData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchUsernameDataData' from JSON`,
  );
}

/** @internal */
export const SearchUsernameData$inboundSchema: z.ZodMiniType<
  SearchUsernameData,
  unknown
> = z.pipe(
  z.object({
    duration_ms: types.number(),
    exists: types.boolean(),
    service: types.string(),
    type: SearchUsernameType$inboundSchema,
    data: types.optional(z.lazy(() => SearchUsernameDataData$inboundSchema)),
    error: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "duration_ms": "durationMs",
    });
  }),
);

export function searchUsernameDataFromJSON(
  jsonString: string,
): SafeParseResult<SearchUsernameData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchUsernameData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchUsernameData' from JSON`,
  );
}

/** @internal */
export const SearchUsernameResponse$inboundSchema: z.ZodMiniType<
  SearchUsernameResponse,
  unknown
> = z.object({
  data: z.array(z.lazy(() => SearchUsernameData$inboundSchema)),
  success: types.boolean(),
  error: types.optional(types.string()),
});

export function searchUsernameResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchUsernameResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchUsernameResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchUsernameResponse' from JSON`,
  );
}
