/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SearchCertificatesRequest = {
  query: string;
};

export type SearchCertificatesInternalServerErrorData = {
  commonName: string;
  entryTimestamp: string;
  id: number;
  issuerCaId: number;
  issuerName: string;
  nameValue: string;
  notAfter: string;
  notBefore: string;
  serialNumber: string;
};

export type SearchCertificatesData = {
  commonName: string;
  entryTimestamp: string;
  id: number;
  issuerCaId: number;
  issuerName: string;
  nameValue: string;
  notAfter: string;
  notBefore: string;
  serialNumber: string;
};

/**
 * Search successful
 */
export type SearchCertificatesResponse = {
  data: Array<SearchCertificatesData>;
  success: boolean;
  error?: string | undefined;
};

/** @internal */
export type SearchCertificatesRequest$Outbound = {
  query: string;
};

/** @internal */
export const SearchCertificatesRequest$outboundSchema: z.ZodMiniType<
  SearchCertificatesRequest$Outbound,
  SearchCertificatesRequest
> = z.object({
  query: z.string(),
});

export function searchCertificatesRequestToJSON(
  searchCertificatesRequest: SearchCertificatesRequest,
): string {
  return JSON.stringify(
    SearchCertificatesRequest$outboundSchema.parse(searchCertificatesRequest),
  );
}

/** @internal */
export const SearchCertificatesInternalServerErrorData$inboundSchema:
  z.ZodMiniType<SearchCertificatesInternalServerErrorData, unknown> = z.pipe(
    z.object({
      common_name: types.string(),
      entry_timestamp: types.string(),
      id: types.number(),
      issuer_ca_id: types.number(),
      issuer_name: types.string(),
      name_value: types.string(),
      not_after: types.string(),
      not_before: types.string(),
      serial_number: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "common_name": "commonName",
        "entry_timestamp": "entryTimestamp",
        "issuer_ca_id": "issuerCaId",
        "issuer_name": "issuerName",
        "name_value": "nameValue",
        "not_after": "notAfter",
        "not_before": "notBefore",
        "serial_number": "serialNumber",
      });
    }),
  );

export function searchCertificatesInternalServerErrorDataFromJSON(
  jsonString: string,
): SafeParseResult<
  SearchCertificatesInternalServerErrorData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SearchCertificatesInternalServerErrorData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SearchCertificatesInternalServerErrorData' from JSON`,
  );
}

/** @internal */
export const SearchCertificatesData$inboundSchema: z.ZodMiniType<
  SearchCertificatesData,
  unknown
> = z.pipe(
  z.object({
    common_name: types.string(),
    entry_timestamp: types.string(),
    id: types.number(),
    issuer_ca_id: types.number(),
    issuer_name: types.string(),
    name_value: types.string(),
    not_after: types.string(),
    not_before: types.string(),
    serial_number: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "common_name": "commonName",
      "entry_timestamp": "entryTimestamp",
      "issuer_ca_id": "issuerCaId",
      "issuer_name": "issuerName",
      "name_value": "nameValue",
      "not_after": "notAfter",
      "not_before": "notBefore",
      "serial_number": "serialNumber",
    });
  }),
);

export function searchCertificatesDataFromJSON(
  jsonString: string,
): SafeParseResult<SearchCertificatesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchCertificatesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchCertificatesData' from JSON`,
  );
}

/** @internal */
export const SearchCertificatesResponse$inboundSchema: z.ZodMiniType<
  SearchCertificatesResponse,
  unknown
> = z.object({
  data: z.array(z.lazy(() => SearchCertificatesData$inboundSchema)),
  success: types.boolean(),
  error: types.optional(types.string()),
});

export function searchCertificatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchCertificatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchCertificatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchCertificatesResponse' from JSON`,
  );
}
