/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SearchAddressRequest = {
  address1: string;
  city: string;
  state: string;
  zip: string;
  address2?: string | undefined;
};

export type SearchAddressLocal = {
  id: number;
  startDat: number | null;
  address: string | null;
  aka1fullname: string | null;
  aka2fullname: string | null;
  aka3fullname: string | null;
  alt1dob: string | null;
  alt2dob: string | null;
  alt3dob: string | null;
  city: string | null;
  countyName: string | null;
  dob: string | null;
  firstname: string;
  lastname: string;
  middlename: string | null;
  nameSuff: string | null;
  phone1: number | null;
  st: string | null;
  zip: number | null;
};

export type SearchAddressWeb = {
  aka: Array<string>;
  associates: Array<string>;
  children: number;
  currentAddress: string;
  emails: Array<string>;
  maritalStatus: string;
  name: string | null;
  pastAddresses: Array<string>;
  phones: Array<string>;
};

export type SearchAddressData = {
  local: Array<SearchAddressLocal>;
  web: Array<SearchAddressWeb>;
};

/**
 * Search for individuals by address.
 */
export type SearchAddressResponse = {
  data: SearchAddressData;
  success: boolean;
};

/** @internal */
export type SearchAddressRequest$Outbound = {
  address1: string;
  city: string;
  state: string;
  zip: string;
  address2?: string | undefined;
};

/** @internal */
export const SearchAddressRequest$outboundSchema: z.ZodMiniType<
  SearchAddressRequest$Outbound,
  SearchAddressRequest
> = z.object({
  address1: z.string(),
  city: z.string(),
  state: z.string(),
  zip: z.string(),
  address2: z.optional(z.string()),
});

export function searchAddressRequestToJSON(
  searchAddressRequest: SearchAddressRequest,
): string {
  return JSON.stringify(
    SearchAddressRequest$outboundSchema.parse(searchAddressRequest),
  );
}

/** @internal */
export const SearchAddressLocal$inboundSchema: z.ZodMiniType<
  SearchAddressLocal,
  unknown
> = z.pipe(
  z.object({
    ID: types.number(),
    StartDat: types.nullable(types.number()),
    address: types.nullable(types.string()),
    aka1fullname: types.nullable(types.string()),
    aka2fullname: types.nullable(types.string()),
    aka3fullname: types.nullable(types.string()),
    alt1dob: types.nullable(types.string()),
    alt2dob: types.nullable(types.string()),
    alt3dob: types.nullable(types.string()),
    city: types.nullable(types.string()),
    county_name: types.nullable(types.string()),
    dob: types.nullable(types.string()),
    firstname: types.string(),
    lastname: types.string(),
    middlename: types.nullable(types.string()),
    name_suff: types.nullable(types.string()),
    phone1: types.nullable(types.number()),
    st: types.nullable(types.string()),
    zip: types.nullable(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "ID": "id",
      "StartDat": "startDat",
      "county_name": "countyName",
      "name_suff": "nameSuff",
    });
  }),
);

export function searchAddressLocalFromJSON(
  jsonString: string,
): SafeParseResult<SearchAddressLocal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchAddressLocal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchAddressLocal' from JSON`,
  );
}

/** @internal */
export const SearchAddressWeb$inboundSchema: z.ZodMiniType<
  SearchAddressWeb,
  unknown
> = z.object({
  aka: z.array(types.string()),
  associates: z.array(types.string()),
  children: types.number(),
  currentAddress: types.string(),
  emails: z.array(types.string()),
  maritalStatus: types.string(),
  name: types.nullable(types.string()),
  pastAddresses: z.array(types.string()),
  phones: z.array(types.string()),
});

export function searchAddressWebFromJSON(
  jsonString: string,
): SafeParseResult<SearchAddressWeb, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchAddressWeb$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchAddressWeb' from JSON`,
  );
}

/** @internal */
export const SearchAddressData$inboundSchema: z.ZodMiniType<
  SearchAddressData,
  unknown
> = z.object({
  local: z.array(z.lazy(() => SearchAddressLocal$inboundSchema)),
  web: z.array(z.lazy(() => SearchAddressWeb$inboundSchema)),
});

export function searchAddressDataFromJSON(
  jsonString: string,
): SafeParseResult<SearchAddressData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchAddressData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchAddressData' from JSON`,
  );
}

/** @internal */
export const SearchAddressResponse$inboundSchema: z.ZodMiniType<
  SearchAddressResponse,
  unknown
> = z.object({
  data: z.lazy(() => SearchAddressData$inboundSchema),
  success: types.boolean(),
});

export function searchAddressResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchAddressResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchAddressResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchAddressResponse' from JSON`,
  );
}
