/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SearchDiscordRequest = {
  query: string;
};

export type Traits = {
  label: string;
  name: string;
  position: number;
  url: string | null;
};

export type Clan = {
  badge: string | null;
  banner: string | null;
  boosts: number | null;
  description: string | null;
  features: Array<string> | null;
  icon: string | null;
  id: string;
  invite: string | null;
  memberCount: number | null;
  name: string | null;
  onlineCount: number | null;
  tag: string | null;
  traits: Array<Traits> | null;
};

export type ConnectedAccounts2 = {
  id: string;
  link: string | null;
  name: string;
};

export type ConnectedAccounts1 = {
  id: string;
  link: string | null;
  name: string;
};

export type ConnectedAccountsUnion =
  | ConnectedAccounts1
  | Array<ConnectedAccounts2>;

export type Details = {
  ground: string;
  source: string;
  targetType: string;
};

export type Timeline = {
  application: number;
  content: number;
  created: number;
};

export type ModAction = {
  date: number;
  description: string;
  details: Details;
  id: string;
  status: string;
  tags: Array<string>;
  timeline: Timeline;
  title: string;
};

export type Badge = {
  description: string;
  icon: string;
  name: string;
  redirectURL: string;
  type: number;
};

export type Sender = {
  badges: Array<Badge>;
  discordID: string;
  id: number;
  profilePhoto: string;
  username: string;
  clientMod?: boolean | undefined;
};

export type Review = {
  comment: string;
  id: number;
  sender: Sender;
  timestamp: number;
  type: number;
  star?: number | undefined;
};

export type SearchDiscordPlatforms = {
  playstation?: string | undefined;
  xbox?: string | undefined;
};

export type SearchDiscordPresence = {
  iconUrl: string;
  lastOnline: string;
  text: string;
  type: number;
};

export type SearchDiscordStats = {
  followers: number;
  following: number;
  friends: number;
  placeVisits: number;
};

export type SearchDiscordRolimons = {
  rap: number;
  value: number;
  rank?: number | undefined;
};

export type RobloxProfile = {
  avatarUrl: string | null;
  badges: Array<string>;
  created: string;
  description: string;
  displayName: string;
  hasPremium: boolean;
  id: number;
  isAdmin: boolean;
  isBanned: boolean;
  isStarCreator: boolean;
  isVerified: boolean;
  pastUsernames: Array<string>;
  platforms: SearchDiscordPlatforms;
  presence: SearchDiscordPresence;
  socials: { [k: string]: string };
  stats: SearchDiscordStats;
  username: string;
  error?: string | undefined;
  rolimons?: SearchDiscordRolimons | undefined;
};

export type Role = {
  color: number;
  hoist: boolean;
  id: string;
  managed: boolean;
  name: string;
  permissions: string;
  position: number;
};

export type Server = {
  banner: string | null;
  description: string | null;
  icon: string | null;
  id: string;
  invite: string | null;
  membersOnline: number | null;
  name: string | null;
  nickname: string | null;
  totalMembers: number | null;
  roles?: Array<Role> | undefined;
};

export type SearchDiscordData = {
  banner: string | null;
  bio: string | null;
  clan: Clan | null;
  connectedAccounts: {
    [k: string]: ConnectedAccounts1 | Array<ConnectedAccounts2>;
  };
  displayName: string | null;
  internalErrors: Array<string>;
  legacyName: string | null;
  modActions: Array<ModAction>;
  pfp: string;
  presence: string | null;
  pronouns: string | null;
  reviewCount: number;
  reviews: Array<Review>;
  robloxProfiles: Array<RobloxProfile>;
  servers: Array<Server>;
  userId: string;
  username: string;
};

/**
 * Search successful
 */
export type SearchDiscordResponse = {
  data: SearchDiscordData;
  success: boolean;
  error?: string | undefined;
};

/** @internal */
export type SearchDiscordRequest$Outbound = {
  query: string;
};

/** @internal */
export const SearchDiscordRequest$outboundSchema: z.ZodMiniType<
  SearchDiscordRequest$Outbound,
  SearchDiscordRequest
> = z.object({
  query: z.string(),
});

export function searchDiscordRequestToJSON(
  searchDiscordRequest: SearchDiscordRequest,
): string {
  return JSON.stringify(
    SearchDiscordRequest$outboundSchema.parse(searchDiscordRequest),
  );
}

/** @internal */
export const Traits$inboundSchema: z.ZodMiniType<Traits, unknown> = z.object({
  label: types.string(),
  name: types.string(),
  position: types.number(),
  url: types.nullable(types.string()),
});

export function traitsFromJSON(
  jsonString: string,
): SafeParseResult<Traits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Traits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Traits' from JSON`,
  );
}

/** @internal */
export const Clan$inboundSchema: z.ZodMiniType<Clan, unknown> = z.object({
  badge: types.nullable(types.string()),
  banner: types.nullable(types.string()),
  boosts: types.nullable(types.number()),
  description: types.nullable(types.string()),
  features: types.nullable(z.array(types.string())),
  icon: types.nullable(types.string()),
  id: types.string(),
  invite: types.nullable(types.string()),
  memberCount: types.nullable(types.number()),
  name: types.nullable(types.string()),
  onlineCount: types.nullable(types.number()),
  tag: types.nullable(types.string()),
  traits: types.nullable(z.array(z.lazy(() => Traits$inboundSchema))),
});

export function clanFromJSON(
  jsonString: string,
): SafeParseResult<Clan, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Clan$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Clan' from JSON`,
  );
}

/** @internal */
export const ConnectedAccounts2$inboundSchema: z.ZodMiniType<
  ConnectedAccounts2,
  unknown
> = z.object({
  id: types.string(),
  link: types.nullable(types.string()),
  name: types.string(),
});

export function connectedAccounts2FromJSON(
  jsonString: string,
): SafeParseResult<ConnectedAccounts2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConnectedAccounts2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConnectedAccounts2' from JSON`,
  );
}

/** @internal */
export const ConnectedAccounts1$inboundSchema: z.ZodMiniType<
  ConnectedAccounts1,
  unknown
> = z.object({
  id: types.string(),
  link: types.nullable(types.string()),
  name: types.string(),
});

export function connectedAccounts1FromJSON(
  jsonString: string,
): SafeParseResult<ConnectedAccounts1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConnectedAccounts1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConnectedAccounts1' from JSON`,
  );
}

/** @internal */
export const ConnectedAccountsUnion$inboundSchema: z.ZodMiniType<
  ConnectedAccountsUnion,
  unknown
> = smartUnion([
  z.lazy(() => ConnectedAccounts1$inboundSchema),
  z.array(z.lazy(() => ConnectedAccounts2$inboundSchema)),
]);

export function connectedAccountsUnionFromJSON(
  jsonString: string,
): SafeParseResult<ConnectedAccountsUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConnectedAccountsUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConnectedAccountsUnion' from JSON`,
  );
}

/** @internal */
export const Details$inboundSchema: z.ZodMiniType<Details, unknown> = z.object({
  ground: types.string(),
  source: types.string(),
  targetType: types.string(),
});

export function detailsFromJSON(
  jsonString: string,
): SafeParseResult<Details, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Details$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Details' from JSON`,
  );
}

/** @internal */
export const Timeline$inboundSchema: z.ZodMiniType<Timeline, unknown> = z
  .object({
    application: types.number(),
    content: types.number(),
    created: types.number(),
  });

export function timelineFromJSON(
  jsonString: string,
): SafeParseResult<Timeline, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Timeline$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Timeline' from JSON`,
  );
}

/** @internal */
export const ModAction$inboundSchema: z.ZodMiniType<ModAction, unknown> = z
  .object({
    date: types.number(),
    description: types.string(),
    details: z.lazy(() => Details$inboundSchema),
    id: types.string(),
    status: types.string(),
    tags: z.array(types.string()),
    timeline: z.lazy(() => Timeline$inboundSchema),
    title: types.string(),
  });

export function modActionFromJSON(
  jsonString: string,
): SafeParseResult<ModAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModAction' from JSON`,
  );
}

/** @internal */
export const Badge$inboundSchema: z.ZodMiniType<Badge, unknown> = z.object({
  description: types.string(),
  icon: types.string(),
  name: types.string(),
  redirectURL: types.string(),
  type: types.number(),
});

export function badgeFromJSON(
  jsonString: string,
): SafeParseResult<Badge, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Badge$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Badge' from JSON`,
  );
}

/** @internal */
export const Sender$inboundSchema: z.ZodMiniType<Sender, unknown> = z.object({
  badges: z.array(z.lazy(() => Badge$inboundSchema)),
  discordID: types.string(),
  id: types.number(),
  profilePhoto: types.string(),
  username: types.string(),
  clientMod: types.optional(types.boolean()),
});

export function senderFromJSON(
  jsonString: string,
): SafeParseResult<Sender, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sender$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sender' from JSON`,
  );
}

/** @internal */
export const Review$inboundSchema: z.ZodMiniType<Review, unknown> = z.object({
  comment: types.string(),
  id: types.number(),
  sender: z.lazy(() => Sender$inboundSchema),
  timestamp: types.number(),
  type: types.number(),
  star: types.optional(types.number()),
});

export function reviewFromJSON(
  jsonString: string,
): SafeParseResult<Review, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Review$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Review' from JSON`,
  );
}

/** @internal */
export const SearchDiscordPlatforms$inboundSchema: z.ZodMiniType<
  SearchDiscordPlatforms,
  unknown
> = z.object({
  playstation: types.optional(types.string()),
  xbox: types.optional(types.string()),
});

export function searchDiscordPlatformsFromJSON(
  jsonString: string,
): SafeParseResult<SearchDiscordPlatforms, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchDiscordPlatforms$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchDiscordPlatforms' from JSON`,
  );
}

/** @internal */
export const SearchDiscordPresence$inboundSchema: z.ZodMiniType<
  SearchDiscordPresence,
  unknown
> = z.object({
  iconUrl: types.string(),
  lastOnline: types.string(),
  text: types.string(),
  type: types.number(),
});

export function searchDiscordPresenceFromJSON(
  jsonString: string,
): SafeParseResult<SearchDiscordPresence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchDiscordPresence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchDiscordPresence' from JSON`,
  );
}

/** @internal */
export const SearchDiscordStats$inboundSchema: z.ZodMiniType<
  SearchDiscordStats,
  unknown
> = z.object({
  followers: types.number(),
  following: types.number(),
  friends: types.number(),
  placeVisits: types.number(),
});

export function searchDiscordStatsFromJSON(
  jsonString: string,
): SafeParseResult<SearchDiscordStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchDiscordStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchDiscordStats' from JSON`,
  );
}

/** @internal */
export const SearchDiscordRolimons$inboundSchema: z.ZodMiniType<
  SearchDiscordRolimons,
  unknown
> = z.object({
  rap: types.number(),
  value: types.number(),
  rank: types.optional(types.number()),
});

export function searchDiscordRolimonsFromJSON(
  jsonString: string,
): SafeParseResult<SearchDiscordRolimons, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchDiscordRolimons$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchDiscordRolimons' from JSON`,
  );
}

/** @internal */
export const RobloxProfile$inboundSchema: z.ZodMiniType<
  RobloxProfile,
  unknown
> = z.object({
  avatarUrl: types.nullable(types.string()),
  badges: z.array(types.string()),
  created: types.string(),
  description: types.string(),
  displayName: types.string(),
  hasPremium: types.boolean(),
  id: types.number(),
  isAdmin: types.boolean(),
  isBanned: types.boolean(),
  isStarCreator: types.boolean(),
  isVerified: types.boolean(),
  pastUsernames: z.array(types.string()),
  platforms: z.lazy(() => SearchDiscordPlatforms$inboundSchema),
  presence: z.lazy(() => SearchDiscordPresence$inboundSchema),
  socials: z.record(z.string(), types.string()),
  stats: z.lazy(() => SearchDiscordStats$inboundSchema),
  username: types.string(),
  error: types.optional(types.string()),
  rolimons: types.optional(z.lazy(() => SearchDiscordRolimons$inboundSchema)),
});

export function robloxProfileFromJSON(
  jsonString: string,
): SafeParseResult<RobloxProfile, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RobloxProfile$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RobloxProfile' from JSON`,
  );
}

/** @internal */
export const Role$inboundSchema: z.ZodMiniType<Role, unknown> = z.object({
  color: types.number(),
  hoist: types.boolean(),
  id: types.string(),
  managed: types.boolean(),
  name: types.string(),
  permissions: types.string(),
  position: types.number(),
});

export function roleFromJSON(
  jsonString: string,
): SafeParseResult<Role, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Role$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Role' from JSON`,
  );
}

/** @internal */
export const Server$inboundSchema: z.ZodMiniType<Server, unknown> = z.object({
  banner: types.nullable(types.string()),
  description: types.nullable(types.string()),
  icon: types.nullable(types.string()),
  id: types.string(),
  invite: types.nullable(types.string()),
  membersOnline: types.nullable(types.number()),
  name: types.nullable(types.string()),
  nickname: types.nullable(types.string()),
  totalMembers: types.nullable(types.number()),
  roles: types.optional(z.array(z.lazy(() => Role$inboundSchema))),
});

export function serverFromJSON(
  jsonString: string,
): SafeParseResult<Server, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Server$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Server' from JSON`,
  );
}

/** @internal */
export const SearchDiscordData$inboundSchema: z.ZodMiniType<
  SearchDiscordData,
  unknown
> = z.object({
  banner: types.nullable(types.string()),
  bio: types.nullable(types.string()),
  clan: types.nullable(z.lazy(() => Clan$inboundSchema)),
  connectedAccounts: z.record(
    z.string(),
    smartUnion([
      z.lazy(() => ConnectedAccounts1$inboundSchema),
      z.array(z.lazy(() => ConnectedAccounts2$inboundSchema)),
    ]),
  ),
  displayName: types.nullable(types.string()),
  internalErrors: z.array(types.string()),
  legacyName: types.nullable(types.string()),
  modActions: z.array(z.lazy(() => ModAction$inboundSchema)),
  pfp: types.string(),
  presence: types.nullable(types.string()),
  pronouns: types.nullable(types.string()),
  reviewCount: types.number(),
  reviews: z.array(z.lazy(() => Review$inboundSchema)),
  robloxProfiles: z.array(z.lazy(() => RobloxProfile$inboundSchema)),
  servers: z.array(z.lazy(() => Server$inboundSchema)),
  userId: types.string(),
  username: types.string(),
});

export function searchDiscordDataFromJSON(
  jsonString: string,
): SafeParseResult<SearchDiscordData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchDiscordData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchDiscordData' from JSON`,
  );
}

/** @internal */
export const SearchDiscordResponse$inboundSchema: z.ZodMiniType<
  SearchDiscordResponse,
  unknown
> = z.object({
  data: z.lazy(() => SearchDiscordData$inboundSchema),
  success: types.boolean(),
  error: types.optional(types.string()),
});

export function searchDiscordResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchDiscordResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchDiscordResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchDiscordResponse' from JSON`,
  );
}
