/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SearchPhoneRequest = {
  query: string;
};

export type SearchPhoneDob = number | string;

export type SearchPhoneLocal = {
  id: number;
  startDat: number | null;
  address: string | null;
  aka1fullname: string | null;
  aka2fullname: string | null;
  aka3fullname: string | null;
  alt1DOB: number | null;
  alt2DOB: number | null;
  alt3DOB: number | null;
  city: string | null;
  countyName: string | null;
  dob: number | string | null;
  firstname: string;
  lastname: string;
  middlename: string | null;
  nameSuff: string | null;
  phone1: number | null;
  st: string | null;
  zip: number | null;
};

export type LineTypeIntelligence = {
  carrierName: string;
  mobileCountryCode: string;
  mobileNetworkCode: string;
  type: string;
};

export type SmsPumpingRisk = {
  numberBlocked: boolean | null;
  numberBlockedDate: string | null;
  numberBlockedLast3Months: boolean | null;
  carrierRiskCategories?: string | null | undefined;
};

export type SearchPhonePhone = {
  countryCode: string;
  nationalFormat: string;
  phoneNumber: string;
  valid: boolean;
  lineTypeIntelligence?: LineTypeIntelligence | undefined;
  smsPumpingRisk?: SmsPumpingRisk | undefined;
};

export type SearchPhoneWeb = {
  aka?: Array<string> | undefined;
  associates?: Array<string> | undefined;
  children?: number | undefined;
  currentAddress?: string | undefined;
  emails?: Array<string> | undefined;
  error?: string | undefined;
  maritalStatus?: string | undefined;
  name?: string | null | undefined;
  pastAddresses?: Array<string> | undefined;
  phones?: Array<string> | undefined;
};

export type SearchPhoneData = {
  local: Array<SearchPhoneLocal>;
  phone: SearchPhonePhone;
  web: Array<SearchPhoneWeb>;
};

/**
 * Search successful
 */
export type SearchPhoneResponse = {
  data: SearchPhoneData;
  success: boolean;
  error?: string | undefined;
};

/** @internal */
export type SearchPhoneRequest$Outbound = {
  query: string;
};

/** @internal */
export const SearchPhoneRequest$outboundSchema: z.ZodMiniType<
  SearchPhoneRequest$Outbound,
  SearchPhoneRequest
> = z.object({
  query: z.string(),
});

export function searchPhoneRequestToJSON(
  searchPhoneRequest: SearchPhoneRequest,
): string {
  return JSON.stringify(
    SearchPhoneRequest$outboundSchema.parse(searchPhoneRequest),
  );
}

/** @internal */
export const SearchPhoneDob$inboundSchema: z.ZodMiniType<
  SearchPhoneDob,
  unknown
> = smartUnion([types.number(), types.string()]);

export function searchPhoneDobFromJSON(
  jsonString: string,
): SafeParseResult<SearchPhoneDob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPhoneDob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPhoneDob' from JSON`,
  );
}

/** @internal */
export const SearchPhoneLocal$inboundSchema: z.ZodMiniType<
  SearchPhoneLocal,
  unknown
> = z.pipe(
  z.object({
    ID: types.number(),
    StartDat: types.nullable(types.number()),
    address: types.nullable(types.string()),
    aka1fullname: types.nullable(types.string()),
    aka2fullname: types.nullable(types.string()),
    aka3fullname: types.nullable(types.string()),
    alt1DOB: types.nullable(types.number()),
    alt2DOB: types.nullable(types.number()),
    alt3DOB: types.nullable(types.number()),
    city: types.nullable(types.string()),
    county_name: types.nullable(types.string()),
    dob: types.nullable(smartUnion([types.number(), types.string()])),
    firstname: types.string(),
    lastname: types.string(),
    middlename: types.nullable(types.string()),
    name_suff: types.nullable(types.string()),
    phone1: types.nullable(types.number()),
    st: types.nullable(types.string()),
    zip: types.nullable(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "ID": "id",
      "StartDat": "startDat",
      "county_name": "countyName",
      "name_suff": "nameSuff",
    });
  }),
);

export function searchPhoneLocalFromJSON(
  jsonString: string,
): SafeParseResult<SearchPhoneLocal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPhoneLocal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPhoneLocal' from JSON`,
  );
}

/** @internal */
export const LineTypeIntelligence$inboundSchema: z.ZodMiniType<
  LineTypeIntelligence,
  unknown
> = z.pipe(
  z.object({
    carrier_name: types.string(),
    mobile_country_code: types.string(),
    mobile_network_code: types.string(),
    type: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "carrier_name": "carrierName",
      "mobile_country_code": "mobileCountryCode",
      "mobile_network_code": "mobileNetworkCode",
    });
  }),
);

export function lineTypeIntelligenceFromJSON(
  jsonString: string,
): SafeParseResult<LineTypeIntelligence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LineTypeIntelligence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LineTypeIntelligence' from JSON`,
  );
}

/** @internal */
export const SmsPumpingRisk$inboundSchema: z.ZodMiniType<
  SmsPumpingRisk,
  unknown
> = z.pipe(
  z.object({
    number_blocked: types.nullable(types.boolean()),
    number_blocked_date: types.nullable(types.string()),
    number_blocked_last_3_months: types.nullable(types.boolean()),
    carrier_risk_categories: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "number_blocked": "numberBlocked",
      "number_blocked_date": "numberBlockedDate",
      "number_blocked_last_3_months": "numberBlockedLast3Months",
      "carrier_risk_categories": "carrierRiskCategories",
    });
  }),
);

export function smsPumpingRiskFromJSON(
  jsonString: string,
): SafeParseResult<SmsPumpingRisk, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SmsPumpingRisk$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SmsPumpingRisk' from JSON`,
  );
}

/** @internal */
export const SearchPhonePhone$inboundSchema: z.ZodMiniType<
  SearchPhonePhone,
  unknown
> = z.pipe(
  z.object({
    country_code: types.string(),
    national_format: types.string(),
    phone_number: types.string(),
    valid: types.boolean(),
    line_type_intelligence: types.optional(
      z.lazy(() => LineTypeIntelligence$inboundSchema),
    ),
    sms_pumping_risk: types.optional(
      z.lazy(() => SmsPumpingRisk$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "country_code": "countryCode",
      "national_format": "nationalFormat",
      "phone_number": "phoneNumber",
      "line_type_intelligence": "lineTypeIntelligence",
      "sms_pumping_risk": "smsPumpingRisk",
    });
  }),
);

export function searchPhonePhoneFromJSON(
  jsonString: string,
): SafeParseResult<SearchPhonePhone, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPhonePhone$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPhonePhone' from JSON`,
  );
}

/** @internal */
export const SearchPhoneWeb$inboundSchema: z.ZodMiniType<
  SearchPhoneWeb,
  unknown
> = z.object({
  aka: types.optional(z.array(types.string())),
  associates: types.optional(z.array(types.string())),
  children: types.optional(types.number()),
  currentAddress: types.optional(types.string()),
  emails: types.optional(z.array(types.string())),
  error: types.optional(types.string()),
  maritalStatus: types.optional(types.string()),
  name: z.optional(z.nullable(types.string())),
  pastAddresses: types.optional(z.array(types.string())),
  phones: types.optional(z.array(types.string())),
});

export function searchPhoneWebFromJSON(
  jsonString: string,
): SafeParseResult<SearchPhoneWeb, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPhoneWeb$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPhoneWeb' from JSON`,
  );
}

/** @internal */
export const SearchPhoneData$inboundSchema: z.ZodMiniType<
  SearchPhoneData,
  unknown
> = z.object({
  local: z.array(z.lazy(() => SearchPhoneLocal$inboundSchema)),
  phone: z.lazy(() => SearchPhonePhone$inboundSchema),
  web: z.array(z.lazy(() => SearchPhoneWeb$inboundSchema)),
});

export function searchPhoneDataFromJSON(
  jsonString: string,
): SafeParseResult<SearchPhoneData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPhoneData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPhoneData' from JSON`,
  );
}

/** @internal */
export const SearchPhoneResponse$inboundSchema: z.ZodMiniType<
  SearchPhoneResponse,
  unknown
> = z.object({
  data: z.lazy(() => SearchPhoneData$inboundSchema),
  success: types.boolean(),
  error: types.optional(types.string()),
});

export function searchPhoneResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchPhoneResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchPhoneResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchPhoneResponse' from JSON`,
  );
}
