/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SearchWhoisRequest = {
  query: string;
};

export type Dates = {
  created?: string | undefined;
  expires?: string | undefined;
};

export type Raw = {};

export type Registrar = {
  abuseEmail: string;
  abusePhone: string;
  ianaId: string;
  name: string;
  url: string;
};

export type SearchWhoisData = {
  dates: Dates;
  dnssec: { [k: string]: any };
  domain: string;
  nameservers: Array<{ [k: string]: any }>;
  raw: Raw;
  registrar: Registrar;
  status: Array<string>;
};

/**
 * Search successful
 */
export type SearchWhoisResponse = {
  data: SearchWhoisData;
  success: boolean;
  error?: string | undefined;
};

/** @internal */
export type SearchWhoisRequest$Outbound = {
  query: string;
};

/** @internal */
export const SearchWhoisRequest$outboundSchema: z.ZodMiniType<
  SearchWhoisRequest$Outbound,
  SearchWhoisRequest
> = z.object({
  query: z.string(),
});

export function searchWhoisRequestToJSON(
  searchWhoisRequest: SearchWhoisRequest,
): string {
  return JSON.stringify(
    SearchWhoisRequest$outboundSchema.parse(searchWhoisRequest),
  );
}

/** @internal */
export const Dates$inboundSchema: z.ZodMiniType<Dates, unknown> = z.object({
  created: types.optional(types.string()),
  expires: types.optional(types.string()),
});

export function datesFromJSON(
  jsonString: string,
): SafeParseResult<Dates, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Dates$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Dates' from JSON`,
  );
}

/** @internal */
export const Raw$inboundSchema: z.ZodMiniType<Raw, unknown> = z.object({});

export function rawFromJSON(
  jsonString: string,
): SafeParseResult<Raw, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Raw$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Raw' from JSON`,
  );
}

/** @internal */
export const Registrar$inboundSchema: z.ZodMiniType<Registrar, unknown> = z
  .object({
    abuseEmail: types.string(),
    abusePhone: types.string(),
    ianaId: types.string(),
    name: types.string(),
    url: types.string(),
  });

export function registrarFromJSON(
  jsonString: string,
): SafeParseResult<Registrar, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Registrar$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Registrar' from JSON`,
  );
}

/** @internal */
export const SearchWhoisData$inboundSchema: z.ZodMiniType<
  SearchWhoisData,
  unknown
> = z.object({
  dates: z.lazy(() => Dates$inboundSchema),
  dnssec: z.record(z.string(), z.any()),
  domain: types.string(),
  nameservers: z.array(z.record(z.string(), z.any())),
  raw: z.lazy(() => Raw$inboundSchema),
  registrar: z.lazy(() => Registrar$inboundSchema),
  status: z.array(types.string()),
});

export function searchWhoisDataFromJSON(
  jsonString: string,
): SafeParseResult<SearchWhoisData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchWhoisData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchWhoisData' from JSON`,
  );
}

/** @internal */
export const SearchWhoisResponse$inboundSchema: z.ZodMiniType<
  SearchWhoisResponse,
  unknown
> = z.object({
  data: z.lazy(() => SearchWhoisData$inboundSchema),
  success: types.boolean(),
  error: types.optional(types.string()),
});

export function searchWhoisResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchWhoisResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchWhoisResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchWhoisResponse' from JSON`,
  );
}
