/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SendOrganizationCreditsRequestBody = {
  creditsEach: number;
  recipientMemberIds: Array<string>;
};

export type SendOrganizationCreditsRequest = {
  id: string;
  body: SendOrganizationCreditsRequestBody;
};

/**
 * Credits sent.
 */
export type SendOrganizationCreditsResponse = {
  sent: number;
  success: boolean;
  totalCost: number;
};

/** @internal */
export type SendOrganizationCreditsRequestBody$Outbound = {
  creditsEach: number;
  recipientMemberIds: Array<string>;
};

/** @internal */
export const SendOrganizationCreditsRequestBody$outboundSchema: z.ZodMiniType<
  SendOrganizationCreditsRequestBody$Outbound,
  SendOrganizationCreditsRequestBody
> = z.object({
  creditsEach: z.number(),
  recipientMemberIds: z.array(z.string()),
});

export function sendOrganizationCreditsRequestBodyToJSON(
  sendOrganizationCreditsRequestBody: SendOrganizationCreditsRequestBody,
): string {
  return JSON.stringify(
    SendOrganizationCreditsRequestBody$outboundSchema.parse(
      sendOrganizationCreditsRequestBody,
    ),
  );
}

/** @internal */
export type SendOrganizationCreditsRequest$Outbound = {
  id: string;
  body: SendOrganizationCreditsRequestBody$Outbound;
};

/** @internal */
export const SendOrganizationCreditsRequest$outboundSchema: z.ZodMiniType<
  SendOrganizationCreditsRequest$Outbound,
  SendOrganizationCreditsRequest
> = z.object({
  id: z.string(),
  body: z.lazy(() => SendOrganizationCreditsRequestBody$outboundSchema),
});

export function sendOrganizationCreditsRequestToJSON(
  sendOrganizationCreditsRequest: SendOrganizationCreditsRequest,
): string {
  return JSON.stringify(
    SendOrganizationCreditsRequest$outboundSchema.parse(
      sendOrganizationCreditsRequest,
    ),
  );
}

/** @internal */
export const SendOrganizationCreditsResponse$inboundSchema: z.ZodMiniType<
  SendOrganizationCreditsResponse,
  unknown
> = z.object({
  sent: types.number(),
  success: types.boolean(),
  totalCost: types.number(),
});

export function sendOrganizationCreditsResponseFromJSON(
  jsonString: string,
): SafeParseResult<SendOrganizationCreditsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendOrganizationCreditsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendOrganizationCreditsResponse' from JSON`,
  );
}
